### PR TITLE
Disable some old GpuConv tests

### PR DESCRIPTION
**Pull request by nouiz**

### CODE REVIEW

**Comment by lamblin** [comment]
I don't think it is a good idea to keep those tests (and the code tested) around in an unclear state.
If those cases are removed from the code base, then let's remove the tests.
Otherwise, let's keep the tests as long as the code is there.

**Comment by nouiz** [comment]
The utility of the old code is that it do not use extra memory. But it is
so slow that we changed the default.

Do we want to keep the old code? I think we can get rid of it, but i'm not
100% sure. If people want no extra memory convolution, cudnn provide it.

What do you think?

**Comment by abergeron** [comment]
I am of the opinion that if we keep the code, we keep the tests.  However I have no objection to deleting the tests and the code for the old GpuConv.

**Comment by nouiz** [comment]
@lamblin, can you confirm you are ok to delete the old GpuConv Code and
associated test? If so, I'll update the PR.

**Comment by nouiz** [comment]
I'm not convinced that removing it won't cause problems to some user. cudnn is still recent and it do not support all GPUs.

I think that the old tests was too heavy at first. We tested all implementation with all shapes. We also tested the auto-selection mechanism that test only the case implemented for each shapes tested. I keep that set of test. I think we do not need more tests then those. Nobody specify manually which version to use. This depend of each conv in the forward and the grad. There isn't a good mechanism to specify it for the grad. So everybody use the auto-selected implementation.

So I think that testing only the auto-selected version is good enough. In particular with the fact that we tested all combination for a long time on many platform.

So, I just deleted the commented tests to do not pollute the code in a new commit.

**Comment by abergeron** [comment]
Only testing the auto-selection is fine for me.

**Comment by lamblin** [comment]
@nouiz What do you mean by "Nobody specify manually which version to use"? Is there a mechanism that prevents people from doing that? Or are we assuming it is not something people currently do?
If we remove the tests that do not use the auto-selected version, we should make it impossible to use something else than the auto-selected version.

**Comment by abergeron** [comment]
This doesn't close the possibility of somebody manually selecting the version, but we have never come across a use case where somebody did.

I don't think we need to specifically disable the possibility.

**Comment by nouiz** [comment]
I think it is safer to disable it. I'll do that in another PR. I'll raise
an error to tell that this isn't tested anymore, but the user can uncomment
the raise to make it work and that is will probably work. Just in case.

**Pull request merged**
