### PR TITLE
Add deprecation warnings to Conv3D.

### PR DESCRIPTION
**Pull request by abergeron**
Related to #5079

### CODE REVIEW

**Comment by abergeron** [comment]
If by more radical, you mean deleting the files, then I approve and we can close this.

**Comment by nouiz** [comment]
If we don't get Faruk to finish his PR, we can merge this one.

**Comment by nouiz** [comment]
The remove is done in https://github.com/Theano/Theano/pull/6252

**Comment by abergeron** [comment]
While I wholeheartedly approve of outright removal instead of just warnings like here, that PR is nowhere near ready for merge.

**Pull request closed without merging**
