### PR TITLE
Make local_dimshuffle_lift go through many nodes

### PR DESCRIPTION
**Pull request by t13m**
Make local_dimshuffle_lift go through many nodes by recursively calling itself. This commit is following the patch provided by Fred here ( https://github.com/Theano/Theano/issues/2971 ). 

I tested it with following code.
```
import theano                                                                                   
import theano.tensor as T

v = T.vector()
m = T.matrix()
out0 = (v+m).T
out = (out0 + 42).T
theano.config.optimizer_verbose = True
f = theano.function([v, m], out)
```

The output before this optimization as follows,
```
local_dimshuffle_lift DimShuffle{1,0}.0 Elemwise{add,no_inplace}.0
local_dimshuffle_lift DimShuffle{1,0}.0 Elemwise{add,no_inplace}.0
MergeOptimizer tan.0 tan.0
MergeOptimizer sqr.0 sqr.0
...... { MergeOptimizers for many times, ignored here}
MergeOptimizer true_div.0 true_div.0
MergeOptimizer tan.0 tan.0
constant_folding DimShuffle{x,x}.0 TensorConstant{(1, 1) of 42}
local_upcast_elemwise_constant_inputs Elemwise{add,no_inplace}.0 Elemwise{add,no_inplace}.0
local_dimshuffle_lift DimShuffle{1,0}.0 Elemwise{add,no_inplace}.0
local_dimshuffle_lift DimShuffle{1,0}.0 DimShuffle{0,x}.0
local_add_canonizer Elemwise{add,no_inplace}.0 Elemwise{add,no_inplace}.0
local_dimshuffle_lift DimShuffle{1,0}.0 DimShuffle{x,0}.0
local_dimshuffle_lift DimShuffle{1,0}.0 <TensorType(float64, matrix)>
constant_folding DimShuffle{x,x}.0 TensorConstant{(1, 1) of 42.0}
dimshuffle_as_view DimShuffle{x,0}.0 InplaceDimShuffle{x,0}.0
```

The output after is as follows,
```
local_dimshuffle_lift DimShuffle{1,0}.0 Elemwise{add,no_inplace}.0
MergeOptimizer DimShuffle{x,x}.0 DimShuffle{x,x}.0
local_upcast_elemwise_constant_inputs Elemwise{add,no_inplace}.0 Elemwise{add,no_inplace}.0
MergeOptimizer TensorConstant{42} TensorConstant{42}
local_add_canonizer Elemwise{add,no_inplace}.0 Elemwise{add,no_inplace}.0
MergeOptimizer DimShuffle{x,0}.0 DimShuffle{x,0}.0
MergeOptimizer tan.0 tan.0
MergeOptimizer sqr.0 sqr.0
...... { MergeOptimizers for many times, ignored here}
MergeOptimizer true_div.0 true_div.0
MergeOptimizer tan.0 tan.0
constant_folding DimShuffle{x,x}.0 TensorConstant{(1, 1) of 42.0}
dimshuffle_as_view DimShuffle{x,0}.0 InplaceDimShuffle{x,0}.0
```

### CODE REVIEW

**Comment by nouiz** [comment]
Can you check the speed up of this PR on the use case you have?

**Comment by nouiz** [comment]
Can you add a test that call local_dimshuffle_lift.transform() on the graph you used in the description of this PR and check that the output is right? This is to make sure we don't break it later.

**Comment by t13m** [comment]
In this case, the function graph before any optimization is like this,
```
theano.printing.debugprint(out)
```
```
DimShuffle{1,0} [@A] ''   
 |Elemwise{mul,no_inplace} [@B] ''   
   |DimShuffle{x,0} [@C] ''   
   | |Elemwise{add,no_inplace} [@D] ''   
   |   |<TensorType(float64, vector)> [@E]
   |   |DimShuffle{x} [@F] ''   
   |     |TensorConstant{42} [@G]
   |Elemwise{add,no_inplace} [@H] ''   
     |<TensorType(float64, matrix)> [@I]
     |DimShuffle{x,x} [@J] ''   
       |TensorConstant{84} [@K]

```

After compiling, it's like this,
```
theano.printing.debugprint(f.maker.fgraph)
```
```
Elemwise{Composite{(i0 * (i1 + i2))}} [@A] ''   3
 |Elemwise{add,no_inplace} [@B] ''   2
 | |TensorConstant{(1, 1) of 42.0} [@C]
 | |InplaceDimShuffle{0,x} [@D] ''   1
 |   |<TensorType(float64, vector)> [@E]
 |TensorConstant{(1, 1) of 84.0} [@F]
 |InplaceDimShuffle{1,0} [@G] ''   0
   |<TensorType(float64, matrix)> [@H]
```

If only apply local_dimshuffle_lift, 
```
e = theano.gof.FunctionGraph([v,m], [out])
simplify = theano.gof.TopoOptimizer(theano.tensor.opt.local_dimshuffle_lift)
simplify(e)
theano.printing.debugprint(e)
```
```
Elemwise{mul,no_inplace} [@A] ''   6
 |Elemwise{add,no_inplace} [@B] ''   5
 | |DimShuffle{0,x} [@C] ''   3
 | | |<TensorType(float64, vector)> [@D]
 | |DimShuffle{x,x} [@E] ''   2
 |   |TensorConstant{42} [@F]
 |Elemwise{add,no_inplace} [@G] ''   4
   |DimShuffle{1,0} [@H] ''   1
   | |<TensorType(float64, matrix)> [@I]
   |DimShuffle{x,x} [@J] ''   0
     |TensorConstant{84} [@K]
```
It seems all right.

And I tested compiled function f with
```
import numpy as np
nv = np.asarray([1, 2, 3, 4, 5])
nm = np.ones((3, 5))
nm[0,:] = 2
nout = f(nv, nm)
print nout
```
The output is also right.
```
[[ 3698.  3655.  3655.]
 [ 3784.  3740.  3740.]
 [ 3870.  3825.  3825.]
 [ 3956.  3910.  3910.]
 [ 4042.  3995.  3995.]]
```

**Comment by nouiz** [comment]
I understand that you tested it manually. But I think we should add a test in Theano tests suite to make sure we don't break this later.

1) Add a test in theano/tensor/tests/test_opt.py that only apply that optimization and that check that the output graph is right.
2) Profile this opt and give it to me. I would like to see how much speed up it cause. This also affect the order of optimization, so I would like to make sure there isn't unforseen consequence.

**Comment by t13m** [comment]
The profile is here: 
before, https://gist.github.com/t13m/a6931e342ef1be00d552#file-opt3_before
after, https://gist.github.com/t13m/a6931e342ef1be00d552#file-opt3_after_0

**Comment by t13m** [comment]
The profiling output of the user case is here https://gist.github.com/t13m/a6931e342ef1be00d552#file-opt3_usercase_after_0

**Comment by t13m** [comment]
Test added.

**Comment by t13m** [comment]
In the test, out2in(local_dimshuffle_lift).optimize() is used, which should be local_dimshuffle_lift.transform(). But I don't know how to get the string form of the optimized graph of transformed node.

**Comment by nouiz** [comment]
I think this PR is ready to merge when travis pass. thanks.

**Comment by t13m** [comment]
Thanks.

**Pull request merged**
