### PR TITLE
Force older conda version on travis

### PR DESCRIPTION
**Pull request by abergeron**
This should hopefully fix the no-blas condition on travis.

fix gh-4187

### CODE REVIEW

**Comment by abergeron** [comment]
Now this is working.

**Comment by nouiz** [comment]
ok to merge when travis pass.

**Comment by lamblin** [comment]
`The command "python -c 'import theano; assert(theano.config.blas.ldflags != "")'" exited with 1.`

**Comment by lamblin** [comment]
The assert passed, so I'm merging.

**Pull request merged**
