### PR TITLE
fix flake8 whitelist on windows

### PR DESCRIPTION
**Pull request by slefrancois**

### CODE REVIEW

**Comment by slefrancois** [comment]
jenkins test win

**Comment by slefrancois** [comment]
jenkins test this

**Comment by slefrancois** [comment]
jenkins test windows

**Comment by nouiz** [comment]
I don't get why this is needed. It was working in the past. Also, in python, the directory separator is the same on all OS I think.

**Comment by slefrancois** [comment]
Since we moved the windows buildbot to a new machine, the python os module has been generating paths with \ as the separator. The whitelist hardcodes / as the separator, hence the comparison was failing.

**Comment by slefrancois** [comment]
flake8 wasn't installed before so it was skipped:
http://earlgrey.iro.umontreal.ca:8080/job/Theano_pr_win/32/testReport/theano.tests/test_flake8/test_format_flake8/

**Pull request merged**
