### PR TITLE
Fix compilation on mac with CLT 7.3

### PR DESCRIPTION
**Pull request by abergeron**
This should get a test with CLT 7.2 to make sure it still works, but I'm confident it will.

fix gh-4277

### CODE REVIEW

**Comment by nouiz** [comment]
thanks to merge when travis pass.

**Comment by abergeron** [comment]
I've tested it with CLT 7.2 and it works.

**Comment by PierrotLC** [comment]
Thank you ! it works !

**Comment by aliostad** [comment]
Sorry what worked for you? It is broken for me with 0.8.0 on Mac.
Do I need to downgrade my XCode CLT or the theano itself has been updated?

**Comment by nouiz** [comment]
You need to update Theano to the dev version.
Le 27 mars 2016 18:24, "Ali Kheyrollahi" <notifications@github.com> a
écrit :

**Comment by aliostad** [comment]
@nouiz sorry do you mean get the source run python setup.py dist?

**Comment by nouiz** [comment]
See:

http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

**Comment by lamblin** [comment]
You can update to 0.8.1, which includes this fix.

**Comment by kdj842969** [comment]
Get my problem solved! Thanks!

**Pull request merged**
