### PR TITLE
Fix windows test problems.

### PR DESCRIPTION
**Pull request by abergeron**

### CODE REVIEW

**Comment by lamblin** [comment]
Crap, there are a couple of new `isinstance(..., int)` in `theano/tensor/nnet/abstract_conv.py` now.

**Comment by nouiz** [comment]
ok for me, but I saw that lamblin have a comment.

**Comment by abergeron** [comment]
I've fixed the new 'int's in abstractconv.

**Comment by nouiz** [comment]
ok to merge when travis pass.

**Comment by nouiz** [comment]
travis is failing:

```
  File "/home/travis/build/Theano/Theano/theano/scan_module/scan.py", line 375, in scan
    if isinstance(n_steps, (float, integer_types)):
NameError: global name 'integer_types' is not defined

```

**Pull request merged**
