### PR TITLE
Cast Py_None to PyTypeObject * to satisfy g++ 4.9.

### PR DESCRIPTION
**Pull request by abergeron**
Otherwise there are a bunch of compile errors in the new backend.

### CODE REVIEW

**Comment by abergeron** [comment]
If this seems too weird I have another option which is to change the type of all the APIs in cython to take `object` instead of `type`.  That also works.

**Comment by nouiz** [comment]
It is not very user friendly. Can you explain why g++ 4.9 have problem?
What is the consequence of using object instead of type? Less type checking
from cython when we call the function?

**Comment by lamblin** [comment]
From my perspective, the issue is that `None` is not a type, so `Py_None` is not a `PyTypeObject *`.
If Cython is doing some checks on the passed value, expecting a `PyTypeObject *`, those checks would be meaningless on a casted `Py_None`. If there are some optimizations done by the compiler, then they may be wrong.

**Comment by abergeron** [comment]
Ok I'll roll the changes in the allocation PR for libgpuarray.

**Comment by nouiz** [comment]
I didn't saw this in current PR and I didn't saw a new PR.

**Pull request closed without merging**
