### PR TITLE
Added missing softsign import

### PR DESCRIPTION
**Pull request by mgermain**

### CODE REVIEW

**Comment by nouiz** [comment]
This would slow down the import of theano, but it is probably good.

@abergeron @lamblin do you agree?

**Comment by mgermain** [comment]
Well, I think it is just missing. Either have all the activation functions there or none?

**Comment by abergeron** [comment]
Yes I am ok.

If importing an additional symbol from an already-imported file results in any measurable differnece to the total import time of Theano, then you should stop trying to run python on a 8086.

**Comment by lamblin** [comment]
I don't think it is going to slow down anything, as `sigm.py` is already parsed and compiled in order to import other symbols.

**Comment by abergeron** [comment]
Or at least I would be if the softsign function was actually in the file this is trying to import it from.  softsign is in nnet, not sigm.

**Pull request merged**
