### PR TITLE
Remove the custom version check in the __init__ of pygpu.

### PR DESCRIPTION
**Pull request by abergeron**
We will now use the soversion like for everything else.

### CODE REVIEW

**Comment by nouiz** [comment]
@lamblin are you ok to use shared lib versioning for libgpuarray work?

What about pygpu versioning? We didn't had check related to that should we?

**Comment by lamblin** [comment]
Sure, why not?
For pygpu, we can just use the version of the Python package, like the usual dependencies.

**Comment by nouiz** [comment]
@abergeron, can you add a check for pygpu version here? With that I'm good
with the PR.

**Comment by abergeron** [comment]
There is currently no way to check the pygpu version.

**Comment by abergeron** [comment]
This needs https://github.com/Theano/libgpuarray/pull/300

**Comment by nouiz** [comment]
jenkins test this

**Pull request merged**
