### PR TITLE
[CRASH] Improve shared variable management in Scan

### PR DESCRIPTION
**Pull request by carriepl**
~~Those checks were added for the sake of completeness in a previous PR but they were not required for any use case known at that time.~~

~~This PR deactivates them for the time being because it appears these checks are causing issues with valid graphs (https://groups.google.com/forum/#!topic/theano-users/y7Nb8oYRUa0).~~

~~Since they are not required anywhere, they can be deactivated for the time being but we should go back eventually to figure out why.~~

Updated description:
The PR changes the way Scan handles some shared variables as recurrent outputs to make sure the associated and outputs are on the CPU. 

The current way it's implemented would mistakenly have MRG_RandomStreams with an input state on the CPU and the output state on GPU. This wasn't caught by anything but, eventually, through the optimization process, the graph was modified and made consistent so no one ever had any issue with this. The recently-added checks for the consistency of the inner graph caught the inconsistency and that is what caused the crash.

### CODE REVIEW

**Comment by nouiz** [comment]
Can you add a scan test with the case that caused problem? That way, when we try to reintroduce it we will be sure to not break it again.

**Comment by carriepl** [comment]
I updated the PR. It turns out that the checks were not the issue but rather the way Scan handled some shared variables. It allowed them to have input states on the CPU but output states on the GPU. This was fixed during the optimization process so no one ever had any issue related to this before but now that we have checks for the consistency of the inner graph, we could actually detect this invalid state.

**Comment by udibr** [comment]
Just adding more info on problems I observed related to this issue:

I got the  error message:
TypeError: Inconsistency in the inner graph of scan 'scan_fn' : an input and an output are associated with the same recurrent state and should have the 
same type but have type 'TensorType(float32, vector)' and 'CudaNdarrayType(float32, vector)' respectively.

I found that the problem happens with any test value set and testing enabled:

<code>
theano.config.compute_test_value = 'warn'
x.tag.test_value = np.ones((max_steps,batch_size,3)).astype(np.float32)
</code>

or using np.random... to initalize test value for x
but when I remove the testing (comment out the theano.config.compute_test_value = 'warn') then the error disappers

**Comment by nouiz** [comment]
Can you update the description of this issue?

I'm ok with this PR, but if @lamblin or @abergeron can confirm they are ok with this before merging, it would be better.

**Comment by carriepl** [comment]
I updated the description.

**Comment by nouiz** [comment]
Do you think it is useful to add a test that check if the code get optimized correctly on the GPU?

**Comment by lamblin** [comment]
The fix seems to make sense, but I have two questions:
- What if `new_var` is actually not a tensor? Should we convert `input.update` to that type instead?
- I'm afraid this change will prevent the whole thing from moving to the GPU. It would be good to have a test checking that the optimized graph do not have useless transfers.

**Comment by carriepl** [comment]
I added a check that the scan gets moved on the GPU. I think this should be enough and, since we're working on making scan work on the gpuarray backend, this makes the test work on both backends without having to check for transfer nodes from both backends.

**Pull request merged**
