### PR TITLE
Delete deprecated

### PR DESCRIPTION
**Pull request by abergeron**
Fix the last problem with #2589 for merge.

### CODE REVIEW

**Comment by lamblin** [comment]
Fixes #2561.
Fixes #2564.

**Comment by lamblin** [comment]
The documentation still mentions (at least):
- `Module` and related objects (`External`, `Component`, ...)
- `c&py`
- `theano.sandbox.linalg.kron`
- `theano.tensor.randomstreams.RandomStreams`

**Comment by abergeron** [comment]
I've made a bit of a cleanup in the documentation, but there may still be some cruft.

**Comment by abergeron** [comment]
Also this could benefit from a test run on a machine with a GPU.

**Comment by nouiz** [comment]
I started tests on GPU and some fails. I'll post the result when they finish.

**Comment by lamblin** [comment]
My GPU test run worked correctly, so I'm merging.

**Pull request merged**
