### PR TITLE
Pooling rop

### PR DESCRIPTION
**Pull request by aam-at**
Continuation of #4781 and all work which was done before.

I updated max pool rop implementation which now supports arbitrary ndim for pure python and cpu openmp implementation. I also dropped support for old backend and instead added support only for new backend.

Also as a sidenote, there is a large overlap between max pooling and max pooling rop. Max pooling reduces to max pooling rop if eval point is equal to the input. For now, I didn't do any refactoring and just duplicated code for max pooling with minor changes for rop.

fix gh-4387

### CODE REVIEW

**Comment by aam-at** [comment]
Travis fails on pooling rop - No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself
When I run tests on locally, I don't have any problems though.

**Comment by lamblin** [comment]
Jenkins test this please

**Comment by lamblin** [comment]
I may be mistaken, but I think this is the same mathematical operation as `DownsampleFactorMaxGradGrad`, which also reduces to max pooling if `ggx` is equal to `x`.
Could you check if I missed something and there is a difference?

**Comment by aam-at** [comment]
Correct me if I am wrong: the output shape of `DownsampleFactorMaxGradGrad` is the same as `z`. And max pool rop will be equivalent to it only if `ws` and `stride` are both 1. `GradGrad` uses maximum in output `z` and sums ups corresponding elements in `gx` (overlaps are possible). Rop uses maximum in the input and find corresponding elements in `ex`.

Relevant part from gpu kernel for pool2d_grad_grad:
``` c
if (z[index] == x_slice[h * width + w]) {
  gradient += gx_slice[h * width + w];
}
```
and pool2d_rop:
``` c
if (x_slice[(d*height + h)*width + w] > maxval) {
  maxval = x_slice[(d*height + h)*width + w];
  collector = ex_slice[(d*height + h)*width + w];
}
```

**Comment by lamblin** [comment]
OK, so the difference is that rop recomputes the maximum in the input in order to select the element from `ex`, whereas gradgrad checks the positions where the input is equal to its (already precomputed) max `z`.
In gradgrad, `z`'s size is the size of `max_pool(x)`, `ggx` has the same shape as `x`, and the output of gradgrad has the same shape as `z`.
If I understand correctly, the rop's output has the same shape as `max_pool(x)` as well, right?

So the mathematical expressions should be equivalent (at least when the position of the max is not ambiguous), but the way to arrive to it are different (the max is pre-computed vs. recomputed). I really don't know which approach is the best in general. We could have both implementations, but then both would need to be available for each of the operations (MaxPoolGrad.grad and MaxPool.Rop), maybe an optimization could be used to switch between them.

**Comment by aam-at** [comment]
The output shape of max pool rop is the same as `x`. In this sense rop operation is similar to `MaxPoolGrad`. And the computation itself is similar to `MaxPool`. Compare above rop snippet with the  computation for max pool kernel:
``` c
if (x_slice[h*width + w] > maxval) {
  maxval = x_slice[h*width + w];
}
```
So max pool rop selects values in `ex` which correspond to the maximum in `x`. Output will have block like structure of repeated values from `ex`.

I think we can't reuse any other operations for general case. For corner cases though some ops are equivalent but it is not straightforward to generalize.

**Comment by aam-at** [comment]
I deleted my previous comment as it was incorrect. You are right that `MaxPoolRop` returns shape of size `z`. And yes, I also think that when there are no ambiguity for max value both operation should return same  result.

**Comment by nouiz** [comment]
Currently, we aren't consistent how we handle ambiguous max value. We
should select only one in all cases as cudnn/caffe does.

Do you know how the new op handle the ambiguous cases?

**Comment by aam-at** [comment]
This new op `MaxPoolRop` chooses only one maximum value. `MaxPoolGradGrad` accumulates them. With the exception of this, both operations are mathematically equivalent. Implementation-wise, `MaxPoolGradGrad` requires pre-computed maximum values. So if understand @lamblin correctly, we can optimization which chooses between two implementations whenever pre-computed `z` is available.

**Comment by aam-at** [comment]
What else should I finish, so you can accept this pull request?

**Comment by lamblin** [comment]
Sorry about the delay, I just came back from the holidays.
We decided to keep a larger refactorization (and harmonization) for later, in particular concerning the behaviour when several values tie for the maximum.

For now, the remaining issue is that `Pool.R_op()` and `MaxPoolGrad.grad()` return different Ops, even though it is the same operation and they should be merged if needed.

Would it be possible for you to make `Pool.R_op()` return an instance of `MaxPoolGradGrad`? We are still interested in your implementation that is in `MaxPoolRop`, and we are considering making it the default version in the refactorization mentioned above, so you can leave it as part of the PR.

Thanks,

**Comment by aam-at** [comment]
I updated `Rop` which return `MaxPoolGradGrad` for now.

If we decide to implement case 3 from #5404, I can work on it. I am not sure what you mean by a larger refactorization but changes to c++ code for cpu and gpu should be fairly easy. For example for gpu `MaxPoolGradGrad`, we can just break from innermost cycle once the corresponding maximum is found:
```c++
bool should_stop = false;
for (ga_size h=hstart; h < hend && !should_stop; ++h) {
  for (ga_size w=wstart; w < wend && !should_stop; ++w) {
  // maximum in the region
  if (z[index] == x_slice[h * width + w]) {
    gradient = gx_slice[h * width + w];
    should_stop = true;
  }
}
```

**Comment by lamblin** [comment]
Jenkins test this please

**Comment by nouiz** [comment]
merging as @lamblin approved. We can continue the discussion in the issue.

thanks

**Comment by nomader** [comment]
Similar analysis: https://github.com/Theano/Theano/issues/4568

**Pull request merged**
