### PR TITLE
Use the testcode facility to test code examples directly

### PR DESCRIPTION
**Pull request by abergeron**
This can help avoid mismatch between implementation and documentation.  The previous method of copying the example into a test file is cumbersome and prone to errors.

This supersedes #3228

### CODE REVIEW

**Comment by abergeron** [comment]
Almost all of the code examples in the documentation are now tested for correctness and those tests pass.

Numerous mistakes where fixed in the process.  Code involving the GPU is not tested at the moment, as is code that need pydot.  Scipy is assumed to be present on the test machine.

This is not enabled to be run on travis right now, but I can add it.  The time to run all the tests on my machine is less than 5 minutes (with a hot cache).

**Comment by carriepl** [comment]
At @abergeron's request, I had a look at his commits (starting at cec5647). It *looks* fine to me.

**Comment by abergeron** [comment]
This means it can be merged.  Please do.

**Comment by nouiz** [comment]
This need a rebase.

**Comment by abergeron** [comment]
Rebase is done.

**Pull request merged**
