### PR TITLE
Handle filter_dilation in the abstractconv_grad* perform methods

### PR DESCRIPTION
**Pull request by ballasn**

### CODE REVIEW

**Comment by ballasn** [comment]
should we add some tests to make sure that the abstract_op are tested in debugmode, to avoid this kind of issue in the future?

**Comment by lamblin** [comment]
DebugMode may be overkill, but we could have some tests execute with optimizer='None', and compare with the reference value.

**Comment by lamblin** [comment]
Otherwise, it looks reasonable, assuming the tests currently pass in debugmode.

**Comment by nouiz** [comment]
Test pass in debugmode. So I merge to fix the daily buildbot now. Test in normal mode are still missing:

thanks

$ THEANO_FLAGS=mode=DEBUG_MODE theano-nose theano/tensor/nnet/tests/test_abstract_conv.py
.......................................................................................................................................................................................................................................................................................................................................................................................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS......................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS......................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS......................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS......................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS......................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS....
----------------------------------------------------------------------
Ran 705 tests in 3215.588s

OK (SKIP=216)

**Pull request merged**
