### PR TITLE
PR cache correct

### PR DESCRIPTION
**Pull request by slefrancois**
In progress

### CODE REVIEW

**Comment by slefrancois** [comment]
jenkins test win

**Comment by slefrancois** [comment]
jenkins test this

**Comment by abergeron** [comment]
It doesn't seem to have sped up anything.  Also, this version of the cache code will reuse the cache between PRs between rebuilds of the cache.

You could try to use rsync --delete to remove the differing files from the destination so you don't have to copy from scratch all the time.

**Comment by slefrancois** [comment]
I put and rm -rf first to avoid reusing the previous PR cache. Also I don't think rsync --delete would change anything since before I was copying onto the docker filesystem, which is reset everytime.

**Comment by slefrancois** [comment]
jenkins test this

**Comment by slefrancois** [comment]
jenkins test this

**Comment by slefrancois** [comment]
jenkins test mac

**Comment by nouiz** [comment]
Closing for now. We need to first make Theano better support moving/coping its cache.

**Pull request closed without merging**
