### PR TITLE
Modifications for 1.0.3 release

### PR DESCRIPTION
**Pull request by twiecki**

### CODE REVIEW

**Comment by abergeron** [comment]
The new doc has warnings: https://travis-ci.org/Theano/Theano/jobs/428515506#L1285

**Comment by twiecki** [comment]
@abergeron should be fixed.

**Comment by twiecki** [comment]
Tests pass.

**Comment by twiecki** [comment]
Seems like tags do not get merged, at least it doesn't show up in the releases yet: https://github.com/Theano/Theano/releases

What are the other next steps? Uploading to pypi and announcing on the mailing list?

**Comment by abergeron** [comment]
Oh, yeah.  For tags you have to push it directly to the master, which means that you need commit access.  I can do that part.

You can build the pypi packages, but you might have trouble uploading since it think you need an authorized account for the project there.  @nouiz should know more about that part.

After that you can indeed do the announcement on the mailing lists.  That shouldn't require and special privilege.

**Comment by abergeron** [comment]
Apparently the automatic package upload have failed because the anaconda tokens expired.  I'll have to replace them on Monday.  I've made an issue to remember that: #6643

**Comment by abergeron** [comment]
I've updated the tokens, so they should be good for another year.  I've also pushed pack the tag one commit to include the new tokens. If you've already built the pypi packages, it's fine since there is absolutely no code change in the new commit.

**Comment by abergeron** [comment]
The conda packages are up.

**Comment by nouiz** [comment]
I'll check tomorrow to give you access to pypi.

**Comment by twiecki** [comment]
@abergeron Seems like the packages on anaconda and conda-forge are still 1.0.2: https://anaconda.org/anaconda/theano https://anaconda.org/conda-forge/theano

I uploaded the release to pypi.

**Comment by nouiz** [comment]
@abergeron can update those on conda-forge.

But for those of anaconda, it is the anaconda team that need to do it. I
already pinged them in the past, but for a minor release, I would wait a
little before asking them.

**Comment by abergeron** [comment]
conda-forge has a bot which does automatic updates: https://github.com/conda-forge/theano-feedstock/pull/23 (you still need someone to approve the PR once it passes, which I can do).

**Pull request merged**
