### PR TITLE
libraries not found by g++ are now printed to the user.

### PR DESCRIPTION
**Pull request by ChihebTrabelsi**

### CODE REVIEW

**Comment by nouiz** [comment]
@notoraptor can you test it on linux?

**Comment by notoraptor** [comment]
Testing on Linux is surprisingly harder, as `libpython` library is in `ldconfig` cache, and it seems it comes with default Ubuntu Python package (which seems to be important for many other packages on the system!). So, even when I hide standard folders added by Theano, compilation still succeeds.

I'm still looking for a best way to test it.

**Comment by notoraptor** [comment]
Done. When manually renaming `libpython*.a` and `libpython*.so` and then running `sudo ldconfig`, the error occurs:

```
===============================
Problem occurred during compilation with the command line below:
/usr/bin/g++ -shared -g -march=haswell -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mmovbe -maes -mno-sha -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mbmi2 -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=3072 -mtune=haswell -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -I/media/notoraptor/Windows/Users/HPPC/mila/dev/git/theano/theano/gof -L/usr/lib -fvisibility=hidden -o /home/notoraptor/.theano/compiledir_Linux-4.4--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-2.7.12-64/lazylinker_ext/lazylinker_ext.so /home/notoraptor/.theano/compiledir_Linux-4.4--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-2.7.12-64/lazylinker_ext/mod.cpp -lpython2.7
/usr/bin/ld : ne peut trouver -lpython2.7
collect2: error: ld returned 1 exit status

library python2.7 is not found.
Check if package python-dev 2.7 or python-devel 2.7 is installed.
```

So, it works on Linux.

**Comment by nouiz** [comment]
thanks

**Pull request merged**
