### PR TITLE
Resolve conflicts Rop implementation for Pool(mode='max')

### PR DESCRIPTION
**Pull request by alexlee-gk**
Following up on PR #4412 by @AndreasMadsen

Added minor changes for DownsampleFactorMaxRop to inherit from OpenMPOp, analogous to the other pooling classes.

Original implementation was done by @nouiz and @rodrigob in #3587

/cc @nouiz @AndreasMadsen

### CODE REVIEW

**Comment by AndreasMadsen** [comment]
Oh, thanks for taking care of this, I completely forgot about it.

**Comment by alexlee-gk** [comment]
I just noticed that I didn't modify the string returned by `DownsampleFactorMaxRop.c_code` to use `#pragma omp parallel`, so this class is not implementing the `OpenMPOp` contract at all.

We can either (1) fix that string or (2) revert the changes in `DownsampleFactorMaxRop` so that it inherits from `Op` instead of `OpenMPOp`. I can do the latter, but I don't think I'll have time to do the former. Let me know what's the best way to proceed.

**Comment by nouiz** [comment]
The best would be to get this merged. I need someone else to verify the
test.

So if you don't have the time for the OpenMP version, then do the other. I
don't know anyone else who will do it.

**Comment by alexlee-gk** [comment]
Alright, I updated the commit to keep `DownsampleFactorMaxRop` without OpenMP for now.

I also updated the tuples returned by `c_code_cache_version` of the other pooling classes to enforce the method's contract.

**Comment by aam-at** [comment]
I need that. Is that okay if I pick up this pull request to finish it?

**Comment by alexlee-gk** [comment]
It's okay with me. Thanks for taking care of this.

**Comment by nouiz** [comment]
continued in https://github.com/Theano/Theano/pull/5323

**Pull request closed without merging**
