### PR TITLE
Good implementation of shape_i() optimized function

### PR DESCRIPTION
**Pull request by nouiz**
In the past, we where not causing all the graph to be optimized by the shape feature. We need to add the node in the toposort order. We add only the nodes that aren't already in the shape feature.

### CODE REVIEW

**Comment by nouiz** [comment]
@lamblin can you review it? I think you are the only one who know enough ShapeFeature to see potential problems. If I'm wrong and someone else know it engough, do not hesitate to review it.

**Comment by lamblin** [comment]
On a first look, it seems reasonable, I'll give a new look tomorrow.
I'm not sure why we were not doing that before. Maybe we did not want to import all other nodes unless the output gets actually used in the graph, in which case they would be imported through the regular way in the fgraph, and the feature's `on_import` method would be triggered at that point.
Also, does calling `feature.on_import` set the `fgraph` attribute? If not, then the function could be called many times on the same variable. But if it does, it would prevent the variable from being properly imported in the graph in the future.
Do you have any case where it makes a difference? That could make a test case.

**Comment by nouiz** [comment]
It wasn't done like this before because it is very recent. I added it late
last week. This is to prevent some optimization that do big graph
replacement to generate too much work for the optimizer, that would cause
after that Equilibrium max'out.

on_import() do not add the fgraph attribute. I do not think this cause
problem If we call on_import() on the same node many times, this do not
cause problem we inside that method, we check if it know that node and if
so, nothing is done. The only reason to not call it on node that have an
fgraph is to remove useless work (and that could be much for big graph).

The fact that a node is in the shapefeature before being in the fgraph do
not cause problem when we introduce it in the graph. When
shape_feature.on_import() will get called, it won't redo the work. This is
already happening when we revert some optimization.

**Comment by lamblin** [comment]
In that case, are we sure that this change does not make optimization run for too long?
It does not seem to be a problem for travis (run time is approximately the same), though.

**Comment by nouiz** [comment]
Currently, travis didn't trigger its usage, as it is currently only used on
GPU opt.

I didn't time it, but the tests didn't fell slower of faster. But as it is
already slow, I wouldn't have remarked small change.

In theory, it should be faster as we remove change in the graph during the
optimization phase.

**Comment by lamblin** [comment]
OK, the idea works for me.
Can you add the test you've mentioned as a unit test?

**Comment by nouiz** [comment]
I'm not sure you make reference to what. The first version of shape_i()
function fixed a test that is already in Theano. It was conv test on the
gpu that add cudnn op. The opt was creating a big graph from one node, so
it caused too much work and this triggered a equilibrium max'out.

if you refer to that test, it is already in Theano. Or do you make a
reference to another test?

**Comment by lamblin** [comment]
So this removes a warning that is currently happening in the nightly buildbot, is that correct?

**Comment by nouiz** [comment]
This do not fix anything in the current buildbot, as the first fix wasn't working in the general case. But the first fix fixed errors and so we know that this PR do at least cover that case.

**Pull request merged**
