### PR TITLE
Fixed error in the keyword for cuDNN

### PR DESCRIPTION
**Pull request by Pastafarianist**

### CODE REVIEW

**Comment by abergeron** [comment]
What keyword error do you get exactly?  conv_dnn is the proper optimizer to disable here.

**Comment by Pastafarianist** [comment]
@abergeron I am running [this image](http://thecloudmarket.com/image/ami-735bda04--ubuntu14-04-mkl-cuda-dl) on a g2.2xlarge Amazon EC2 instance. cuDNN is built incorrectly there, so I was receiving this error:

    Using gpu device 0: GRID K520
    Traceback (most recent call last):
      File "/home/ubuntu/repositories/pylearn2/pylearn2/scripts/train.py", line 71, in <module>
        from pylearn2.utils import serial
      File "/home/ubuntu/repositories/pylearn2/pylearn2/__init__.py", line 4, in <module>
        from pylearn2.utils.logger import configure_custom
      File "/home/ubuntu/repositories/pylearn2/pylearn2/utils/__init__.py", line 10, in <module>
        import theano
      File "/home/ubuntu/repositories/theano/theano/__init__.py", line 102, in <module>
        theano.sandbox.cuda.tests.test_driver.test_nvidia_driver1()
      File "/home/ubuntu/repositories/theano/theano/sandbox/cuda/tests/test_driver.py", line 32, in test_nvidia_driver1
        profile=False)
      File "/home/ubuntu/repositories/theano/theano/compile/function.py", line 265, in function
        profile=profile)
      File "/home/ubuntu/repositories/theano/theano/compile/pfunc.py", line 511, in pfunc
        on_unused_input=on_unused_input)
      File "/home/ubuntu/repositories/theano/theano/compile/function_module.py", line 1545, in orig_function
        on_unused_input=on_unused_input).create(
      File "/home/ubuntu/repositories/theano/theano/compile/function_module.py", line 1250, in __init__
        optimizer_profile = optimizer(fgraph)
      File "/home/ubuntu/repositories/theano/theano/gof/opt.py", line 90, in __call__
        return self.optimize(fgraph)
      File "/home/ubuntu/repositories/theano/theano/gof/opt.py", line 81, in optimize
        ret = self.apply(fgraph, *args, **kwargs)
      File "/home/ubuntu/repositories/theano/theano/gof/opt.py", line 195, in apply
        sub_prof = optimizer.optimize(fgraph)
      File "/home/ubuntu/repositories/theano/theano/gof/opt.py", line 81, in optimize
        ret = self.apply(fgraph, *args, **kwargs)
      File "/home/ubuntu/repositories/theano/theano/gof/opt.py", line 195, in apply
        sub_prof = optimizer.optimize(fgraph)
      File "/home/ubuntu/repositories/theano/theano/gof/opt.py", line 81, in optimize
        ret = self.apply(fgraph, *args, **kwargs)
      File "/home/ubuntu/repositories/theano/theano/sandbox/cuda/dnn.py", line 1400, in apply
        dnn_available.msg)
    AssertionError: cuDNN optimization was enabled, but Theano was not able to use it. We got this error:
    Theano is not able to use cuDNN. We got this error:
    /tmp/ccSCeAps.o: In function `main':
    try_flags_oDWUPz.c:(.text+0x37): undefined reference to `cudnnGetErrorString'
    collect2: error: ld returned 1 exit status

Adding `optimizer_excluding=conv_dnn` to `THEANO_FLAGS` had absolutely no effect on the problem. Adding `optimizer_excluding=cudnn` eliminated it. Seems like the right keyword is `cudnn` after all.

**Comment by abergeron** [comment]
If you want to completely disable cudnn, then yes, using optimizer_excluding=cudnn is right, but that section is discussing convolution, and in that case, conv_dnn is the appropriate tag since it only disables the convolution op using cudnn.

The other problem you seem to have is that theano should be detecting whether you have cudnn or not and just disable it if it is not found.  The behaviour you posted should only happen when you explicitly set optimizer_including=cudnn somewhere.  I would double check your theano config (including .theanorc and the environment) to make sure you don't explicitly enable cudnn.

**Comment by nouiz** [comment]
Can you confirm there was a configuration problem on your side? If not,
maybe the local_conv_dnn_alternative optimization isn't correctly
registered.

For cudnn, I do not know why, but If I have multiple cudnn version in my
env variable like INCLUDE, CPATH, LIBRARY_PATH, LD_LIBRARY_PATH, I also
have this errors. I think something mess with the order of those path.

Can you confirm if you are also in that same case? If I use only 1 cudnn
version in those variable, all work correctly for me.

**Comment by Pastafarianist** [comment]
Unfortunately, I won't be able to confirm it in the foreseeable future, since I do not intend to run any Amazon instances.
I did not notice that that part was discussing convolutions, so my apologies.

**Pull request closed without merging**
