### PR TITLE
Added small gradient calculation for batched_dot

### PR DESCRIPTION
**Pull request by briancheung**
Wrote a quick gradient for the new batched_dot op just to get the ball rolling. Let me know what else needs to be written.

### CODE REVIEW

**Comment by nouiz** [comment]
thanks. can you add test for the gradient? http://deeplearning.net/software/theano/tutorial/extending_theano.html#testing-the-gradient

**Comment by briancheung** [comment]
Anything else needed for this PR?

**Comment by nouiz** [comment]
Thanks. I did a PR to your PR to fix the test with mode=FAST_COMPILE

https://github.com/briancheung/Theano/pull/1

We run our daily buildbot in that mode. If you want to tests with all modes that our daily buildbot test, you can use theano/misc/do_nightly_build .... instead of nosetests ...

With that, we can merge your PR. thanks

Also, when you update a PR with new commit, we don't get notified. So if you want us to see it faster, just make a comment in the PR. That send us a notification.

**Comment by nouiz** [comment]
thanks

**Pull request merged**
