### PR TITLE
[CRASH ] Fix crash in scan.grad when same variable used for multiple outputs

### PR DESCRIPTION
**Pull request by carriepl**

### CODE REVIEW

**Comment by abergeron** [comment]
I can't help but notice that your test doesn't cover the case where both outputs are of the same type.

Have you not been able to get an error with that case?

**Comment by carriepl** [comment]
I haven't been able so far, with the setups I've tried, either when both outputs are nitsots, sitsots or mitsots.  So far, I got crashes when one was a nitsot and the other a non-nitsot and it crashes because of the *if* condition that will not correctly detect whether an output is a nitsot or not.

**Comment by abergeron** [comment]
Can we ask Junyoung to try his code with this fix to make sure it is the same problem?

**Comment by carriepl** [comment]
I had already sent him an email with you in cc.

**Comment by carriepl** [comment]
But at any rate, it does fix a crash which I could reproduce.

**Comment by abergeron** [comment]
Yeah sure we can merge this anyway,  I just want to make sure that Junyoung's problem is not something else.

**Pull request merged**
