### PR TITLE
Downsample factor max.r op

### PR DESCRIPTION
**Pull request by nouiz**
This is a rebase/update to the current interface of work done by Razvan P. The rebase was started in gh-3418

@lamblin can you very how the new ops are tested? Otherwise, I think it is good.

### CODE REVIEW

**Comment by nouiz** [comment]
Before merging, we need to run the GPU tests for the new functionality.

**Comment by lamblin** [comment]
This looks reasonable. The tests are OK, although the test for L_Op is missing, and it could probably be refactored into a test_rop_lop_tensor4 or something like that.

**Comment by lamblin** [comment]
Are there tests for the new GPU Op, or should they be written?

**Comment by nouiz** [comment]
closing as continued in gh-4412

**Pull request closed without merging**
