### PR TITLE
Fix one step scan use wrong seq slice bug

### LINKED ISSUE #6596: Incorrect seq slice in scan with one step.
When using scan function, if a seq use multiple taps with all tap above 0, and n_steps equals 1 which will cause Theano to use recurrent function directly instead of using scan loop, the recurrent function will receive wrong seq slice.
Test code of one step:
```python
def test_mintap_onestep():
    seq = theano.tensor.ivector("seq")
    seq_info = dict(input=seq, taps=[2])

    def accum(seq_t, prev_sum):
        new_sum = prev_sum + seq_t
        return new_sum

    rs, updates = theano.scan(fn=accum,
                              sequences=seq_info,
                              outputs_info=0,
                              n_steps=1)

    f = theano.function(inputs=[seq],
                        outputs=rs)
    _seq = np.arange(20).astype("int32")
    _sum = f(_seq)
    print("sum %f" % _sum)
    assert _sum == 2
```
Will print:
>  sum 0.000000

and raise a AssertError.

Test code of two step:
```python
def test_mintap_twostep():
    seq = theano.tensor.fvector("seq")
    seq_info = dict(input=seq, taps=[2])

    def accum(seq_t, prev_sum):
        new_sum = prev_sum + seq_t
        return new_sum

    rs, updates = theano.scan(fn=accum,
                              sequences=seq_info,
                              outputs_info=np.float32(0),
                              n_steps=2)

    f = theano.function(inputs=[seq],
                        outputs=rs)
    _seq = np.arange(20).astype("float32")
    _sum = f(_seq)
    _sum = _sum[0]
    print("sum %f" % _sum)
    assert _sum == 2
```
That's will be ok.

### PR DESCRIPTION
**Pull request by Glexin**
Fix #6596

### CODE REVIEW

**Comment by lamblin** [comment]
Jenkins test this please.

**Comment by lamblin** [comment]
I think it needs to be rebased because some commits are clashing with your last PR, that just got merged.
Can you rebase or squash your commits together?

**Comment by Glexin** [comment]
OK, I'm a newbie to github and not quite clear about meaning of rebase or squash.
If I rebase this commit to previous commit or squash these two commits, should I create a new PR again.
What about the “resolve conflict“ button, may I use that.

**Comment by nouiz** [comment]
You do not need to create a new PR. You can force push to this PR after a local rebase/squase.

I never used the button. You can try it.

**Comment by lamblin** [comment]
Thanks!

**Pull request merged**
