### PR TITLE
Remove empty string in the include and lib dir.

### PR DESCRIPTION
**Pull request by nouiz**
retry of gh-4084

### CODE REVIEW

**Comment by nouiz** [comment]
@matt-graham Can you test this PR to confirm that it still fix your problem? I tried to fix the problem the original PR introduced.

thanks

**Comment by matt-graham** [comment]
@nouiz This seems to leave everything still working on my test system. Thanks

**Comment by eyaler** [comment]
this solved my problem

**Comment by abergeron** [comment]
Ok when travis passes

**Comment by nouiz** [comment]
Ideally, we should wait for @jonathanstrong or @shirtzet  to confirm that this also fix the other problem.

My review didn't worked as I expected, so I would merge when travis pass. So at least, we would have a partial fix. As now, there is no revert merged.

**Comment by eyaler** [comment]
btw, i testing by pulling bleeding edge then applying only the changes made in this PR.

**Comment by shirtzet** [comment]
Works for me ;)

**Comment by nouiz** [comment]
travis pass, so I merge. Thanks all.

**Comment by jonathanstrong** [comment]
this commit stops the warning I was receiving, but theano does not work if I don't have the lib64 dir in my LD_LIBRARY_PATH env

```
$ LD_LIBRARY_PATH=/usr/local/cuda/lib64 python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano
Using gpu device 0: GeForce GTX TITAN X (CNMeM is enabled with initial size: 10000 MB, CuDNN 4007)
>>> 
```
without ld_library_path

```
$ LD_LIBRARY_PATH='' python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano
ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: libcublas.so.7.5: cannot open shared object file: No such file or directory
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: cuda unavailable)
```
using 
```
>>> theano.__version__
'0.8.0.dev0.dev-58135c60c37a608f574e078e6cea49a2a6cda7f2'
```
here is to verify I'm using correct commit: 

```
$ git log --pretty=format:'%h' -n 1
58135c6
$ git branch
  master
* matt-graham-cudnn_paths_fix
```

**Comment by abergeron** [comment]
Do you have either nvcc in your path or CUDA_ROOT set to /usr/local/cuda?  Alternatively you can try to set the Theano flag cuda.root to /usr/local/cuda

**Comment by jonathanstrong** [comment]
yes - see https://github.com/Theano/Theano/issues/4103 - I have CUDA_HOME in .bashrc and theano.config.cuda.root set in .theanorc.

**Comment by nouiz** [comment]
Which of do you use and which version of cuda do you use?
Le 23 févr. 2016 16:46, "Jonathan Strong" <notifications@github.com> a
écrit :

**Comment by jonathanstrong** [comment]
I have cuda 7.5.18 and cudnn v4 installed

My .bashrc has these lines

```
export PATH="$PATH:/usr/local/cuda/bin"
export CUDA_HOME=/usr/local/cuda
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64"
```

my .theanorc has these lines

```
[cuda]
root = /usr/local/cuda
```

**Comment by lamblin** [comment]
Can you use `CUDA_ROOT`, and not `CUDA_HOME`?

**Pull request merged**
