### PR TITLE
Add elemwise `conj` to `sparse`.

### PR DESCRIPTION
**Pull request by Krastanov**
fix https://github.com/Theano/Theano/issues/3123

### CODE REVIEW

**Comment by nouiz** [comment]
This need tests. Check in the file sparse/tests/test_basic.py, you can use the SqrTester examples.

thanks

**Comment by nouiz** [comment]
travis tests fail:
```
======================================================================

ERROR: test_grad (theano.sparse.tests.test_basic.ConjTester)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/miniconda/envs/pyenv/lib/python2.6/site-packages/theano/sparse/tests/test_basic.py", line 2672, in test_grad

    structured=True)

  File "/home/travis/miniconda/envs/pyenv/lib/python2.6/site-packages/theano/sparse/basic.py", line 209, in verify_grad_sparse

    return utt.verify_grad(conv_op, dpt, *args, **kwargs)

  File "/home/travis/miniconda/envs/pyenv/lib/python2.6/site-packages/theano/tests/unittest_tools.py", line 91, in verify_grad

    T.verify_grad(op, pt, n_tests, rng, *args, **kwargs)

  File "/home/travis/miniconda/envs/pyenv/lib/python2.6/site-packages/theano/gradient.py", line 1656, in verify_grad

    disconnected_inputs='ignore')

  File "/home/travis/miniconda/envs/pyenv/lib/python2.6/site-packages/theano/gradient.py", line 547, in grad

    grad_dict, wrt, cost_name)

  File "/home/travis/miniconda/envs/pyenv/lib/python2.6/site-packages/theano/gradient.py", line 1288, in _populate_grad_dict

    rval = [access_grad_cache(elem) for elem in wrt]

  File "/home/travis/miniconda/envs/pyenv/lib/python2.6/site-packages/theano/gradient.py", line 1246, in access_grad_cache

    term = access_term_cache(node)[idx]

  File "/home/travis/miniconda/envs/pyenv/lib/python2.6/site-packages/theano/gradient.py", line 953, in access_term_cache

    output_grads = [access_grad_cache(var) for var in node.outputs]

  File "/home/travis/miniconda/envs/pyenv/lib/python2.6/site-packages/theano/gradient.py", line 1246, in access_grad_cache

    term = access_term_cache(node)[idx]

  File "/home/travis/miniconda/envs/pyenv/lib/python2.6/site-packages/theano/gradient.py", line 953, in access_term_cache

    output_grads = [access_grad_cache(var) for var in node.outputs]

  File "/home/travis/miniconda/envs/pyenv/lib/python2.6/site-packages/theano/gradient.py", line 1246, in access_grad_cache

    term = access_term_cache(node)[idx]

  File "/home/travis/miniconda/envs/pyenv/lib/python2.6/site-packages/theano/gradient.py", line 1093, in access_term_cache

    input_grads = node.op.grad(inputs, new_output_grads)

  File "/home/travis/miniconda/envs/pyenv/lib/python2.6/site-packages/theano/tensor/elemwise.py", line 672, in grad

    rval = self._bgrad(inputs, ograds)

  File "/home/travis/miniconda/envs/pyenv/lib/python2.6/site-packages/theano/tensor/elemwise.py", line 747, in _bgrad

    scalar_igrads = self.scalar_op.grad(scalar_inputs, scalar_ograds)

  File "/home/travis/miniconda/envs/pyenv/lib/python2.6/site-packages/theano/scalar/basic.py", line 891, in grad

    self.__class__.__name__)

MethodNotDefined: ('grad', <class 'theano.scalar.basic.Conj'>, 'Conj')

----------------------------------------------------------------------

Ran 628 tests in 1570.676s
```

Can you look at it? Mostly, the op try to test the grad, but it isn,t implemented. 2 ways to fix it: implement the grad in theano/scalar.py, in the class Conj, or just don't test the grad as it isn't implemented.

**Comment by Krastanov** [comment]
Yeah, I was just looking at this. I do not know enough of theano to implement the grad (and do not need it for what I am doing) so I would prefer to just not test it. However I do not understand the tester system very well. Is any of the other functions being tested skipping the grad as well, so I can copy from there?

**Comment by Krastanov** [comment]
Stupid question, I see there is a test_grad flag. I will add it.

**Comment by Krastanov** [comment]
All tests have passed. Hopefully it can be merged.

Also, thanks for the hand holding! Theano has a pretty intimidating codebase.

**Comment by nouiz** [comment]
Thanks for the PR. No worry, it is normal to have questions for anybody that is new to extend Theano. We help as we can.

**Pull request merged**
