### PR TITLE
Mixed: warning, error msg, tests fix, clean up, crash

### PR DESCRIPTION
**Pull request by nouiz**
Also:
- Add debugprint(print_storage=False)
- make the "merge" string optimizer behave like the others.

### CODE REVIEW

**Comment by nouiz** [comment]
travis pass

**Comment by lamblin** [comment]
Otherwise, it looks OK to me.

**Comment by nouiz** [comment]
I fixed the comments.

**Comment by nouiz** [comment]
I updated the PR.

**Comment by nouiz** [comment]
@lamblin told me we can merge when travis pass.

**Pull request merged**
