### PR TITLE
[WIP, BUG, CRASH] Fix GpuAdvancedIncSubtensor1_dev20 with negative index

### PR DESCRIPTION
**Pull request by nouiz**
advance gh-3111

todo before merging:
- [x] test on windows (the err_var is static, do it need an export?)
- [x] refactoring to remove duplicate init and copy of err_var
- [x] check the results of the tests in do_nightly_build
- [ ] do the same on the new back-end.

### CODE REVIEW

**Comment by abergeron** [comment]
Looks good, can merge after travis.

**Comment by nouiz** [comment]
start travis again by closing/reopening.

**Comment by lamblin** [comment]
I'll check on Windows.

**Comment by lamblin** [comment]
Tests of `theano\sandbox\cuda\tests\test_basic_ops.py:T_subtensor` passed on windows (53 tests).

**Pull request merged**
