### PR TITLE
Faster travis

### PR DESCRIPTION
**Pull request by abergeron**
Since travis upped their job length restriction to 2h, we can merge some parts together.  This will save a tiny bit on setup time, but also possibly enable us to test a PR with a single set of jobs that run concurrently.

Here I'm adapting travis.yml by steps to check the timings.

### CODE REVIEW

**Comment by abergeron** [comment]
This PR is now ready, but we will have to wait until the tests in the docs are not broken anymore otherwise this will break travis.

**Comment by abergeron** [comment]
I think this would be useful to merge early so I could disable the tests on the documentation to keep travis passing and we can re-enable them when they have been fixed.

**Comment by nouiz** [comment]
ok.

**Comment by abergeron** [comment]
Done.

**Comment by nouiz** [comment]
travis fail.

**Comment by abergeron** [comment]
Now it should work (at least the doc builds locally)

**Comment by abergeron** [comment]
Rebased and fixed.  Merge this quick before somebody breaks the doc again.

**Comment by nouiz** [comment]
We still need to wait for travis... But I'll try to not merge until this
one get merged...

Ok to merge when travis pass.

**Comment by lamblin** [comment]
```
Warning, treated as error:

WARNING: LaTeX command 'latex' cannot be run (needed for math display), check the pngmath_latex setting
```
Not sure if we should install latex, or configure sphinx differently.

**Comment by abergeron** [comment]
I vote for adding latex, and I did this.

**Comment by nouiz** [comment]
ok to merge when travis pass.

**Comment by nouiz** [comment]
travis is failing with this: 

Warning, treated as error:

WARNING: dvipng command 'dvipng' cannot be run (needed for math display), check the pngmath_dvipng setting

**Comment by abergeron** [comment]
Added the dvipng package and rebased.

**Comment by nouiz** [comment]
travis fail:

Warning, treated as error:

/home/travis/build/Theano/Theano/doc/sandbox/ccodegen.txt:173: WARNING: Could not parse literal_block as "python". highlighting skipped.

**Comment by lamblin** [comment]
Indeed, it should be c or cpp

**Comment by abergeron** [comment]
I've made the fixes and also switched to install sphinx with conda.

**Comment by nouiz** [comment]
Only one of the doc case failed in travis:

Warning, treated as error:

/home/travis/build/Theano/Theano/theano/misc/pkl_utils.py:docstring of theano.misc.pkl_utils.CompatUnpickler:12: WARNING: Definition list ends without a blank line; unexpected unindent.

It is the one with python 3.3

**Comment by abergeron** [comment]
Apparently there were some more warnings in python3.  I fixed those and now it should pass.

**Comment by nouiz** [comment]
More doc error:

Warning, treated as error:

/home/travis/build/Theano/Theano/theano/tensor/nnet/abstract_conv.py:docstring of theano.tensor.nnet.abstract_conv.conv2d_grad_wrt_inputs:42: ERROR: Unexpected indentation.

**Comment by lamblin** [comment]
That's my fault, I should not have merged that... sorry.
Should I try to fix it by a sub-PR?

**Comment by abergeron** [comment]
I did a rebase and fixed the new doc warnings in master.  Now it should be ok.

**Pull request merged**
