### PR TITLE
jenkins pr master cache

### PR DESCRIPTION
**Pull request by slefrancois**

### CODE REVIEW

**Comment by slefrancois** [comment]
jenkins test this

**Comment by slefrancois** [comment]
jenkins test this

**Comment by slefrancois** [comment]
jenkins test this

**Comment by nouiz** [comment]
I killed travis

**Comment by slefrancois** [comment]
Successful jenkins runs [306](http://earlgrey.iro.umontreal.ca:8080/job/Theano_PR/306/) and [298](http://earlgrey.iro.umontreal.ca:8080/job/Theano_PR/298/)

**Comment by slefrancois** [comment]
jenkins test this

**Pull request merged**
