### PR TITLE
useless dimshuffle in reshape is removed

### PR DESCRIPTION
**Pull request by mohammadpz**
Regarding issue #4580 .

### CODE REVIEW

**Comment by lamblin** [comment]
The issue seems to be that Travis times out in one test: `test_grad_negative_axis (theano.tensor.tests.test_sort.test_sort)`, when run in `FAST_COMPILE`.
It could indicate an infinite loop, or that something is taking much longer than before.
Can you run that test locally with mode=FAST_COMPILE, and see how long it takes with that PR vs. the master?

**Comment by nouiz** [comment]
The problem was in the faster of Theano. It was fixed. I will close/reopen
to retrigget travis.

**Comment by lamblin** [comment]
Indeed, Travis seems to pass now. I'll have another look at the PR tomorrow.

**Comment by lamblin** [comment]
It looks correct, thanks!

**Pull request merged**
