### PR TITLE
Fix MKL linking on Windows.

### PR DESCRIPTION
**Pull request by notoraptor**
Partially solves #6365 (still need to add fallback code for [sd]gemv, and probably [sd]dot too).

@nouiz @abergeron

### CODE REVIEW

**Comment by nouiz** [comment]
jenkins test windows

**Comment by notoraptor** [comment]
Updated. There was one failure with Jenkins on Windows due to float16 support for cudnn convolution: http://earlgrey.iro.umontreal.ca:8080/job/Theano_pr_win/41/ . I cherry-picked a fix fro; #6367 .

Also, all tests for `blas_c` passed (none skipped) on Windows ! http://earlgrey.iro.umontreal.ca:8080/job/Theano_pr_win/41/testReport/theano.tensor.tests.test_blas_c/

jenkins test windows

**Comment by notoraptor** [comment]
Jenkins fails on Windows, but only with flake8 tests: http://earlgrey.iro.umontreal.ca:8080/job/Theano_pr_win/42/testReport/theano.tests/test_flake8/test_format_flake8/

Surprisingly, these flake8 errors are not reported by Jenkins on Linux.

@slefrancois  @abergeron @nouiz .

**Comment by slefrancois** [comment]
You can ignore that, since we updated the windows buildbot it doesn't load the flake8 whitelist correctly. The regular PRs check for flake8 so you passed.

**Pull request merged**
