### PR TITLE
Backport of support for pydot-ng in 0.8.x

### PR DESCRIPTION
**Pull request by lamblin**
Plus trying to fix travis.

### CODE REVIEW

**Comment by nouiz** [comment]
I already restarted the 2 travis part that fail due to no output in 10m:

https://travis-ci.org/Theano/Theano/jobs/185989444

At this point, I'm not sure if we should continue or just drop this.

**Comment by lamblin** [comment]
I'll have a look at the batchnorm tests, there's no reason they should pass on the master branch and not here.

**Comment by nouiz** [comment]
travis still fail.

**Comment by lamblin** [comment]
Finally passed!

**Pull request merged**
