### PR TITLE
[BUG] Fix invalid optimization for product of multiplication

### PR DESCRIPTION
**Pull request by carriepl**
Optimization local_sum_prod_mul_by_scalar had behavior : 
prod(scalar * smth) -> scalar * prod(smth)
prod(-smth) -> -prod(smth)

when it should have been : 
prod(scalar * smth) -> scalar ** size(smth) * prod(smth)
prod(-smth) -> (-1) ** size(smth) * prod(smth)

### CODE REVIEW

**Comment by lamblin** [comment]
Travis seems to be overwhelmed.
Can you run the relevant tests with DebugMode locally? If that works, I can merge.

**Comment by carriepl** [comment]
I ran them in DebugMode, both float32 and float64. Also, I had travis run the two jobs that it had skipped and they pass.

**Comment by carriepl** [comment]
Done

**Comment by nouiz** [comment]
we can merge when travis pass. It will be long, it is overloaded.

**Pull request merged**
