### PR TITLE
[FIX] Add define for PyInt_FromSize_t for Python3.

### LINKED ISSUE #2387: identifier "PyInt_FromLong" is undefined
OS: Ubuntu 14.04
Theano: 5ec4c302
Python: 3.4.0

The error occurs when running `theano.test()`:

    mod.cu (57): error: identifier "PyInt_FromLong" is undefined

It may be necessary to change from `PyInt_FromLong` to `PyLong_FromLong` according to [this post](http://python3porting.com/cextensions.html).

### PR DESCRIPTION
**Pull request by HapeMask**
Fixes #2387.

### CODE REVIEW

**Comment by abergeron** [comment]
This looks good.  @ziyuang can you confirm this fixes the problem for python 3?

**Comment by ziyuang** [comment]
Looks like I cannot pull this due to the check fails.

**Comment by nouiz** [comment]
@ziyuang, what do you mean? Which check fail?

**Comment by ziyuang** [comment]
> @ziyuang, what do you mean? Which check fail?

I saw some Travis checking fails but now they are gone. I will confirm PR later.

**Comment by ziyuang** [comment]
Yes this fixes the compilation error when importing theano in Python 3.

**Comment by nouiz** [comment]
thanks.

**Comment by ziyuang** [comment]
Nonono sorry, this did not fix.

**Comment by ziyuang** [comment]
OK, there was some confusion but yes this fixed the compilation error in Python 3.

**Pull request merged**
