### PR TITLE
Include pep8 autocheck test + while list (from blocks) #2503

### PR DESCRIPTION
**Pull request by Saizheng**
This file only considers flake8 check for theano.

### CODE REVIEW

**Comment by Saizheng** [comment]
This is for Issue 2503 https://github.com/Theano/Theano/issues/2503

**Comment by lamblin** [comment]
It looks like you also have to add the following files to the whitelist:
- `generated_version.py`
- `sandbox/cuda/opt_util.py`

Also, `gof/tests/test_utils.py` seems to violate flake8 only in python 3, so I think it may be due to 2to3, and nothing we can fix.
Should we disable the flake8 tests in python 3?

**Comment by nouiz** [comment]
I would keep it in python 3 for now. I suppose newer flake8 will fix it.
For now, I'll would just keep that file in the whitelist.

**Comment by nouiz** [comment]
thanks.

**Pull request merged**
