### PR TITLE
Fix blas C code having wrong alpha and beta for float16.

### PR DESCRIPTION
**Pull request by abergeron**

### CODE REVIEW

**Comment by nouiz** [comment]
I would like that we add a test for the case this fix.

**Comment by nouiz** [comment]
otherwise, I think it is good.

**Comment by nouiz** [comment]
merging now as this fix a bug, but I still would like to see a test for this.

**Comment by mharradon** [comment]
This now warns as creating float64 with warn_float64 = 'warn' - I was under the impression that this was detrimental to performance. Is this not the case? Perhaps this should be "excepted" from warn_float64 if not?

**Comment by nouiz** [comment]
Agreed. We should make this not warm with these flag.

Le 18 oct. 2016 18:05, "Michael Harradon" <notifications@github.com> a
écrit :

**Pull request merged**
