### PR TITLE
jenkins buildbot with docker

### PR DESCRIPTION
**Pull request by slefrancois**

### CODE REVIEW

**Comment by slefrancois** [comment]
waiting for buildbot tests to complete

**Comment by slefrancois** [comment]
[Two extra errors on 32 bit buildbot](http://earlgrey.iro.umontreal.ca:8080/job/Theano_buildbot_python2_32bit/200/testReport/):

- graphviz problem is now solved.
- missing performs unknown, I didn't change the test parameters.

**Comment by nouiz** [comment]
IRL discussion: probably g++ isn't installed

**Comment by slefrancois** [comment]
g++ 32 bit was missing from docker, solved.

Ready to merge.

**Comment by nouiz** [comment]
I forgot, what this PR is for already? What it try to change?

**Comment by slefrancois** [comment]
It makes the 32 bit buildbot script compatible with the new docker workers in jenkins.

**Pull request merged**
