### PR TITLE
refactored GpuJoin c_code to not hit nested block limit of MSVC

### PR DESCRIPTION
**Pull request by NasenSpray**
MSVC doesn't like functions with too many gotos

Possible discussion topic: C++11 usage

### CODE REVIEW

**Comment by nouiz** [comment]
@lamblin @abergeron what about requesting C++11?

Do you use other C++11 code then the auto keywork? In fact, auto seem to be in C++0x and was in gcc 4.4: https://gcc.gnu.org/gcc-4.4/cxx0x_status.html

I still have a computer with GCC 4.5. I'll try it there.

**Comment by NasenSpray** [comment]
> Do you use other C++11 code then the auto keywork?

`std::copy_n` and range-based for loops. Another in future potentially very useful C++11 features would be variadic templates.

> In fact, auto seem to be in C++0x

sure, C++0x _is_ C++11 after all

**Comment by nouiz** [comment]
It don't compile with g++ 4.8 and cuda 7.5. If I use this diff, it compile with less error:

```
diff --git a/theano/sandbox/cuda/basic_ops.py b/theano/sandbox/cuda/basic_ops.py
index 084d4fc..f593174 100644
--- a/theano/sandbox/cuda/basic_ops.py
+++ b/theano/sandbox/cuda/basic_ops.py
@@ -3642,6 +3642,11 @@ class GpuJoin(tensor.Join, GpuOp):
     def c_code_cache_version(self):
         return (7,)
 
+    def c_compile_args(self):
+        return ["-std=c++11"]
+
 gpu_join = GpuJoin()
 
 
diff --git a/theano/sandbox/cuda/nvcc_compiler.py b/theano/sandbox/cuda/nvcc_compiler.py
index 2b60a8d..18112b9 100644
--- a/theano/sandbox/cuda/nvcc_compiler.py
+++ b/theano/sandbox/cuda/nvcc_compiler.py
@@ -271,7 +271,7 @@ class NVCC_compiler(Compiler):
                             '--prec-div', '--prec-sqrt',  '--use_fast_math',
                             '-fmad', '-ftz', '-maxrregcount',
                             '-prec-div', '-prec-sqrt', '-use_fast_math',
-                            '--use-local-env', '--cl-version=']:
+                            '--use-local-env', '--cl-version=', '-std=']:
 
                 if pa.startswith(pattern):
                     preargs1.append(pa)
```

Error with this diff:

```
mod.cu(196): error: transfer of control bypasses initialization of:
            variable "inputs"
```

Mostly, you should define inputs before the error checking. Did it compile and work for you? I suppose so. Can you add this diff this your PR?

It don't work with g++ 4.5. It don't like the n_copy and auto. So I'm not reading correctly g++ doc about when auto was added.

**Comment by NasenSpray** [comment]
> It don't work with g++ 4.5. It don't like the n_copy and auto. So I'm not reading correctly g++ doc about when auto was added.

GCC was C++11-complete at 4.8.x

**Comment by abergeron** [comment]
I think that requiring GCC 4.8 is a bit too recent for now.

Also, this problem seems to be only in the old gpu backend which is scheduled to go away.

**Comment by NasenSpray** [comment]
> I think that requiring GCC 4.8 is a bit too recent for now.

GCC 4.8.1 was released on May 31, 2013. Is that really too recent?

> Also, this problem seems to be only in the old gpu backend which is scheduled to go away.

Would it be possible to add this fix to a "for MSVC only" branch? The problem affects every Theano/Keras user on Windows and makes it almost impossible to use RNNs there.

**Comment by nouiz** [comment]
We had a quick discussion and we are pretty sure that in some cluster, this
will cause problem. Also, it will probably raise the minimum CUDA version
as it request specific g++ version.

We don't like having a branch of the code that won't be tested on linux as
we don't have buildbot on windows. It will be brittle and have more risk of
betting bugged/broken by mistake. Could you change the code to not use
C++11?

**Comment by lamblin** [comment]
Ubuntu 12.04, still supported, has GCC 4.6 only, for instance, and Anaconda provides only MinGW 4.7 for Windows.
Is that new feature actually required for the fix, though? Can we fix the issue without using `copy_n` or `for (auto it : inputs)`?

**Comment by NasenSpray** [comment]
> Ubuntu 12.04, still supported, has GCC 4.6 only, for instance, and Anaconda provides only MinGW 4.7 for Windows.

Okay, makes sense then.

> Is that new feature actually required for the fix, though? Can we fix the issue without using copy_n or for (auto it : inputs)?

Not really, it's just syntax sugar. I can make a new PR w/o C++11.

**Comment by lamblin** [comment]
@NasenSpray If you can make a new PR without C++11, that would be really great.
Thanks for your help!

**Comment by nouiz** [comment]
I'll make a Theano 0.8.2 release next week. It would be great if we include this fix. Do you have the time to finish it? I'm pretty busy and won,t have the time to finish this.

thanks

**Comment by NasenSpray** [comment]
Sorry, I almost forgot this. What's the deadline? I should have some time to work on it tomorrow.

**Comment by nouiz** [comment]
I don't know when it will be done. It could be today, tomorrow or Wednesday.

thanks

**Comment by nouiz** [comment]
I stumbled on this PR again. Do you have time to finish it?

**Comment by nouiz** [comment]
Note, https://github.com/fchollet/keras/issues/3550 found another work around, using tile instead of concatenate when you concatenate the same tensor many times. That should be faster too.

**Comment by nouiz** [comment]
The new back-end don't have this problem. So closing as we will get rid of the old back-end shortly.

**Pull request closed without merging**
