### PR TITLE
Test abstract conv

### PR DESCRIPTION
**Pull request by teganmaharaj**
I get the following missing input errors, but @lamblin the code worked for you?

======================================================================                                                                                                                                                                                    
ERROR: Compares calculated abstract grads wrt inputs with the fwd grads                                                                                                                                                                                   
----------------------------------------------------------------------                                                                                                                                                                                    
Traceback (most recent call last):                                                                                                                                                                                                                        
  File "/u/maharajt/Theano/theano/tensor/nnet/tests/test_abstract_conv.py", line 1152, in test_conv2d_grad_wrt_inputs                                                                                                                                     
    f_old = theano.function([self.w, self.output_grad], conv_grad)                                                                                                                                                                                        
  File "/u/maharajt/Theano/theano/compile/function.py", line 326, in function                                                                                                                                                                             
    output_keys=output_keys)                                                                                                                                                                                                                              
  File "/u/maharajt/Theano/theano/compile/pfunc.py", line 486, in pfunc                                                                                                                                                                                   
    output_keys=output_keys)                                                                                                                                                                                                                              
  File "/u/maharajt/Theano/theano/compile/function_module.py", line 1783, in orig_function                                                                                                                                                                
    output_keys=output_keys).create(                                                                                                                                                                                                                      
  File "/u/maharajt/Theano/theano/compile/function_module.py", line 1437, in __init__                                                                                                                                                                     
    accept_inplace)                                                                                                                                                                                                                                       
  File "/u/maharajt/Theano/theano/compile/function_module.py", line 176, in std_fgraph                                                                                                                                                                    
    update_mapping=update_mapping)                                                                                                                                                                                                                        
  File "/u/maharajt/Theano/theano/gof/fg.py", line 180, in __init__                                                                                                                                                                                       
    self.__import_r__(output, reason="init")                                                                                                                                                                                                              
  File "/u/maharajt/Theano/theano/gof/fg.py", line 351, in __import_r__                                                                                                                                                                                   
    self.__import__(variable.owner, reason=reason)                                                                                                                                                                                                        
  File "/u/maharajt/Theano/theano/gof/fg.py", line 396, in __import__                                                                                                                                                                                     
    variable=r)                                                                                                                                                                                                                                           
MissingInputError: An input of the graph, used to compute Shape(x), was not provided and not given a value.Use the Theano flag exception_verbosity='high',for more information on this error.                                                             

Backtrace when the variable is created:
  File "/Tmp/lisa/os_v5/anaconda/lib/python2.7/site-packages/nose/suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "/Tmp/lisa/os_v5/anaconda/lib/python2.7/site-packages/nose/suite.py", line 224, in run
    test(orig)
  File "/Tmp/lisa/os_v5/anaconda/lib/python2.7/site-packages/nose/case.py", line 45, in __call__
    return self.run(*arg, **kwarg)
  File "/Tmp/lisa/os_v5/anaconda/lib/python2.7/site-packages/nose/case.py", line 133, in run
    self.runTest(result)
  File "/Tmp/lisa/os_v5/anaconda/lib/python2.7/site-packages/nose/case.py", line 151, in runTest
    test(result)
  File "/Tmp/lisa/os_v5/anaconda/lib/python2.7/unittest/case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "/Tmp/lisa/os_v5/anaconda/lib/python2.7/unittest/case.py", line 320, in run
    self.setUp()
  File "/u/maharajt/Theano/theano/tensor/nnet/tests/test_abstract_conv.py", line 1123, in setUp
    self.x = theano.tensor.tensor4('x', theano.config.floatX)  # inputs


======================================================================
ERROR: Compares calculated abstract grads wrt weights with the fwd grads
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/u/maharajt/Theano/theano/tensor/nnet/tests/test_abstract_conv.py", line 1192, in test_conv2d_grad_wrt_weights
    f_old = theano.function([self.x, self.output_grad], conv_grad)
  File "/u/maharajt/Theano/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/u/maharajt/Theano/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/u/maharajt/Theano/theano/compile/function_module.py", line 1783, in orig_function
    output_keys=output_keys).create(
  File "/u/maharajt/Theano/theano/compile/function_module.py", line 1437, in __init__
    accept_inplace)
  File "/u/maharajt/Theano/theano/compile/function_module.py", line 176, in std_fgraph
    update_mapping=update_mapping)
  File "/u/maharajt/Theano/theano/gof/fg.py", line 180, in __init__
    self.__import_r__(output, reason="init")
  File "/u/maharajt/Theano/theano/gof/fg.py", line 351, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "/u/maharajt/Theano/theano/gof/fg.py", line 396, in __import__
    variable=r)
MissingInputError: An input of the graph, used to compute Shape(w), was not provided and not given a value.Use the Theano flag exception_verbosity='high',for more information on this error.

Backtrace when the variable is created:
  File "/Tmp/lisa/os_v5/anaconda/lib/python2.7/site-packages/nose/suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "/Tmp/lisa/os_v5/anaconda/lib/python2.7/site-packages/nose/suite.py", line 224, in run
    test(orig)
  File "/Tmp/lisa/os_v5/anaconda/lib/python2.7/site-packages/nose/case.py", line 45, in __call__
    return self.run(*arg, **kwarg)
  File "/Tmp/lisa/os_v5/anaconda/lib/python2.7/site-packages/nose/case.py", line 133, in run
    self.runTest(result)
  File "/Tmp/lisa/os_v5/anaconda/lib/python2.7/site-packages/nose/case.py", line 151, in runTest
    test(result)
  File "/Tmp/lisa/os_v5/anaconda/lib/python2.7/unittest/case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "/Tmp/lisa/os_v5/anaconda/lib/python2.7/unittest/case.py", line 320, in run
    self.setUp()
  File "/u/maharajt/Theano/theano/tensor/nnet/tests/test_abstract_conv.py", line 1124, in setUp
    self.w = theano.tensor.tensor4('w', theano.config.floatX)  # filter weights


----------------------------------------------------------------------
Ran 1033 tests in 335.688s

### CODE REVIEW

**Comment by lamblin** [comment]
There is a conflict to resolve, due to another test class having been added at the end of the same file. It should be easy to fix with a rebase. After the rebase, do not merge with the branch on GitHub, just `git push -f ...`.

Removing `x` from the inputs of `f_old` had worked for me with `nnet.conv.conv2d(...)`, but I had forgotten that `nnet.conv2d` actually needs `x` for its gradient (to know its shape). So you would need to add it back for `f_old`, sorry about that.
With those changes, the tests do pass.

**Comment by teganmaharaj** [comment]
I rebased and gave the x / w back to f_old and the tests pass :). Should be
good to go!

**Comment by lamblin** [comment]
Jenkins test this please

**Comment by lamblin** [comment]
Jenkins test this please

**Comment by lamblin** [comment]
Jenkins test this

**Comment by lamblin** [comment]
Jenkins test this

**Comment by nouiz** [comment]
jenkins passed.

**Pull request merged**
