### PR TITLE
Grad for round

### PR DESCRIPTION
**Pull request by ChienliMa**
An old issue: #1460
Do we need test cases here?

### CODE REVIEW

**Comment by abergeron** [comment]
I'm not sure those definitions of the gradient are actually sound.

Also, you would need to add tests.

**Comment by nouiz** [comment]
The old issue about grad are tricky most of the time. This is probably why
they haven't been fixed.

So to prevent useless work, I think it would be better to discuss the fix
first, to be sure it is good. But this need time to investigate all the
possible condition and the consequence of the change. So it is better that
this is time when we have enough time for this.

I'm away for a week and we have a deadline Feb 6th. So if you want to work
on that, I think a better timming would be after our deadline.

p.s. I didn't check the code. If someone else have time for this now, just
tell me.

**Comment by ChienliMa** [comment]
I just  simply feel that these two ops like ceiling and floor so I copied that their grads here, without carrying mathematical prove.  If proven is needed, maybe I should leave this for a while.

**Comment by abergeron** [comment]
We don't need a mathematical proof per se (although it could help), but we need some testing code to make sure that it's partially ok and that it won't break in the future.

**Comment by lamblin** [comment]
The mathematical definition of the gradient is correct, it should be zero almost everywhere, and we generalize it to zero.
Regarding the dtype, since `round_half_to_even` and `round_half_away_from_zero` are defined with `same_out_float_only`, I would say that the special case for discrete dtypes is not necessary, but I guess it does not hurt to have it here in case we support that in the future.
Regarding tests, I think a simple test where we take the gradient through a rounding operation would be enough.

**Comment by nouiz** [comment]
There have been now commit. This to not generate new notification. Can you add a new comment when it need a new review? This way we get notification/email about it. @lamblin told me he will check it again.

The new comment prevent extra delay like it happened here:)

**Comment by lamblin** [comment]
This is the only question I have, otherwise, I'm OK to merge.

**Comment by ChienliMa** [comment]
In fact, I didn't remember why I make this change.
So I resumed these codes to ```numpy.round``` and tests passed.

**Comment by lamblin** [comment]
Thanks!

**Pull request merged**
