### PR TITLE
Fix infer_shape user warning for not implemented case

### PR DESCRIPTION
**Pull request by nouiz**

### CODE REVIEW

**Comment by abergeron** [comment]
Please instead of fiddling with warnings could we just implement those cases.  The shapes we want are inputs 3 and 4 in both cases.

**Comment by nouiz** [comment]
I updated the PR with the implementation. @daemonmaker can you tell us what you think?

**Comment by abergeron** [comment]
Apparently this is mostly "my" code so we need somebody else to review this.

**Comment by nouiz** [comment]
As we both agree on the code, can you just run the tests? If they pass, we can merge.

**Comment by abergeron** [comment]
The tests passed.

**Pull request merged**
