### PR TITLE
fix compilation with cygwin

### PR DESCRIPTION
**Pull request by nouiz**
I didn't test it myself, it was reported on the mailing list. I'm guessing that maybe this would work.

### CODE REVIEW

**Comment by nouiz** [comment]
Just to know, you just reviewed and didn't tested?

**Comment by abergeron** [comment]
Yes, since I don't have a windows environment ready.  But I was pretty sure python used .pyd on cygwin (as it normally does on windows).

Apparently through some hocus-pocus, using cygwin disables .pyd loading leaving .dll as the only possibility for compiled extensions, which is supposed to only be a fallback.  So yes, this would be wrong apparently.

**Comment by nouiz** [comment]
So the fix is to use .dll for the extension for cygwin for all compilation?
Or only for library we link again like cuda_ndarray?

**Comment by abergeron** [comment]
Apparently we should use .dll on cygwin for everything.

**Pull request merged**
