### PR TITLE
[WIP] Do not run cudnn available on the default GPU.

### PR DESCRIPTION
**Pull request by nouiz**
see: [theano-users] cudnn R2 throws a nondescript error

I wait for confirmation that this do the good fix.

### CODE REVIEW

**Comment by lamblin** [comment]
Looks reasonable to me.

**Comment by benanne** [comment]
awesome :) if I have some time tomorrow I'll try this out!

**Comment by benanne** [comment]
Sorry for the delay, I just had a chance to test this. It seems to work as advertised (I no longer get "cudnn not available" with exclusive process mode).

**Comment by nouiz** [comment]
thanks. As you confirm it work for you, I merge as @lamblin was ok with this.

**Comment by benanne** [comment]
Sweet! Thanks a lot for this :)

**Pull request merged**
