### PR TITLE
as per #5409,  fixing a typo

### LINKED ISSUE #5409: A typo that prevents T.grad on gpuarray.pool
See this line:
https://github.com/Theano/Theano/blob/a7900bd8ddbfceda9249f235e21005e0ee970884/theano/gpuarray/pool.py#L100

I think it should be
```
out = self(img, ws, stride, pad)
```
rather than 
```
out = self(inp, ws, stride, pad)
```
Otherwise, I'm getting the error below.

```
Traceback (most recent call last):
  File "alex_net.py", line 490, in <module>
    model = AlexNet(config)
  File "alex_net.py", line 103, in __init__
    self.grads = T.grad(self.cost,self.params)
  File "/export/mlrg/hma02/.local/lib/python2.7/site-packages/theano/gradient.py", line 553, in grad
    grad_dict, wrt, cost_name)
  File "/export/mlrg/hma02/.local/lib/python2.7/site-packages/theano/gradient.py", line 1317, in _populate_grad_dict
    rval = [access_grad_cache(elem) for elem in wrt]
  File "/export/mlrg/hma02/.local/lib/python2.7/site-packages/theano/gradient.py", line 1272, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/export/mlrg/hma02/.local/lib/python2.7/site-packages/theano/gradient.py", line 965, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/export/mlrg/hma02/.local/lib/python2.7/site-packages/theano/gradient.py", line 1272, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/export/mlrg/hma02/.local/lib/python2.7/site-packages/theano/gradient.py", line 965, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]

......


  File "/export/mlrg/hma02/.local/lib/python2.7/site-packages/theano/gradient.py", line 1272, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/export/mlrg/hma02/.local/lib/python2.7/site-packages/theano/gradient.py", line 1106, in access_term_cache
    new_output_grads)
  File "/export/mlrg/hma02/.local/lib/python2.7/site-packages/theano/gradient.py", line 1106, in access_term_cache
    new_output_grads)
  File "/export/mlrg/hma02/.local/lib/python2.7/site-packages/theano/gof/op.py", line 700, in L_op
    return self.grad(inputs, output_grads)
  File "/export/mlrg/hma02/.local/lib/python2.7/site-packages/theano/gpuarray/pool.py", line 100, in grad
    out = self(inp, ws, stride, pad)
  File "/export/mlrg/hma02/.local/lib/python2.7/site-packages/theano/gof/op.py", line 604, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/export/mlrg/hma02/.local/lib/python2.7/site-packages/theano/gpuarray/pool.py", line 44, in make_node
    ctx_name = infer_context_name(inp)
  File "/export/mlrg/hma02/.local/lib/python2.7/site-packages/theano/gpuarray/basic_ops.py", line 108, in infer_context_name
    if isinstance(v.type, GpuArrayType):
AttributeError: 'list' object has no attribute 'type'
```

### PR DESCRIPTION
**Pull request by hma02**
fix #5409, This is for fixing a typo that prevents T.grad on gpuarray.pool

### CODE REVIEW

**Comment by nouiz** [comment]
jenkins test this

**Comment by nouiz** [comment]
You don't need to call GpuPool manually anymore. The CPU interface cover all the options the GPU support. This is why this error wasn't found before. Call theano.tensor.signal.pool.pool_2d() in your graph. Theano optimization will move that to the GPU itself.

It would still be great to merge this PR.

**Comment by hma02** [comment]
@nouiz I see. Thank you. 
Yes I was calling the Op,  GpuPool, directly for making a maxpooling node. I wonder if Calling theano.tensor.signal.pool.pool_2d() will give speed improvement or introduce any overhead with different Theano optimization options, like fast_run, fast_math, etc..

**Comment by nouiz** [comment]
I should probably make no big difference. Maybe small slowdown or even
speed up could be given by this change. But I think it is mostly noise.

**Pull request merged**
