### PR TITLE
Fix pep8

### PR DESCRIPTION
**Pull request by lamblin**
Follow-up on #5693

### CODE REVIEW

**Comment by nouiz** [comment]
It contains the commits from the other PR that was merged. You probably want only the 2 last commits in this PR.

**Comment by abergeron** [comment]
Once again `MockRandomState` is present but unused.  Otherwise I'm ok with the rest of this.

**Comment by nouiz** [comment]
This PR need a rebase.

**Comment by lamblin** [comment]
I'll rebase and address some comments.

**Comment by lamblin** [comment]
Rebased, and added some comments for `MockRandomState`.

**Comment by lamblin** [comment]
Re-updated.

**Pull request merged**
