### PR TITLE
Flake8 tensor

### PR DESCRIPTION
**Pull request by harlouci**

### CODE REVIEW

**Comment by nouiz** [comment]
quick code review seem to tell it is ok.

**Comment by nouiz** [comment]
travis is failing

**Comment by carriepl** [comment]
This PR will need a rebase.

**Comment by carriepl** [comment]
You still have a few flake8 errors that cause Travis to fail

**Comment by harlouci** [comment]
One more flake8 error corrected

**Comment by nouiz** [comment]
this PR need a rebase

**Comment by harlouci** [comment]
J'ai un PB, j'ai rebasé flake8_v3 et je n'arrive plus à pousser :

*git push origin flake8_v3*
To git@github.com:harlouci/Theano.git
 ! [rejected]        flake8_v3 -> flake8_v3 (non-fast-forward)
error: failed to push some refs to 'git@github.com:harlouci/Theano.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Merge the remote changes (e.g. 'git pull')
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

*Voici mon arbre local.* Curisieusement., il y manque le commit 6a593c4
<https://github.com/harlouci/Theano/commit/6a593c451981ea43c29261333a4c7c7e8f7e8f1e>
flake8 for theano/tensor/var.py; one blank line removed
<https://github.com/harlouci/Theano/commit/6a593c451981ea43c29261333a4c7c7e8f7e8f1e>
de origine/flake8_v3 (!!!???) :

[harlouci@eos3 Theano]$* git log --graph --oneline --decorate --all*
* da0ed7f (HEAD, flake8_v3) One flake8 error corrected in
theano/tensor/blas.py
* a95168e Deplaced test_matrix_inverse_solve from nlinalg.py to
test_linalg.py
* 56661d4 A #noqa added to theano/tensor/type.py
* d13d751 Put back import nlinalg in tensor/extra_ops.py
* 03dd907 Corrected a couple of flake8 errors in tensor/blas.py
* 35753cb flake8 for tensor/blas_scipy.py
* 8607880 flake8 elemwise_cgen.py
* fe2627d flake8 for tensor/blas_c.py
* c844015 flake8 for nlinalg, four E left
* fb73c20 flake8 for tensor/extra_ops.py
* bac96e8 flake8 for tensor/blas.py; two E left
* 804be89 flake8 for tensor/opt_uncanonicalize.py
* a421817 flake8 for tensor/fourier.py
* 2855a75 flake8 for tensor/type.py ; one E left
* 962a811 flake8 for tensor/blas_headers.py
| * e1aace6 (props_nlinalg) __props__ added to theano/tensor/nlinalg.py
|/
*   fe66544 (central/master, master) Merge pull request #3104 from
harlouci/trunk





2015-07-15 11:29 GMT-04:00 Frédéric Bastien <notifications@github.com>:

**Comment by harlouci** [comment]
J'ai rebaptisé la branche et je l'ai renvoyé à origin. Iban

2015-07-15 12:17 GMT-04:00 Harlouchet Iban <iban.harlouchet@gmail.com>:

**Comment by nouiz** [comment]
we can merge when travis pass.

**Pull request merged**
