### PR TITLE
Change the elemwise input fusion limit to 32.

### LINKED ISSUE #2870: ValueError during graph optimization - "Cannot construct a ufunc with more than 32 operands (requested number were: inputs = 34 and outputs = 1)"
I'm trying to track down the cause of an error during graph optimization that I'm seeing with Theano 0.7.0. Here's some code that will reproduce it:

```python
import numpy as np
import theano
from theano import tensor as te
from theano.gradient import jacobian, hessian


# hidden parameters to learn
# ---------------------------------------------------------------------
P = te.dvector('P')     # packed vector of model parameters
A = P[0]
B = P[1]
C = P[2:4]
sigma_min = P[4]
sigma_ratio = P[5]
theta = P[6]
sigma_maj = sigma_ratio * sigma_min

# known parameters
# ---------------------------------------------------------------------
X = te.dmatrix('X')     # [2, m], (x, y) positions of stimulus
Z = te.dvector('Z')     # [m,], response magnitudes

# bivariate Gaussian model
# ---------------------------------------------------------------------
sin2_theta = te.sin(theta) ** 2
cos2_theta = te.cos(theta) ** 2
sin_2theta = te.sin(2 * theta)
sigma2_maj = sigma_maj ** 2
sigma2_min = sigma_min ** 2
a = (cos2_theta / 2. / sigma2_maj) + (sin2_theta / 2. / sigma2_min)
b = (-sin_2theta / 4. / sigma2_maj) + (sin_2theta / 4. / sigma2_min)
c = (sin2_theta / 2. / sigma2_maj) + (cos2_theta / 2. / sigma2_min)
M = te.stack([a, b, b, c]).reshape((2, 2))
D = (X.T - C).T
Q = (D * te.dot(M, D)).sum(0)
Z_hat = A * te.exp(-Q) + B

_fit_err = Z - Z_hat
_loss = 0.5 * te.dot(_fit_err, _fit_err)   # fast sum of squares
_jac = jacobian(_loss, P)
_hess = hessian(_loss, P)

# Theano functions
# ---------------------------------------------------------------------
forward = theano.function([P, X], Z_hat)
loss = theano.function([P, X, Z], _loss)
jacobian = theano.function([P, X, Z], _jac)
hessian = theano.function([P, X, Z], _hess) #<-error disappears if this line is commented

# sample input/output
# ---------------------------------------------------------------------
P = np.r_[1., 0., 1., 2., 1., 3., np.pi / 4.]
P0 = np.random.randn(7)
X = np.mgrid[-5:5:1000j,-5:5:1000j].reshape(2, -1)
Y = forward(P, X)
L = loss(P0, X, Y)
J = jacobian(P0, X, Y)
H = hessian(P0, X, Y)
```

If I try to run this script with the line `hessian = theano.function([P, X, Z], _hess)` uncommented, I see the following optimization error:

```python
ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x7f9e22400d90>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/alistair/.venvs/resonant_pipeline/lib/python2.7/site-packages/theano/gof/opt.py", line 195, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/alistair/.venvs/resonant_pipeline/lib/python2.7/site-packages/theano/gof/opt.py", line 81, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/alistair/.venvs/resonant_pipeline/lib/python2.7/site-packages/theano/tensor/opt.py", line 5498, in apply
    new_outputs = self.optimizer(node)
  File "/home/alistair/.venvs/resonant_pipeline/lib/python2.7/site-packages/theano/tensor/opt.py", line 5445, in local_fuse
    ret = local_fuse(n)
  File "/home/alistair/.venvs/resonant_pipeline/lib/python2.7/site-packages/theano/tensor/opt.py", line 5445, in local_fuse
    ret = local_fuse(n)
  File "/home/alistair/.venvs/resonant_pipeline/lib/python2.7/site-packages/theano/tensor/opt.py", line 5445, in local_fuse
    ret = local_fuse(n)
  File "/home/alistair/.venvs/resonant_pipeline/lib/python2.7/site-packages/theano/tensor/opt.py", line 5445, in local_fuse
    ret = local_fuse(n)
  File "/home/alistair/.venvs/resonant_pipeline/lib/python2.7/site-packages/theano/tensor/opt.py", line 5445, in local_fuse
    ret = local_fuse(n)
  File "/home/alistair/.venvs/resonant_pipeline/lib/python2.7/site-packages/theano/tensor/opt.py", line 5433, in local_fuse
    n = OP(C)(*inputs).owner
  File "/home/alistair/.venvs/resonant_pipeline/lib/python2.7/site-packages/theano/tensor/elemwise.py", line 496, in __init__
    scalar_op.nout)
ValueError: Cannot construct a ufunc with more than 32 operands (requested number were: inputs = 35 and outputs = 1)

```
Thinking it might be a version conflict, I've tried various different versions of Theano (0.6.0 and 0.7.0) and numpy (1.8.1, 1.9.1 and 1.10.0.dev0+3c06833), and hit the same error every time. Since the error seems to be specific to computing the Hessian, I've also tried implementing this myself [as described here](http://deeplearning.net/software/theano/tutorial/gradients.html#computing-the-hessian), rather than using the `theano.gradient.hessian` convenience function:

```python
...
_jac = jacobian(_loss, P)
# _hess = hessian(_loss, P)
_hess, updates = theano.scan(lambda i, _jac, P: te.grad(_jac[i], P),
                             sequences=te.arange(_jac.shape[0]),
                             non_sequences=[_jac, P])
hessian = theano.function([P, X, Z], _hess, updates=updates)
...
```

Again, this gives me a very similar optimization error:

```python
ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x7f7b0c48fe50>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/alistair/.venvs/resonant_pipeline/lib/python2.7/site-packages/theano/gof/opt.py", line 195, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/alistair/.venvs/resonant_pipeline/lib/python2.7/site-packages/theano/gof/opt.py", line 81, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/alistair/.venvs/resonant_pipeline/lib/python2.7/site-packages/theano/tensor/opt.py", line 5498, in apply
    new_outputs = self.optimizer(node)
  File "/home/alistair/.venvs/resonant_pipeline/lib/python2.7/site-packages/theano/tensor/opt.py", line 5445, in local_fuse
    ret = local_fuse(n)
  File "/home/alistair/.venvs/resonant_pipeline/lib/python2.7/site-packages/theano/tensor/opt.py", line 5445, in local_fuse
    ret = local_fuse(n)
  File "/home/alistair/.venvs/resonant_pipeline/lib/python2.7/site-packages/theano/tensor/opt.py", line 5445, in local_fuse
    ret = local_fuse(n)
  File "/home/alistair/.venvs/resonant_pipeline/lib/python2.7/site-packages/theano/tensor/opt.py", line 5445, in local_fuse
    ret = local_fuse(n)
  File "/home/alistair/.venvs/resonant_pipeline/lib/python2.7/site-packages/theano/tensor/opt.py", line 5445, in local_fuse
    ret = local_fuse(n)
  File "/home/alistair/.venvs/resonant_pipeline/lib/python2.7/site-packages/theano/tensor/opt.py", line 5433, in local_fuse
    n = OP(C)(*inputs).owner
  File "/home/alistair/.venvs/resonant_pipeline/lib/python2.7/site-packages/theano/tensor/elemwise.py", line 496, in __init__
    scalar_op.nout)
ValueError: Cannot construct a ufunc with more than 32 operands (requested number were: inputs = 35 and outputs = 1)
```

As far as I can tell this error doesn't seem to be fatal, in the sense that my `hessian()` function can still be called, and seems to give reasonable output (although I haven't checked it rigorously yet).

Any ideas about what might be causing this?

Alistair

### PR DESCRIPTION
**Pull request by abergeron**
Fixes #2870

### CODE REVIEW

**Comment by lamblin** [comment]
I think we should only limit it to 32 if support for C code is unavailable. I think we've discussed this with @nouiz in the past.

**Comment by nouiz** [comment]
The problem is how to make this, if we only check for cxx, that won't work. We need to check the used linker + the case if the elemwise support c code, as some of them do not have c code.

This is getting complicated. I think 32 should not cause slowdown. If we find this to be false, then we can see this again.

**Comment by nouiz** [comment]
@lamblin can you confirm, you are good with this solution? If so, you can merge.

**Comment by nouiz** [comment]
@lamblin is ok after live discussion that just repeat what I wrote.

**Pull request merged**
