### PR TITLE
Convert double recursion to simple recursion

### PR DESCRIPTION
**Pull request by carriepl**
This is done by in-lining one method in the other one.

### CODE REVIEW

**Comment by carriepl** [comment]
This allows to support graphs up to 2x bigger but now, if we want to go bigger, we need to change every place in Theano where something is recursive in the number of nodes/variables in a Theano graph... and there's quite a few of those.

**Comment by nouiz** [comment]
travis fail

**Comment by nouiz** [comment]
It is pep8.

/home/travis/miniconda/envs/pyenv/lib/python2.6/site-packages/theano/compile/pfunc.py:92:45: E126 continuation line over-indented for hanging indent

**Comment by carriepl** [comment]
I did Ye Olde Flake8, was there anything else?

**Pull request merged**
