### PR TITLE
Fix scan pushout opt. A GPU tests is already failing

### PR DESCRIPTION
**Pull request by nouiz**
fix gh-3789 also and the test

theano/scan_module/tests/test_scan.py:T_Scan_Cuda.test_gpu_memory_usage

The scan extra memory bug was created by commit https://github.com/Theano/Theano/commit/d3e30815459686 introduced by PR https://github.com/Theano/Theano/pull/3709

### CODE REVIEW

**Comment by carriepl** [comment]
I approve of this commit. If Travis is happy, so am I.

**Comment by lamblin** [comment]
OK to merge when Travis passes.

**Comment by nouiz** [comment]
I updated the PR.

**Comment by nouiz** [comment]
Don't merge, this don't fix anymore the gpu memory test.

**Comment by nouiz** [comment]
I updated the PR with a different fix. I think this fix all known problems, the extra memory reported by a GPU test and the Constant in another FunctionGraph if we enable github.com/Theano/Theano/issues/3765.

This don't enable it gh-3765 as it need more tests. As this fix current problem, I think we can merge it if travis pass and a local checkout pass all Theano tests.

**Comment by carriepl** [comment]
Some scan tests are failing in Travis

**Comment by abergeron** [comment]
There is a working fix for the scan test is in #4125.  However, the other fixes that this contains aren't in there.

**Comment by nouiz** [comment]
The good part have been ported to this PR, https://github.com/Theano/Theano/pull/4129

**Pull request closed without merging**
