### PR TITLE
Tuned insert_deepcopy

### PR DESCRIPTION
**Pull request by xoltar**

### CODE REVIEW

**Comment by lamblin** [comment]
Jenkins, would you test this, please?

**Comment by nouiz** [comment]
jenkins test this

The previous sentense didn't worked.

**Comment by nouiz** [comment]
There was some flake8 failure: http://darjeeling.iro.umontreal.ca:8080/job/Theano%20PR%20multijob/341/testReport/junit/theano.tests/test_flake8/test_format_flake8/

**Comment by lamblin** [comment]
I'll be less polite to Jenkins in the future, then :)

**Comment by nouiz** [comment]
You can locally run that test by doing:

nosetests theano/tests/test_flake8.py

**Comment by xoltar** [comment]
Hmm, local tests don't seem to catch the flake8 problem for me, maybe I'm not invoking it correctly?

> $ nosetests theano/tests/test_flake8.py                                                                                 [±careful-insert_deepcopy ●]
WARNING (theano.configdefaults): Only clang++ is supported. With g++, we end up with strange g++/OSX bugs.
S
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK (SKIP=1)

**Comment by nouiz** [comment]
jenkins test this

**Comment by lamblin** [comment]
@xoltar The flake8 test was actually skipped in your case, presumably because you do not have flake8 installed.

**Comment by xoltar** [comment]
Hmm, that's strange:

```
> $ which flake8                               
/Users/bkeller/anaconda/bin/flake8
```

**Comment by xoltar** [comment]
@nouiz This particular optimization doesn't become significant until depth reaches 80 or so, but after that point it matters quite a bit. On my machine with this tuning, at depth 200, compiling the train function takes 387.23 minutes, versus 893.79 minutes on master da95bf9202f559fa50607aaed7f7f2b0e41ce04e, but current master is probably faster than that. I'll start a new timing run on current master.

**Comment by nouiz** [comment]
Thanks.

no need for more timing. with more depth, there is more shared variable,
and the old code execution time was dependent of the number of updates. But
not the new code.

Thanks for the explanation.

**Comment by lamblin** [comment]
Then maybe the Python package itself is missing?
Can you do:
```python
>>> import flake8.engine
>>> import flake8.main
```

**Comment by xoltar** [comment]
Indeed that is the problem. I have the flake8 module, but flake8.engine has moved. This issue seems to indicate that flake8.engine has moved in recent releases.

https://github.com/tholo/pytest-flake8/issues/7

**Comment by nouiz** [comment]
In travis, we force flake8 to version 2.3

**Pull request merged**
