### PR TITLE
make var() return float16 when input is float16.

### PR DESCRIPTION
**Pull request by nouiz**
fix gh-5129.

### CODE REVIEW

**Comment by nouiz** [comment]
I think https://github.com/Theano/Theano/pull/5091 also fix this. The problem is the constant 2 that get casted to int16 that cause the upcast to float32. But gh-5091 will make the 2 be int8, so this won't upcast to float32.

**Comment by abergeron** [comment]
This will fix the immediate problem, but the larger problem is that upgrade_to_float will never return something smaller than float32.  Maybe we should change it to return float16 when floatX=float16?

**Comment by abergeron** [comment]
Forget what I said, pow uses upcast_out so @nouiz's analysis is right.  Also, I believe that my bool PR will fix this.

**Comment by nouiz** [comment]
Do you think we should merge both? How close to be merged is your PR?

**Comment by abergeron** [comment]
My PR is ready to be merged, but @lamblin wants to do some additional tests.

**Comment by nouiz** [comment]
I think we should merge this PR even if both fix it. It will help prevent the optimization local_upcast_elemwise_constant_inputs to trigger.

@abergeron are you ok to merge this one?

**Pull request merged**
