### PR TITLE
Comments out

### LINKED ISSUE #6238: Convert docstrings to comments in tests
- [x] `theano/tests/test_2nd_order_grads.py`
 - [x] `theano/tests/test_breakpoint.py`
 - [x] `theano/tests/test_dictionary_output.py`
 - [x] `theano/tests/test_flake8.py`
 - [x] `theano/tests/test_gradient.py`
 - [x] `theano/tests/test_ifelse.py`
 - [x] `theano/tests/test_printing.py`
 - [x] `theano/tests/test_record.py`

### PR DESCRIPTION
**Pull request by Alhaider**
Coverted Docstring to comments in test fix #6238

### CODE REVIEW

**Comment by abergeron** [comment]
You should remove the blank lines where there only was `"""` before except when it helps readability (so mostly keep the ones after the comments, but remove the ones before).

**Comment by Alhaider** [comment]
Did the updates I hope it pass

**Comment by nouiz** [comment]
This PR need a rebase. Maybe it was also fixed by another PR, but as there is conflict in only 4 files out of 6 modified files, maybe there is stuff done that isn't merged. So trying a rebase seem interresting.

**Comment by nouiz** [comment]
I did a quick rebase and all in this PR seem already done in the master.

thanks for the PR.

**Pull request closed without merging**
