### PR TITLE
Added tensor implementation of numpy's allclose function.

### PR DESCRIPTION
**Pull request by mbeissinger**
NEWS.txt: Add tensor.{allclose,isclose}

### CODE REVIEW

**Comment by nouiz** [comment]
thanks. numpy.allclose handle correctly inf. Can you add support for it or document that it don't support it? Dev version of numpy have a new parameter for nan, so can you document that it don't support that? That way people won't get unexpected behavior.

Can you add it in the doc in this file doc/library/tensor/basic.txt?

thanks

**Comment by mbeissinger** [comment]
Sure thing, I'll add the support and documentation.

**Comment by mbeissinger** [comment]
Works the same as numpy, docs have been updated.

**Comment by nouiz** [comment]
Can you add tests for nan and inf, to make sure they give the same answer as numpy?

**Comment by mbeissinger** [comment]
They exist in the docstring for isclose(), where should I put them - in the theano.tensor.tests.test_basic module under test_comparison class?

**Comment by nouiz** [comment]
Yes. That is the good place. Currently, we don't run doctests.

**Comment by mbeissinger** [comment]
Tests have been added.

**Comment by mbeissinger** [comment]
Ah it appears the travis build doesn't have numpy with the isclose() method - what should I do? The allclose() tests pass. Here was the error:

ERROR: test_isclose (theano.tensor.tests.test_basic.test_comparison)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/pyenv/lib/python2.6/site-packages/theano/tensor/tests/test_basic.py", line 4146, in test_isclose
    numpy.all(v1 == numpy.isclose(l, r, equal_nan=False)),
AttributeError: 'module' object has no attribute 'isclose'

**Comment by mbeissinger** [comment]
I guess second best would be to hardcode what the answer is - the test just won't keep up to date if numpy changes. I'll do that now.

**Comment by mbeissinger** [comment]
Looks all good from this end!

**Comment by nouiz** [comment]
thanks

**Pull request merged**
