### PR TITLE
Fix doc

### PR DESCRIPTION
**Pull request by abergeron**
This fixes a lot of syntax errors, sphinx warnings and plain weird rendering in the docs.

### CODE REVIEW

**Comment by nouiz** [comment]
I'm ok to merge when travis pass.

**Comment by bouthilx** [comment]
Blocksparse were indeed "fugly" but the new ones are misleading. If you want to leave it to me I'll reformat it properly with correct comments.

**Comment by abergeron** [comment]
I would merge this since it changes very little in the contents itself.  Then you are more than welcome to clarify the docs.

**Comment by bouthilx** [comment]
Alright!

**Pull request merged**
