### PR TITLE
Add tp_repr to CudaNdarray. 

### PR DESCRIPTION
**Pull request by nouiz**
This make DebugMode error print the value instead of <CudaNdarray object at 0x7f229c2f6eb0>

It will help debug the daily buildbot error with DebugMode.

### CODE REVIEW

**Comment by lamblin** [comment]
- Does that mean that we can now get rid of the special case for representing CudaNdarrays in https://github.com/Theano/Theano/blob/master/theano/sandbox/cuda/var.py#L48 ?
- Also, is it already done for GpuArray, or should we add that as well?

**Comment by lamblin** [comment]
I'm OK with the change, and I'd be ready to merge if you can confirm that the GPU-related tests pass when run locally.

**Comment by nouiz** [comment]
1) no, this is not related. What you point to print the test value. We could remove the call to numpy.asarray in that method, but we need to keep the method.

Note, that this make "print a", str(a) and repr(a) work for CudaNdarray.

I checked and GpuArray don't have it work. This need to be done in libgpuarray.

I'm starting the tests. I will see the result only Monday.

**Comment by nouiz** [comment]
@abergeron I'll let you do the change for GpuArray. This isn't urgent, so it can wait. You know more cython then me.

**Comment by lamblin** [comment]
@nouiz If we remove the call to `numpy.asarray`, then the implementation becomes identical to the one in the parent class (https://github.com/Theano/Theano/blob/master/theano/gof/graph.py#L409-L416). So we can remove it and the inherited version will be called, right?

**Comment by nouiz** [comment]
right. I updated the PR.

**Pull request merged**
