### PR TITLE
[MRG] Ignore E501 (lines too long) for the flake8 test.

### PR DESCRIPTION
**Pull request by abergeron**
This also somehow revealed a bunch of errors in files that where not on the whitelist, so I fixed those.

I also took off the whitelist files that pass due to this change.

### CODE REVIEW

**Comment by nouiz** [comment]
Way for the python 2 3 pr to be merged before doing any of this.

**Comment by nouiz** [comment]
typo in my previous comments. There is a big PR that make Theano support
python2 and 3 in a single code base. This is a big PR that conflict with
this one. We should merge the other PR first. I think we should wait for
pep8, flake8 fix that the python2/3 PR is merge first as they will conflict.

**Comment by abergeron** [comment]
Can we merge this?   I'll do the rebasing for the python 2/3 PR.

**Comment by lamblin** [comment]
I'm OK with those changes, you can merge when it is the most convenient.

**Comment by abergeron** [comment]
I did a rebase for the python23 PR

**Comment by lamblin** [comment]
For some reason, there seem to be flake8 violations on python 2.6 but not 3.3...

**Comment by abergeron** [comment]
This is weird since I've made those changes using python 2 and the exact version that is used on travis.

Anyway, I've fixed the problems for now.

**Comment by nouiz** [comment]
I'm ok to merge when travis pass.

**Comment by abergeron** [comment]
So I found why there are problems on travis but not locally.  These come from new code that is merged in master and does not respect the format.  They don't show up on the branch itself, only when you merge with master.

I made a rebase to the most recent master so it should pass this time.  We should merge this before any new problem gets in.

**Comment by nouiz** [comment]
travis fail.

**Comment by abergeron** [comment]
Should be fixed (again).

**Comment by abergeron** [comment]
Yay, it passed!

**Pull request merged**
