### PR TITLE
Change @ caractere to #, to prevent collision with github convention to ...

### PR DESCRIPTION
**Pull request by nouiz**
...notice people.

### CODE REVIEW

**Comment by nouiz** [comment]
This happened again here:

https://github.com/Theano/Theano/issues/3612#issuecomment-155370904

Do you have a preference for #N that can conflict with github issue or [id 0]? If I don't get a response, I'll use [id 0] after a rebase of this PR.

**Comment by nouiz** [comment]
I updated this PR.

**Comment by abergeron** [comment]
I'm ok with this once travis passes

**Comment by nouiz** [comment]
@lamblin any objection?

**Comment by lamblin** [comment]
OK for me.

**Pull request merged**
