### PR TITLE
Scan push out seq scan

### LINKED ISSUE #3282: Optimization failure (SeqOptimizer, PushOutNonSeqScan)
The following code generates an optimization failure.

    import theano
    outputs, _ = theano.scan(lambda x: (x * x, x), non_sequences=[1], n_steps=2)
    f = theano.function(inputs=[], outputs=outputs)

When run I see 6 occurrences of this warning/error sequence:

    WARNING: An optimization wanted to replace a Variable in the graph, but the replacement for it doesn't remove it. We disabled the optimization. Your function runs correctly, but it would be appreciated if you submit this problem to the mailing list theano-users so that we can fix it.
    scanOp_pushout_nonseqs_ops [(for{cpu,scan_fn}.0, Alloc.0)]
    ERROR (theano.gof.opt): SeqOptimizer apply <theano.scan_module.scan_opt.PushOutNonSeqScan object at 0x0000000004C33FD0>
    ERROR (theano.gof.opt): Traceback:
    ERROR (theano.gof.opt): Traceback (most recent call last):
      File "<snip>\theano\theano\gof\opt.py", line 194, in apply
        sub_prof = optimizer.optimize(fgraph)
      File "<snip>\theano\theano\gof\opt.py", line 79, in optimize
        ret = self.apply(fgraph, *args, **kwargs)
      File "<snip>\theano\theano\scan_module\scan_opt.py", line 228, in apply
        self.process_node(fgraph, node)
      File "<snip>\theano\theano\scan_module\scan_opt.py", line 401, in process_node
        reason='scanOp_pushout_nonseqs_ops')
      File "<snip>\theano\theano\gof\toolbox.py", line 324, in replace_all_validate_remove
        raise ReplacementDidntRemovedError()
    ReplacementDidntRemovedError

Then a single instance of:

    ERROR (theano.gof.opt): EquilibriumOptimizer max'ed out by 'all_pushout_opt'. You can safely raise the current threshold of 5.000000 with the theano flag 'optdb.max_use_ratio'.

A few observations:
* Setting `n_steps=1` avoids the problem.
* Returning just `x` from the lambda avoids the problem.
* Returning just `x * x` from the lambda avoids the problem.
* Returning `(x + x, x)` from the lambda also causes the problem.
* Returning `(x, x + x)` from the lambda also causes the problem.

### PR DESCRIPTION
**Pull request by carriepl**
Fixes #3282

### CODE REVIEW

**Comment by carriepl** [comment]
Improved the comment as requested by @nouiz.

**Comment by nouiz** [comment]
I'm ok with this when tests pass and someone else review this

**Comment by carriepl** [comment]
@lamblin or @abergeron : can one of you spare a few minutes?

**Comment by carriepl** [comment]
(Travis was killed on the last commit because it's only a comment change)

**Pull request merged**
