### PR TITLE
pep8 typed list directory

### LINKED ISSUE #3419: pep8 typed_list dir

### PR DESCRIPTION
**Pull request by shabanian**
Fixes #3419.

### CODE REVIEW

**Comment by vdumoulin** [comment]
Looks good! Once the Travis build passes, I'll merge. Thank you!

**Comment by shabanian** [comment]
Cool. Thank YOU!

**Comment by vdumoulin** [comment]
The tests are failing when `floatX == 'float32'` because `numpy.random.rand` produces `float64` values in `TestMakeList.test_correct_answer`. We should cast `A`, `B`, `X` and `Y` to `theano.config.floatX`.

**Comment by shabanian** [comment]
Fixes #3419.

**Comment by vdumoulin** [comment]
@shabanian the tests are still failing. `theano.config.floatX` is a string and can't be used to cast numpy arrays. Instead, try the following:

``` python
my_array = numpy.cast[theano.config.floatX](my_array)
```

**Comment by shabanian** [comment]
Fixes #3419.

**Comment by vdumoulin** [comment]
Everything passes, I'll merge. Good job! :)

**Pull request merged**
