### PR TITLE
Restrict cuDNN reduction to contiguous inputs

### PR DESCRIPTION
**Pull request by abergeron**
There is a problem that was reported with cuDNN reduction where it would give different results than before it was integrated.

This *may* be because there are corner cases where non-contiguous inputs are not supported, so we are tentatively reversing this.  More testing is required to determine the exact cause.

### CODE REVIEW

**Comment by abergeron** [comment]
jenkins test this please

**Comment by nouiz** [comment]
jenkins have one test case failure. The test need to be updated.

**Comment by nouiz** [comment]
jenkins failed.

**Comment by nouiz** [comment]
I canceled the end of travis.

**Pull request merged**
