### PR TITLE
Fix extra scan due to old information in infer shape.

### PR DESCRIPTION
**Pull request by nouiz**
fix gh-3560

### CODE REVIEW

**Comment by abergeron** [comment]
That looks ok to me but someone should have a second look.

**Comment by carriepl** [comment]
This also looks good to me. Based on this and the result of Arnaud's review, I'll be merging.

**Comment by nouiz** [comment]
It is good that it is merged, but it is possible that this slow down
compilation. I'm still investigating this.

**Comment by carriepl** [comment]
I mentionned this IRL to @nouiz but I prefer to also have a written trace : there is a use case from a user (@caglar) which took ~830 seconds to compile on my machine before the introduction of the bug that this PR meant to resolve but now takes ~575 seconds. So it is very possible this PR might slow down compilation but we have at least one data point where it is still very useful.

As @nouiz pointed out, there is a good chance that this improvement comes from the changes that were done in the same PR as the bug was introduced.

**Comment by nouiz** [comment]
I compared the compilation time for gh-3412 and it didn't change. I also checked for the GSoC case, and it did raise a little, but I think this is due to noise and not a real problem. Like the CPU being not overclocked the same way on both computer where I did it.

So I'm pretty sure the compilation time didn't got slowed down.

**Pull request merged**
