### PR TITLE
[WIP] Draft of gpuarray.use(). 

### PR DESCRIPTION
**Pull request by nouiz**
Wait for the big merge before finishing this.

### CODE REVIEW

**Comment by abergeron** [comment]
What's wrong with the current code?

**Comment by nouiz** [comment]
It generate a Shape_i() without taking into account the node that aren't in the graph. So it do not optimize like shape_feature is supposed to do.

**Comment by abergeron** [comment]
I think you are mixing stuff up.  This is about gpuarray.use(), not shape_i.

**Comment by nouiz** [comment]
You are right about my bad comment. The problem is that currently, you need multiple function call to do the same as "device=cuda0" in the python code. We need to be able to do this easily as in the old back-end. I think we should try to keep the same interface as it seem to cover all cases we needed.

**Comment by abergeron** [comment]
In that case you are right that this should wait after the multi-gpu merge.  But I'm not sure that model will be completely appropriate considering that it was developed for single-gpu use.

**Pull request closed without merging**
