### PR TITLE
Impossible to compile a COp

### PR DESCRIPTION
**Pull request by theaverageguy**
Fixes https://github.com/Theano/Theano/issues/4199

### CODE REVIEW

**Comment by nouiz** [comment]
thanks, we can merge when travis pass.

**Comment by theaverageguy** [comment]
The build passed @nouiz :) 
I am adding 3 more PRs today, and then will move to gsoc project discussions.

**Comment by lamblin** [comment]
Thanks!

**Comment by lamblin** [comment]
A small test for that feature would be to add a dummy Op with more outputs than inputs, in a `.c` file in `theano/gof/tests/`, and define a `COp` for instance in `test_op.py` or `test_cop.py`.
This is not a global test of `COp`, but at least a unit test for a past known issue.

**Pull request merged**
