### PR TITLE
profile_memory, print the expected peak memory usage if excluding inplace opt.

### PR DESCRIPTION
**Pull request by nouiz**
Also code clean up, refactoring and better output of the information.

### CODE REVIEW

**Comment by lamblin** [comment]
This breaks a test that expects the old messages to be printed: https://github.com/nouiz/Theano/blob/profile/theano/compile/tests/test_profiling.py#L52-L65

**Comment by nouiz** [comment]
I update the test

**Comment by lamblin** [comment]
I'm pretty sure the lines in the `else:` block should be updated as well.

**Comment by nouiz** [comment]
done

**Pull request merged**
