### PR TITLE
Speed up h_softmax when full output is requested.

### PR DESCRIPTION
**Pull request by adbrebs**
cf #3752, thanks @shawnjhenry!

In h_softmax, replace sparse_block_dot with tensor_block when full output is requested.

### CODE REVIEW

**Comment by lamblin** [comment]
I guess there should be a test for that.

**Comment by nouiz** [comment]
In theano/tensor/nnet/test_nnet.py, there is already a test that execute with target=None. But it only check the shape of the result, not the value. Can you add a check that the value is what is expected?

 Can you confirm that what this do is a speed up and nothing else?

thanks

**Comment by adbrebs** [comment]
> In theano/tensor/nnet/test_nnet.py, there is already a test that execute with target=None. But it only check the shape of the result, not the value. Can you add a check that the value is what is expected?

Ok I will do it next week.

> Can you confirm that what this do is a speed up and nothing else?
Yes, this yields a 2-3x speedup in my experiments.

**Comment by lamblin** [comment]
Forcing new run of Travis after #3885 has been merged.

**Comment by adbrebs** [comment]
I have added a test suggested by @lamblin. It checks if un_output_tg and fun_output computes the same thing.

**Comment by nouiz** [comment]
thanks

**Pull request merged**
