### PR TITLE
Fix dnn loading/usage on mac

### PR DESCRIPTION
**Pull request by abergeron**

### CODE REVIEW

**Comment by abergeron** [comment]
This could break things on windows, so we'll have to watch out for that.

**Comment by slefrancois** [comment]
jenkins test this

**Comment by slefrancois** [comment]
It might break things on linux too, see jenkins.

**Comment by abergeron** [comment]
Apparently it does, I'll fallback to a mac-specific fix then.

**Comment by abergeron** [comment]
This is now less likely to break other platforms.

**Comment by abergeron** [comment]
Also is there a way to ask jenkins to test a specific PR on mac and windows?

**Comment by slefrancois** [comment]
not yet, but [windows pr are coming](https://github.com/Theano/Theano/pull/6146)

**Comment by abergeron** [comment]
Nice!

**Comment by abergeron** [comment]
This has now passed.

**Comment by slefrancois** [comment]
We can test once #6149 is merged.

**Comment by lamblin** [comment]
jenkins test mac

**Comment by f0k** [comment]
Just noticed that @275bd60 breaks cuDNN support for me, I get:
```
Can not use cuDNN on context None: cannot compile with cuDNN. We got this error:
/usr/bin/ld: cannot find -lcudnn
collect2: error: ld returned 1 exit status
```
`libcudnn.so` is installed in `/usr/local/cuda/lib64`, which is included in `/etc/ld.conf.so.d/cudatoolkit` so `ldconfig` can find it. What is the rationale behind not defaulting `dnn.library_path` to the CUDA library path any longer?

**Comment by abergeron** [comment]
The rationale was that the packages provided by NVIDIA install in /usr/local.

However it seems that lots of people have cudnn in the cuda directory so that has been restored as part of #6146

**Comment by f0k** [comment]
Hmm, wait, #6146 sets `theano.config.dnn.library_path` to `/usr/local/cuda/lib`, not `/usr/local/cuda/lib64` as before 275bd60. So it still doesn't work for me without manually overriding `dnn.library_path`. Should it default to `lib64` on unix platforms?

**Comment by abergeron** [comment]
Yes, you're right.  Does this work on your system: https://github.com/Theano/Theano/pull/6256?

**Comment by f0k** [comment]
> Does this work on your system:

Yes, it does!

**Pull request merged**
