### PR TITLE
Mac PR verbose to find which test segfaults

### PR DESCRIPTION
**Pull request by slefrancois**

### CODE REVIEW

**Comment by slefrancois** [comment]
jenkins test mac

**Comment by slefrancois** [comment]
Mac tests did not segfault, maybe master was fixed?

**Comment by nouiz** [comment]
old jenkins mac results with too many failure: http://earlgrey.iro.umontreal.ca:8080/job/Theano_pr_mac/27/

jenkins test mac

There was many jenkins errors. That should not happen. Do you know why so many tests fail?

restarting jenkins just in case it was a temp problem.

**Comment by slefrancois** [comment]
Lots of CUDA_ERROR_LAUNCH_TIMEOUT, could it be a driver or CUDA issue on mac?

**Comment by slefrancois** [comment]
segfault stopped, but now we have CUDA_ERROR_LAUNCH_TIMEOUT which are on the master too.

**Comment by slefrancois** [comment]
GPU testing has been removed from Mac buildbots, it now passes.

**Pull request closed without merging**
