### PR TITLE
Crash fix with openmp and intdiv and modulo

### PR DESCRIPTION
**Pull request by nouiz**
fix gh-5875

### CODE REVIEW

**Comment by lamblin** [comment]
Have you tried dividing by zero on CPU with OpenMP?
Because if it brings back the floating point exception / core dump, I'm not sure it is a good idea.

**Comment by lamblin** [comment]
An option may be to return -1 in that case, like with CUDA, but I do not like that either.
A better option IMO would be to redefine `%(fail)s;` in Elemwise, but I'm not sure it is feasible.

**Comment by nouiz** [comment]
I think we should first fix the regression in master. It is better to bring back the segfault as it is more rare then having all openmp code not working. the segfault is due to a problem in the user code, the openmp is due to our problem, so the user can't fix it.

When someone have the time, I think we should revisit the fail in elemwise to allow to give a python error also with openmp. I think the fail in the scalar should just be something like my_error_code = N, and the scalar set it to its own error code. Then there should be another method in the scalar op that will convert that number to a python error and that error should be executed after the loop.

On the GPU, with the unified memory, we could allocate the variable my_error_code on the CPU and still have the kernel write to it. Yes, the error will be delayed if we don't sync as all error reporting on the GPU. This one will be delayed to the next call of that thunk (of it could be one error code for the cmodule, not just one per thunk).

As this is more then just a quick fix, I would push that to its own issue to fix segfaul for openmp and give python error for integer division by 0 on the GPU.

I think we should fix the regression now.

**Comment by nouiz** [comment]
I let @lamblin fix this. It does more then what I understood at first.

**Pull request closed without merging**
