### PR TITLE
Crash unpickle

### PR DESCRIPTION
**Pull request by nouiz**
fix gh-2516

Reported by Dmitry Bogdanov

### CODE REVIEW

**Comment by rizar** [comment]
Looks good!

**Comment by abergeron** [comment]
While this does fix the problem I wonder if we can't make our singleton implementation better.

The best answer for this question: http://stackoverflow.com/questions/6760685/creating-a-singleton-in-python seems to have an interesting approach.

**Comment by nouiz** [comment]
As it fix it, can we merge this PR and let a better singleton implementation to later?

Personnaly, I do not want to spend time anymore on singleton in python. Too hard to debug and make sure that it work in all case. So I would call it, try to make singleton to lower the number of object, but do not expect this is always true.

**Comment by abergeron** [comment]
All right.

**Pull request merged**
