### PR TITLE
(small fix) Re-allow runtime algorithms for conv3d Ops.

### PR DESCRIPTION
**Pull request by notoraptor**
When updating lists of algorithms, I had forgotten to add runtime algos to conv3d allowed algos.

@abergeron @lamblin

### CODE REVIEW

**Comment by nouiz** [comment]
jenkins have failures

**Comment by notoraptor** [comment]
@nouiz Strangely, failures seem related to `subtensor` modules. They should not be influenced by this PR.

```
[secondBranch] ======================================================================
[secondBranch] ERROR: test1_err_bounds (theano.gpuarray.tests.test_subtensor.G_subtensor)
[secondBranch] ----------------------------------------------------------------------
[secondBranch] Traceback (most recent call last):
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/tensor/tests/test_subtensor.py", line 144, in test1_err_bounds
[secondBranch]     self.eval_output_and_check(t)
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/tensor/tests/test_subtensor.py", line 116, in eval_output_and_check
[secondBranch]     tval = f()
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/compile/function_module.py", line 898, in __call__
[secondBranch]     storage_map=getattr(self.fn, 'storage_map', None))
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/gof/link.py", line 325, in raise_with_op
[secondBranch]     reraise(exc_type, exc_value, exc_trace)
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/compile/function_module.py", line 884, in __call__
[secondBranch]     self.fn() if output_subset is None else\
[secondBranch]   File "pygpu/gpuarray.pyx", line 1415, in pygpu.gpuarray.pygpu_index (pygpu/gpuarray.c:18341)
[secondBranch]   File "pygpu/gpuarray.pyx", line 331, in pygpu.gpuarray.array_index (pygpu/gpuarray.c:6096)
[secondBranch] ValueError: Invalid slice value: slice(7, 140011525714560, 0) when indexing array on dimension 0 of length 3
[secondBranch] Apply node that caused the error: GpuSubtensor{int64}(<GpuArrayType<None>(float32, vector)>, Constant{7})
[secondBranch] Toposort index: 0
[secondBranch] Inputs types: [GpuArrayType<None>(float32, vector), Scalar(int64)]
[secondBranch] Inputs shapes: [(3,), ()]
[secondBranch] Inputs strides: [(4,), ()]
[secondBranch] Inputs values: [gpuarray.array([ 1.,  1.,  1.], dtype=float32), 7]
[secondBranch] Outputs clients: [[HostFromGpu(gpuarray)(GpuSubtensor{int64}.0)]]
[secondBranch] 
[secondBranch] HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
[secondBranch] HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
[secondBranch] 
[secondBranch] ======================================================================
[secondBranch] ERROR: test2_err_bounds0 (theano.gpuarray.tests.test_subtensor.G_subtensor)
[secondBranch] ----------------------------------------------------------------------
[secondBranch] Traceback (most recent call last):
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/tensor/tests/test_subtensor.py", line 240, in test2_err_bounds0
[secondBranch]     self.eval_output_and_check, [t])
[secondBranch]   File "/miniconda/lib/python2.7/unittest/case.py", line 473, in assertRaises
[secondBranch]     callableObj(*args, **kwargs)
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/tensor/tests/test_subtensor.py", line 116, in eval_output_and_check
[secondBranch]     tval = f()
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/compile/function_module.py", line 898, in __call__
[secondBranch]     storage_map=getattr(self.fn, 'storage_map', None))
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/gof/link.py", line 325, in raise_with_op
[secondBranch]     reraise(exc_type, exc_value, exc_trace)
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/compile/function_module.py", line 884, in __call__
[secondBranch]     self.fn() if output_subset is None else\
[secondBranch]   File "pygpu/gpuarray.pyx", line 1415, in pygpu.gpuarray.pygpu_index (pygpu/gpuarray.c:18341)
[secondBranch]   File "pygpu/gpuarray.pyx", line 331, in pygpu.gpuarray.array_index (pygpu/gpuarray.c:6096)
[secondBranch] ValueError: Invalid slice value: slice(4, 140004767159192, 0) when indexing array on dimension 1 of length 3
[secondBranch] Apply node that caused the error: GpuSubtensor{int64, int64}(<GpuArrayType<None>(float32, matrix)>, Constant{0}, Constant{4})
[secondBranch] Toposort index: 0
[secondBranch] Inputs types: [GpuArrayType<None>(float32, matrix), Scalar(int64), Scalar(int64)]
[secondBranch] Inputs shapes: [(2, 3), (), ()]
[secondBranch] Inputs strides: [(12, 4), (), ()]
[secondBranch] Inputs values: ['not shown', 0, 4]
[secondBranch] Outputs clients: [[HostFromGpu(gpuarray)(GpuSubtensor{int64, int64}.0)]]
[secondBranch] 
[secondBranch] HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
[secondBranch] HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
[secondBranch] 
[secondBranch] ======================================================================
[secondBranch] ERROR: test2_err_bounds1 (theano.gpuarray.tests.test_subtensor.G_subtensor)
[secondBranch] ----------------------------------------------------------------------
[secondBranch] Traceback (most recent call last):
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/tensor/tests/test_subtensor.py", line 254, in test2_err_bounds1
[secondBranch]     self.eval_output_and_check, [t])
[secondBranch]   File "/miniconda/lib/python2.7/unittest/case.py", line 473, in assertRaises
[secondBranch]     callableObj(*args, **kwargs)
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/tensor/tests/test_subtensor.py", line 116, in eval_output_and_check
[secondBranch]     tval = f()
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/compile/function_module.py", line 898, in __call__
[secondBranch]     storage_map=getattr(self.fn, 'storage_map', None))
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/gof/link.py", line 325, in raise_with_op
[secondBranch]     reraise(exc_type, exc_value, exc_trace)
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/compile/function_module.py", line 884, in __call__
[secondBranch]     self.fn() if output_subset is None else\
[secondBranch]   File "pygpu/gpuarray.pyx", line 1415, in pygpu.gpuarray.pygpu_index (pygpu/gpuarray.c:18341)
[secondBranch]   File "pygpu/gpuarray.pyx", line 331, in pygpu.gpuarray.array_index (pygpu/gpuarray.c:6096)
[secondBranch] ValueError: Invalid slice value: slice(3, 140004495657792, 0) when indexing array on dimension 1 of length 3
[secondBranch] Apply node that caused the error: GpuSubtensor{int64:int64:, int64}(<GpuArrayType<None>(float32, matrix)>, Constant{4}, Constant{5}, Constant{3})
[secondBranch] Toposort index: 0
[secondBranch] Inputs types: [GpuArrayType<None>(float32, matrix), Scalar(int64), Scalar(int64), Scalar(int64)]
[secondBranch] Inputs shapes: [(2, 3), (), (), ()]
[secondBranch] Inputs strides: [(12, 4), (), (), ()]
[secondBranch] Inputs values: ['not shown', 4, 5, 3]
[secondBranch] Outputs clients: [[HostFromGpu(gpuarray)(GpuSubtensor{int64:int64:, int64}.0)]]
[secondBranch] 
[secondBranch] HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
[secondBranch] HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
[secondBranch] 
[secondBranch] ======================================================================
[secondBranch] ERROR: test1_err_bounds (theano.gpuarray.tests.test_subtensor.G_subtensorF16)
[secondBranch] ----------------------------------------------------------------------
[secondBranch] Traceback (most recent call last):
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/tensor/tests/test_subtensor.py", line 144, in test1_err_bounds
[secondBranch]     self.eval_output_and_check(t)
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/tensor/tests/test_subtensor.py", line 116, in eval_output_and_check
[secondBranch]     tval = f()
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/compile/function_module.py", line 898, in __call__
[secondBranch]     storage_map=getattr(self.fn, 'storage_map', None))
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/gof/link.py", line 325, in raise_with_op
[secondBranch]     reraise(exc_type, exc_value, exc_trace)
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/compile/function_module.py", line 884, in __call__
[secondBranch]     self.fn() if output_subset is None else\
[secondBranch]   File "pygpu/gpuarray.pyx", line 1415, in pygpu.gpuarray.pygpu_index (pygpu/gpuarray.c:18341)
[secondBranch]   File "pygpu/gpuarray.pyx", line 331, in pygpu.gpuarray.array_index (pygpu/gpuarray.c:6096)
[secondBranch] ValueError: Invalid slice value: slice(7, 140011525714560, 0) when indexing array on dimension 0 of length 3
[secondBranch] Apply node that caused the error: GpuSubtensor{int64}(<GpuArrayType<None>(float16, vector)>, Constant{7})
[secondBranch] Toposort index: 0
[secondBranch] Inputs types: [GpuArrayType<None>(float16, vector), Scalar(int64)]
[secondBranch] Inputs shapes: [(3,), ()]
[secondBranch] Inputs strides: [(2,), ()]
[secondBranch] Inputs values: [gpuarray.array([ 1.,  1.,  1.], dtype=float16), 7]
[secondBranch] Outputs clients: [[HostFromGpu(gpuarray)(GpuSubtensor{int64}.0)]]
[secondBranch] 
[secondBranch] HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
[secondBranch] HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
[secondBranch] 
[secondBranch] ======================================================================
[secondBranch] ERROR: test2_err_bounds0 (theano.gpuarray.tests.test_subtensor.G_subtensorF16)
[secondBranch] ----------------------------------------------------------------------
[secondBranch] Traceback (most recent call last):
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/tensor/tests/test_subtensor.py", line 240, in test2_err_bounds0
[secondBranch]     self.eval_output_and_check, [t])
[secondBranch]   File "/miniconda/lib/python2.7/unittest/case.py", line 473, in assertRaises
[secondBranch]     callableObj(*args, **kwargs)
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/tensor/tests/test_subtensor.py", line 116, in eval_output_and_check
[secondBranch]     tval = f()
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/compile/function_module.py", line 898, in __call__
[secondBranch]     storage_map=getattr(self.fn, 'storage_map', None))
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/gof/link.py", line 325, in raise_with_op
[secondBranch]     reraise(exc_type, exc_value, exc_trace)
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/compile/function_module.py", line 884, in __call__
[secondBranch]     self.fn() if output_subset is None else\
[secondBranch]   File "pygpu/gpuarray.pyx", line 1415, in pygpu.gpuarray.pygpu_index (pygpu/gpuarray.c:18341)
[secondBranch]   File "pygpu/gpuarray.pyx", line 331, in pygpu.gpuarray.array_index (pygpu/gpuarray.c:6096)
[secondBranch] ValueError: Invalid slice value: slice(4, 140004486741360, 0) when indexing array on dimension 1 of length 3
[secondBranch] Apply node that caused the error: GpuSubtensor{int64, int64}(<GpuArrayType<None>(float16, matrix)>, Constant{0}, Constant{4})
[secondBranch] Toposort index: 0
[secondBranch] Inputs types: [GpuArrayType<None>(float16, matrix), Scalar(int64), Scalar(int64)]
[secondBranch] Inputs shapes: [(2, 3), (), ()]
[secondBranch] Inputs strides: [(6, 2), (), ()]
[secondBranch] Inputs values: ['not shown', 0, 4]
[secondBranch] Outputs clients: [[HostFromGpu(gpuarray)(GpuSubtensor{int64, int64}.0)]]
[secondBranch] 
[secondBranch] HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
[secondBranch] HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
[secondBranch] 
[secondBranch] ======================================================================
[secondBranch] ERROR: test2_err_bounds1 (theano.gpuarray.tests.test_subtensor.G_subtensorF16)
[secondBranch] ----------------------------------------------------------------------
[secondBranch] Traceback (most recent call last):
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/tensor/tests/test_subtensor.py", line 254, in test2_err_bounds1
[secondBranch]     self.eval_output_and_check, [t])
[secondBranch]   File "/miniconda/lib/python2.7/unittest/case.py", line 473, in assertRaises
[secondBranch]     callableObj(*args, **kwargs)
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/tensor/tests/test_subtensor.py", line 116, in eval_output_and_check
[secondBranch]     tval = f()
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/compile/function_module.py", line 898, in __call__
[secondBranch]     storage_map=getattr(self.fn, 'storage_map', None))
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/gof/link.py", line 325, in raise_with_op
[secondBranch]     reraise(exc_type, exc_value, exc_trace)
[secondBranch]   File "/home/jenkins/workspace/Theano_PR/theano/compile/function_module.py", line 884, in __call__
[secondBranch]     self.fn() if output_subset is None else\
[secondBranch]   File "pygpu/gpuarray.pyx", line 1415, in pygpu.gpuarray.pygpu_index (pygpu/gpuarray.c:18341)
[secondBranch]   File "pygpu/gpuarray.pyx", line 331, in pygpu.gpuarray.array_index (pygpu/gpuarray.c:6096)
[secondBranch] ValueError: Invalid slice value: slice(3, 140004565809984, 0) when indexing array on dimension 1 of length 3
[secondBranch] Apply node that caused the error: GpuSubtensor{int64:int64:, int64}(<GpuArrayType<None>(float16, matrix)>, Constant{4}, Constant{5}, Constant{3})
[secondBranch] Toposort index: 0
[secondBranch] Inputs types: [GpuArrayType<None>(float16, matrix), Scalar(int64), Scalar(int64), Scalar(int64)]
[secondBranch] Inputs shapes: [(2, 3), (), (), ()]
[secondBranch] Inputs strides: [(6, 2), (), (), ()]
[secondBranch] Inputs values: ['not shown', 4, 5, 3]
[secondBranch] Outputs clients: [[HostFromGpu(gpuarray)(GpuSubtensor{int64:int64:, int64}.0)]]
[secondBranch] 
[secondBranch] HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
[secondBranch] HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
[secondBranch] 
[secondBranch] ----------------------------------------------------------------------
[secondBranch] Ran 2833 tests in 5727.114s
[secondBranch] 
[secondBranch] FAILED (SKIP=582, errors=6)
```

**Comment by lamblin** [comment]
Indeed, it should have nothing to do with your changes.
@slefrancois Do you think it could be due to a change in the config of Jenkins?

**Comment by nouiz** [comment]
A change in libgpuarray triggered those error. The fix was merged.

jenkins test this

**Pull request merged**
