### PR TITLE
Conv3d

### PR DESCRIPTION
**Pull request by nouiz**
fix gh-3659

This need to be ported to the new back-end, but I have difficulty as conv3d don't work well in it and the merge of alpha and output node don't seem to work well.

### CODE REVIEW

**Comment by lamblin** [comment]
It seems OK to me, but I'd like @abergeron to take a look at the change removing `nd` from `alpha_merge` and `output_merge`.

**Comment by bartvm** [comment]
I'm not entirely sure how to reproduce the crash when there is no g++ compiler. It happened for me when I hadn't accepted Xcode's T&C yet, but now that I have, I don't think there's a way to un-accept them... Either way, I think it's fine, and if it doesn't fix it, Travis for Blocks will let us know.

**Comment by lamblin** [comment]
Nevermind, the same change had already been done in `gpuarray`, so this should be correct.

**Comment by lamblin** [comment]
The issue with conv3d and alpha/beta may have been solved by #3726

**Pull request merged**
