### PR TITLE
jenkins test fail if theano.gpuarray missing

### PR DESCRIPTION
**Pull request by slefrancois**

### CODE REVIEW

**Comment by slefrancois** [comment]
jenkins test windows mac

**Comment by nouiz** [comment]
jenkins test mac windows

**Comment by nouiz** [comment]
jenkins test window

**Comment by notoraptor** [comment]
Just a note to tell that I can reproduce 3 errors on the 4 errors reported by Jenkins on Windows. The one I can not reproduce is:
```
theano.gpuarray.tests.test_blocksparse.BlockSparse_Gemv_and_Outer.test_sparseblockouter
```
( http://earlgrey.iro.umontreal.ca:8080/job/Theano_pr_win/44/testReport/junit/theano.gpuarray.tests.test_blocksparse/BlockSparse_Gemv_and_Outer/test_sparseblockouter/ )
But this error is quite strange:
```
  Max Abs Diff:  1.19209e-07
  Mean Abs Diff:  6.87405e-10
  Median Abs Diff:  0.0
  Std Abs Diff:  6.85634e-09
  Max Rel Diff:  1.32407e-06
  Mean Rel Diff:  2.93427e-09
  Median Rel Diff:  0.0
  Std Rel Diff:  4.29433e-08

  rtol, atol: 1e-05 1e-05
```
The max abs diff is about 1e-7 while atol is 1e-5. This should not generate an error, isn'it ?

**Comment by nouiz** [comment]
This is probably due to the seed changing. Forget this error for now. The assert isn't done on the rtol or atol separatly, but on the combination of both of them. So even if they pass individually, it could still fail. I forgot the exact formula.

**Comment by nouiz** [comment]
jenkins test this win

**Comment by notoraptor** [comment]
Still investigating errors here. They seems to be related to class `theano.gpuarray.blocksparse.GpuSparseBlockOuter`. The strange thing is that error may occur or may not occur, although seed is the same (default seed given by `config.unittests.rseed`, ie. `666`):

Here is the output for many successive calls to one of failing tests, `theano.gpuarray.tests.test_blocksparse.BlockSparse_Gemv_and_Outer.test_sparseblockgemv_grad_1`. I added a line to print current `config.unittests.rseed`, and we can see that it's always the same value. At one step I clear theano cache with `theano-cache purge`. After that, the next test call gives no error, but the second call gives an error again. Note that, even if theano cache is not cleared, some calls may give no error as well. It's quite arbitrary.

Still investigating, but it's a really strange error.

```

(python2) C:\Users\notoraptor\mila\dev\git\theano>set THEANO_FLAGS=cmodule.debug=True && nosetests -xvs theano.gpuarray.tests.test_blocksparse:BlockSparse_Gemv_and_Outer.test_sparseblockgemv_grad_1
Using cuDNN version 7001 on context None
Mapped name None to device cuda: GeForce GTX 1050 (0000:01:00.0)
test_sparseblockgemv_grad_1 (theano.gpuarray.tests.test_blocksparse.BlockSparse_Gemv_and_Outer) ... unittest.rseed is 666
unittest.rseed is 666
ERROR

======================================================================
ERROR: test_sparseblockgemv_grad_1 (theano.gpuarray.tests.test_blocksparse.BlockSparse_Gemv_and_Outer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\notoraptor\mila\dev\git\theano\theano\tensor\nnet\tests\test_blocksparse.py", line 232, in test_sparseblockgemv_grad_1
    utt.verify_grad(metaop, [b_val, h_val, W_val], mode=self.mode)
  File "C:\Users\notoraptor\mila\dev\git\theano\theano\tests\unittest_tools.py", line 93, in verify_grad
    T.verify_grad(op, pt, n_tests, rng, *args, **kwargs)
  File "C:\Users\notoraptor\mila\dev\git\theano\theano\gradient.py", line 1795, in verify_grad
    abs_tol, rel_tol)
GradientError: GradientError: numeric gradient and analytic gradient exceed tolerance:
        At position 0 of argument 2 with shape (1L, 1L, 1L, 1L),
            val1 = 0.000000      ,  val2 = 0.989321
            abs. error = 0.989321,  abs. tolerance = 0.010000
            rel. error = 1.000000,  rel. tolerance = 0.010000
Exception args:
The error happened with the following inputs:, [array([[ 1.17346799]], dtype=float32), array([[[ 0.82418805]]], dtype=float32), array([[[[ 0.47996601]]]], dtype=float32)],
The value of eps is:, None,
The out_type is:, None

----------------------------------------------------------------------
Ran 1 test in 5.063s

FAILED (errors=1)

(python2) C:\Users\notoraptor\mila\dev\git\theano>set THEANO_FLAGS=cmodule.debug=True && nosetests -xvs theano.gpuarray.tests.test_blocksparse:BlockSparse_Gemv_and_Outer.test_sparseblockgemv_grad_1
Using cuDNN version 7001 on context None
Mapped name None to device cuda: GeForce GTX 1050 (0000:01:00.0)
test_sparseblockgemv_grad_1 (theano.gpuarray.tests.test_blocksparse.BlockSparse_Gemv_and_Outer) ... unittest.rseed is 666
unittest.rseed is 666
ERROR

======================================================================
ERROR: test_sparseblockgemv_grad_1 (theano.gpuarray.tests.test_blocksparse.BlockSparse_Gemv_and_Outer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\notoraptor\mila\dev\git\theano\theano\tensor\nnet\tests\test_blocksparse.py", line 232, in test_sparseblockgemv_grad_1
    utt.verify_grad(metaop, [b_val, h_val, W_val], mode=self.mode)
  File "C:\Users\notoraptor\mila\dev\git\theano\theano\tests\unittest_tools.py", line 93, in verify_grad
    T.verify_grad(op, pt, n_tests, rng, *args, **kwargs)
  File "C:\Users\notoraptor\mila\dev\git\theano\theano\gradient.py", line 1795, in verify_grad
    abs_tol, rel_tol)
GradientError: GradientError: numeric gradient and analytic gradient exceed tolerance:
        At position 0 of argument 2 with shape (1L, 1L, 1L, 1L),
            val1 = 0.000000      ,  val2 = 0.989321
            abs. error = 0.989321,  abs. tolerance = 0.010000
            rel. error = 1.000000,  rel. tolerance = 0.010000
Exception args:
The error happened with the following inputs:, [array([[ 1.17346799]], dtype=float32), array([[[ 0.82418805]]], dtype=float32), array([[[[ 0.47996601]]]], dtype=float32)],
The value of eps is:, None,
The out_type is:, None

----------------------------------------------------------------------
Ran 1 test in 5.110s

FAILED (errors=1)

(python2) C:\Users\notoraptor\mila\dev\git\theano>theano-cache purge
c:\users\notoraptor\mila\dev\git\theano\theano\configdefaults.py:560: UserWarning: DeprecationWarning: there is no c++ compiler.This is deprecated and with Theano 0.11 a c++ compiler will be mandatory
  warnings.warn("DeprecationWarning: there is no c++ compiler."

(python2) C:\Users\notoraptor\mila\dev\git\theano>set THEANO_FLAGS=cmodule.debug=True && nosetests -xvs theano.gpuarray.tests.test_blocksparse:BlockSparse_Gemv_and_Outer.test_sparseblockgemv_grad_1
Using cuDNN version 7001 on context None
Mapped name None to device cuda: GeForce GTX 1050 (0000:01:00.0)
test_sparseblockgemv_grad_1 (theano.gpuarray.tests.test_blocksparse.BlockSparse_Gemv_and_Outer) ... unittest.rseed is 666
unittest.rseed is 666
unittest.rseed is 666
ok

----------------------------------------------------------------------
Ran 1 test in 14.846s

OK

(python2) C:\Users\notoraptor\mila\dev\git\theano>set THEANO_FLAGS=cmodule.debug=True && nosetests -xvs theano.gpuarray.tests.test_blocksparse:BlockSparse_Gemv_and_Outer.test_sparseblockgemv_grad_1
Using cuDNN version 7001 on context None
Mapped name None to device cuda: GeForce GTX 1050 (0000:01:00.0)
test_sparseblockgemv_grad_1 (theano.gpuarray.tests.test_blocksparse.BlockSparse_Gemv_and_Outer) ... unittest.rseed is 666
unittest.rseed is 666
ERROR

======================================================================
ERROR: test_sparseblockgemv_grad_1 (theano.gpuarray.tests.test_blocksparse.BlockSparse_Gemv_and_Outer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\notoraptor\mila\dev\git\theano\theano\tensor\nnet\tests\test_blocksparse.py", line 232, in test_sparseblockgemv_grad_1
    utt.verify_grad(metaop, [b_val, h_val, W_val], mode=self.mode)
  File "C:\Users\notoraptor\mila\dev\git\theano\theano\tests\unittest_tools.py", line 93, in verify_grad
    T.verify_grad(op, pt, n_tests, rng, *args, **kwargs)
  File "C:\Users\notoraptor\mila\dev\git\theano\theano\gradient.py", line 1795, in verify_grad
    abs_tol, rel_tol)
GradientError: GradientError: numeric gradient and analytic gradient exceed tolerance:
        At position 0 of argument 2 with shape (1L, 1L, 1L, 1L),
            val1 = 0.000000      ,  val2 = 0.989321
            abs. error = 0.989321,  abs. tolerance = 0.010000
            rel. error = 1.000000,  rel. tolerance = 0.010000
Exception args:
The error happened with the following inputs:, [array([[ 1.17346799]], dtype=float32), array([[[ 0.82418805]]], dtype=float32), array([[[[ 0.47996601]]]], dtype=float32)],
The value of eps is:, None,
The out_type is:, None

----------------------------------------------------------------------
Ran 1 test in 5.454s

FAILED (errors=1)

(python2) C:\Users\notoraptor\mila\dev\git\theano>
```

I know that `GpuSparseBlockOuter` may call libgpuarray function `gpublas_sgerBatch`. It seems this function may use atomic operations (in `libgpuarray\src\gpuarray_blas_cuda_cublas.c`). Could this error be related to this ?

**Comment by nouiz** [comment]
Can you try to find a commit that cause this to start to happen? We didn't
had that before.

**Comment by notoraptor** [comment]
@nouiz From a `git bisect`, I found that the first bad commit is ba114bd68057f597d0fe8c485ff3ac6ade914b52 .

It was hard to track (because cerrtain commits are unstable and certain work with either pygpu 0.7 or 0.6), but it seems the error starts to occur only when we use pygpu 0.7. We have not this error when we use pygpu 0.6.9 with corresponding Theano code (ie. up to commit ab8c46d72300433f07d80f231c1c796c24ee6671 [with some small change to do in `gpuarray/__init__.py`], which is the one just before the first bad commit reported above).

**Comment by slefrancois** [comment]
jenkins test mac win

**Comment by slefrancois** [comment]
Mac buildbot gives CUDNN_LAUNCH_TIMEOUT errors and windows buildbot has errors, but they are note related to the current PR. I suggest merging.

**Comment by nouiz** [comment]
I think the windows error was fixed upstream. But we changed what we will do for mac. Can you remove the changes about mac from this pR?

**Comment by nouiz** [comment]
Windows failed. Can you bump the min libgpuarray version in the file .jenkins/gpuarray-branch to 0.7.2?

I think it include the fix for the windows failure.

**Comment by slefrancois** [comment]
jenkins test win

**Comment by slefrancois** [comment]
jenkins test win

**Pull request merged**
