### PR TITLE
Fix doc build

### PR DESCRIPTION
**Pull request by lamblin**

### CODE REVIEW

**Comment by abergeron** [comment]
Did you test this locally, because if so, I would merge without waiting for travis.

**Comment by abergeron** [comment]
Also, please don't create branches on the central repo, because that causes travis to build even more stuff.

**Comment by abergeron** [comment]
I did test locally and it works, so I'll merge it.

**Comment by lamblin** [comment]
@abergeron Thanks, that was a configuration mistake on that computer (the central repo was aliased to `origin`), but I killed one of the two instances of Travis before it started.

**Pull request merged**
