### PR TITLE
Function.__call__(): correct indexing variable for group of args with…

### PR DESCRIPTION
**Pull request by yzotov**
… shared memory

### CODE REVIEW

**Comment by yzotov** [comment]
I have tried to make test case but failed. I think it is really dead code because several if-else in other places of Theano prevent entering to this point. So, I think the pull request may be closed.

**Comment by nouiz** [comment]
Can you tell more on what is the dead code? If it is really dead code, it
could be great to delete it. Do you have some idea/information to share? It
was a long time since I looked at that part of the code.

thanks

**Comment by abergeron** [comment]
I had a quick look and the problem is that this line: https://github.com/Theano/Theano/pull/4982/files#diff-e1ec622313fa89e96ae691b21427788fL818

Will always be an empty loop since it iterates on an empty list and therefore no checking is performed.

**Comment by abergeron** [comment]
There is no dead code but the whole loop that does the copy is indented one level too high to do anything effectively.

Also, `i` will be defined to the last argument because of the loop over input_storage and so the copy loop will just copy the last argument a bunch of times without this fix.

**Comment by abergeron** [comment]
Finished in https://github.com/Theano/Theano/pull/6215

**Pull request closed without merging**
