### PR TITLE
remove python2x.py, fix imports associated with it

### PR DESCRIPTION
**Pull request by Inoryy**
Code changes for #4969

As far as I could tell there were only imports for `OrderedDict`, didn't find any usages for `Counter` and `DictMixin`.

~~P.S. The associated ticket says Python 2.6 support is dropped, but I see that Travis builds with that version (which fail for this PR understandably).~~

### CODE REVIEW

**Comment by nouiz** [comment]
travis is failing and this branch how have conflict (so a rebase is needed).

**Comment by nouiz** [comment]
The travis error are due to the fact that it ran before we merge the PR drop Python 2.6. When you rebase to fix the conflicts, The current travis error will disapear.

thanks.

**Comment by Inoryy** [comment]
@nouiz seems to be fixed now.

**Comment by lamblin** [comment]
Jenkins test this please

**Comment by nouiz** [comment]
jenkins failure is the random seg fault after the tests, so merging.

**Comment by nouiz** [comment]
thanks

**Pull request merged**
