### PR TITLE
Issue 4825

### PR DESCRIPTION
**Pull request by olimastro**
Adressing Issue #4825, our change is simply that if a client in the op has an Alloc, it will not apply local_useless_alloc

### CODE REVIEW

**Comment by nouiz** [comment]
pep8 failure:

/home/travis/build/Theano/Theano/theano/tensor/opt.py:1801:29: E203 whitespace before ':'
/home/travis/build/Theano/Theano/theano/tensor/opt.py:1802:63: E203 whitespace before ':'

**Comment by nouiz** [comment]
The PR look good, just the pep8 fix are needed and we can merge.

thanks.

**Comment by olimastro** [comment]
I think it is ready!

**Comment by lamblin** [comment]
Jenkins test this please

**Pull request merged**
