### PR TITLE
Fix unhashable type if shapes are list

### PR DESCRIPTION
**Pull request by fvisin**
Fix BaseAbstractConv2d to convert kernel_shape and image_shape to tuples
@lamblin

### CODE REVIEW

**Comment by nouiz** [comment]
close/reopen for travis fix

**Comment by abergeron** [comment]
Someone killed travis for some reason.  I restarted it.

**Comment by abergeron** [comment]
Or maybe not, there are two builds in the queue for this and the link is currently to the first one (which is the bad one).

**Comment by abergeron** [comment]
And it's still running with the wrong master, so I'll close/reopen again.

**Comment by nouiz** [comment]
travis seem to start correctly. I'm ok to merge when travis pass.

**Pull request merged**
