### PR TITLE
Regression FIX

### PR DESCRIPTION
**Pull request by nouiz**
Fix gh-5088

### CODE REVIEW

**Comment by nouiz** [comment]
@gvtulder @lamblin @abergeron  what do you think of that PR?

**Comment by abergeron** [comment]
I'm okay-ish.  The blocks test that was broken should not have worked with the old code that required 4d inputs (if I'm not mistaken).

Also, the assumption that there are two extra dimensions is pretty widespread in the convolution code as far as I know.  I'm not against a change of convention on this, but we would have to be careful.

**Comment by nouiz** [comment]
The old code was working for 2d and more inputs. It was supposing it was doing 2d pooling, so only worked on the last 2 dims and passed unchanged all the others and didn't care the number of extra dimensions was there.

**Comment by abergeron** [comment]
Ok for this change then.

**Comment by dwf** [comment]
Given that it did work, there may even be some client library out there using it to compute pooling shapes from 2-tuples, so this seems like a reasonable behaviour.

**Comment by nouiz** [comment]
As it already break on other software, as @dwf I think we should not change the default behavior.

**Comment by dwf** [comment]
Maybe consider adding my 1-line test case from the comments on #5088? And maybe another one for length 2 inputs?

**Comment by nouiz** [comment]
I added the test

**Comment by abergeron** [comment]
Still ok

**Comment by gvtulder** [comment]
I think part of the problem was that it worked if you used pool_2d, pool_3d, but not Pool directly.

Shouldn't you also change the default ndim in make_node?

**Comment by nouiz** [comment]
I just did so.

**Comment by gvtulder** [comment]
There are also 2's in perform, grad and c_code. (I think those are all the "2"s I found.) Of course, since you now set ndim = 2 in __init__, these methods will never have to use the default.

Can I ask: why didn't you set ndim=2 in the list of __init__ arguments?

**Comment by gvtulder** [comment]
Sorry for posting multiple comments in a row.
There are more instances of "img.dim - 2". For example, it also appears in the optimizations for the cuda/gpuarray ops. I think that if you search the patch for instances "- 2" you catch them all.

Finally, as a sort of explanation of this mess: I've had a look at the old code and found that before this patch, the only thing that worked with inputs that were not exactly 4D was the Pool.out_shape method. All other methods would always assert img.ndim == 4. The -2 default didn't change anything for 4D cases, so that seemed acceptable. I apparently didn't realize that Pool.out_shape already implicitly defined a different default.

**Comment by abergeron** [comment]
In the gpuarray ops I would leave it as-is.  I think the kernels actually count on that, or at least the C code does.

**Comment by nouiz** [comment]
I think I found all the clean up. As I changed the default I'll let this PR alone so that the tests finish faster and we can merge faster. I put the clean up in another PR:

https://github.com/Theano/Theano/pull/5092

**Comment by nouiz** [comment]
in gpuarray, I let alone some -2 that where needed by cudnn. But I removed
some that supported ndim=None. We don't support that now. (this is in the
other PR)

**Comment by nouiz** [comment]
jenkins test this

**Comment by nouiz** [comment]
jenkins error (that I restarted) also appear in other PR. So merging. The error is:

Traceback (most recent call last):
  File "/usr/local/miniconda2/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/usr/local/miniconda2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/jenkins-cpu1/workspace/Theano core/theano/tensor/tests/test_gc.py", line 92, in test_gc_never_pickles_temporaries
    assert len_pre_f == len_post_f, (len_pre_f, len_post_f)
AssertionError: (20455, 20450)

**Pull request merged**
