### PR TITLE
Flake8 for files in sandbox

### PR DESCRIPTION
**Pull request by harlouci**

### CODE REVIEW

**Comment by nouiz** [comment]
with a quick code review it seem good. But we won't merge before the python2 and 3 PR is merged. thanks.

**Comment by harlouci** [comment]
Rebase done

**Comment by nouiz** [comment]
travis fail.

**Comment by abergeron** [comment]
Yes, because this needs #3030 to be merged before.

**Comment by abergeron** [comment]
Triggering a new merge now that #3030 is merged.

**Pull request merged**
