### PR TITLE
Move C files into c_code sub-folder in every module.

### LINKED ISSUE #6047: Move C codes into a sub-folder `c_code` for each module
As suggested by @nouiz , to help not have too many files in directories, C code files could be moved into separate sub-folder `c_code` in each module. For example, `theano/gpuarray/c_code` for all C code files in `theano/gpuarray` module (as done here: https://github.com/Theano/Theano/commit/5b6d3ac7bb74ef02e86d9091c80ca00e1f5c7e6d ).

What do you think, @abergeron @lamblin ?

### PR DESCRIPTION
**Pull request by notoraptor**
Closes #6047 . All `.c` and `.h` files should have been moved to sub-folder `c_code` in every module. Let's see if Jenkins and Travis accept these changes.

@abergeron @nouiz 

NB: As these are sensitive changes, I think it won't be merged for next beta, but I prepare the work.

### CODE REVIEW

**Comment by abergeron** [comment]
I'm mostly ok with that change.  We just have to make sure that the C files are installed correctly for `pip install` and `python setup.py install` with distutils and setuptools.

**Comment by notoraptor** [comment]
@abergeron @nouiz I have just uploaded Theano beta version 0.10.0b1 to PyPI, and current `c_code` sub-folders (in `theano.gpuarray` and `theano.tensor`) are correctly included ! Check here: https://pypi.python.org/pypi/Theano/0.10.0b1

To test it, you can run DimShuffle tests, as they are now COps with C files in `c_code`:
```
nosetests -xvs theano.gpuarray.tests.test_elemwise:test_GpuDimShuffle
nosetests -xvs theano.tensor.tests.test_elemwise:test_DimShuffle
```

So C files seems to be installed correctly.

**Comment by abergeron** [comment]
Perfect then.  Do we want this for 0.10?

**Comment by nouiz** [comment]
Yes! It seem ready, so why wait. merged

**Pull request merged**
