### PR TITLE
Finish code clean up from the regression fix

### PR DESCRIPTION
**Pull request by nouiz**
To be able to merge faster gh-5090 (a regression fix), I let the code clean up in this PR.

### CODE REVIEW

**Comment by gvtulder** [comment]
These lines from the gpu opts are all filling in the ndim=None case:
https://github.com/Theano/Theano/blob/master/theano/gpuarray/dnn.py#L2081
https://github.com/Theano/Theano/blob/master/theano/gpuarray/dnn.py#L2105
https://github.com/Theano/Theano/blob/master/theano/gpuarray/dnn.py#L2144
https://github.com/Theano/Theano/blob/master/theano/sandbox/cuda/dnn.py#L3058
https://github.com/Theano/Theano/blob/master/theano/sandbox/cuda/dnn.py#L3101
https://github.com/Theano/Theano/blob/master/theano/sandbox/cuda/dnn.py#L3137

**Comment by nouiz** [comment]
You point to the master of Theano, not this PR code. I fixed them in this PR.

**Comment by gvtulder** [comment]
I don't see the changes yet (so far this PR just shows the same patches as the other PR). I guess it's better if I just let you make the changes and not comment while you're working on that.

**Comment by nouiz** [comment]
My bad. The PR with the clean up: https://github.com/Theano/Theano/pull/5093

**Pull request merged**
