### PR TITLE
[TEMP] Change documentation theme to readthedocs and add source links (0.8.X backport)

### PR DESCRIPTION
**Pull request by fvisin**
Temporary PR: opened only to run the test before backporting

### CODE REVIEW

**Comment by fvisin** [comment]
Temporary PR to run the tests on Travis. Duplicate of #4660

**Comment by fvisin** [comment]
@nouiz Travis fails to import pydot and six. What should I do? Do you want me to run the tests locally?

**Comment by nouiz** [comment]
Can you back-port the change on .travis.yml? It should fix that.

**Comment by fvisin** [comment]
Done, thanks!

**Comment by fvisin** [comment]
The PR passed all tests so I pushed the new theme to the stable branch.

**Comment by nouiz** [comment]
@slefrancois can you verify that it get updated correctly on the official web site?

**Pull request merged**
