### PR TITLE
corrected setup of d3viz

### PR DESCRIPTION
**Pull request by saatvikshah1994**
Addressed Issue-3658.
I've built and tested it with http://deeplearning.net/software/theano/library/d3viz/index.html

### CODE REVIEW

**Comment by nouiz** [comment]
If you tested it, I'll merge when travis pass and test after merge.

thanks.

**Comment by saatvikshah1994** [comment]
I ran the test locally on my machine and got the following final output. 
What should I do to correct this issue?

```======================================================================
ERROR: theano.sandbox.cuda.tests.test_type.test_unpickle_cudandarray_as_numpy_ndarray_flag0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tangy/.virtualenvs/testenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/tangy/Work/OpenSource/Theano/theano/sandbox/cuda/tests/test_type.py", line 44, in test_unpickle_cudandarray_as_numpy_ndarray_flag0
    assert_raises(ImportError, u.load)
  File "/usr/lib/python2.7/unittest/case.py", line 475, in assertRaises
    callableObj(*args, **kwargs)
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1133, in load_reduce
    value = func(*args)
  File "/home/tangy/Work/OpenSource/Theano/theano/sandbox/cuda/type.py", line 589, in CudaNdarray_unpickler
    return cuda.CudaNdarray(npa)
MemoryError: Error allocating 4 bytes of device memory (no CUDA-capable device is detected).

======================================================================
ERROR: This is a REALLY PARTIAL TEST.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tangy/.virtualenvs/testenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/tangy/Work/OpenSource/Theano/theano/tests/test_printing.py", line 86, in test_pydotprint_variables
    theano.printing.pydotprint_variables(x * 2)
  File "/home/tangy/Work/OpenSource/Theano/theano/printing.py", line 1189, in pydotprint_variables
    g.write(outfile, prog='dot', format=format)
  File "/home/tangy/.virtualenvs/testenv/local/lib/python2.7/site-packages/pydot.py", line 1696, in write
    dot_fd.write(self.create(prog, format))
  File "/home/tangy/.virtualenvs/testenv/local/lib/python2.7/site-packages/pydot.py", line 1740, in create
    self.write(tmp_name)
  File "/home/tangy/.virtualenvs/testenv/local/lib/python2.7/site-packages/pydot.py", line 1694, in write
    dot_fd.write(self.to_string())
  File "/home/tangy/.virtualenvs/testenv/local/lib/python2.7/site-packages/pydot.py", line 1461, in to_string
    graph.append( edge.to_string() + '\n' )
  File "/home/tangy/.virtualenvs/testenv/local/lib/python2.7/site-packages/pydot.py", line 900, in to_string
    edge_attr.append( attr + '=' + quote_if_necessary(value) )
TypeError: cannot concatenate 'str' and 'NoneType' objects
-------------------- >> begin captured stdout << ---------------------
The output file is available at /home/tangy/.theano/compiledir_Linux-3.13--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64/theano.pydotprint.cpu.png

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 2903 tests in 1816.046s

FAILED (SKIP=101, errors=2)```

**Comment by nouiz** [comment]
The first one is a GPU test that should have been skipped as there is no
GPU available. I'll fix that.

The second one, could be related to a bad pydot module installed. You can
ignore it, at workst you'll get a crash when using pydotprint_variables
that is deprecated. Use pydotprint() instead.

**Comment by saatvikshah1994** [comment]
Since the travis build has passed, can this be merged?

**Comment by nouiz** [comment]
I installed it and ran the d3viz tests and they passed. So it seem to also work for me.

thanks

**Pull request merged**
