### PR TITLE
Add Sort Function ( Partition )

### PR DESCRIPTION
**Pull request by aeloyq**
modified:   theano/tensor/__init__.py
	modified:   theano/tensor/sort.py
	modified:   theano/tensor/var.py

### CODE REVIEW

**Comment by aeloyq** [comment]
Hi , 
I've add function partition(argpartition) to sort.py
Function partition is a wrapper of np.partition
This function is useful when you only need to get top kth value(or its index) along a given axes.
For example it takes 10% time and same effect when you need top 10 value of a tensor with shape (16L,300000L)
First:
`a=numpy.random.randint(0,10000,[16,300000])
`x=theano.shared()
For past you should:
`y=Tensor.sort(a)[:,:10]
Now you can:
`y=Tensor.partitial(a,10-1)[:,:10]

**Comment by khaotik** [comment]
I have an old PR #5959 also utilizing `np.argpartition`. However there are a number of interface differences between the two PRs.

**Comment by aeloyq** [comment]
Thank you @khaotik  for concern i'm reading it ~
BR

**Comment by nouiz** [comment]
This PR seem a subset of https://github.com/Theano/Theano/pull/5959. Can you just use that PR until we merge it?

Otherwise, what advantage your PR have over the more complete one above?

**Pull request closed without merging**
