### PR TITLE
Fix error at exit. Do this also solve gh-3088?

### PR DESCRIPTION
**Pull request by nouiz**

### CODE REVIEW

**Comment by nouiz** [comment]
Why are we having those problems now? Do someone have an idea? I'll start a git bisect to try to find when this happen.

**Comment by nouiz** [comment]
The first commit that cause this problem: 030c7b969fef05da75abe14d19007612a60849d3

This is python23 PR. Mostly, it change the import of StringIO, copyreg, builtins and cPickle to use six and moved some six import to six.moves.

**Comment by lamblin** [comment]
It fixes the error for @yaoli as well, so I'm merging.

**Comment by nouiz** [comment]
The first commit that cause this problem: 030c7b969fef05da75abe14d19007612a60849d3

This is python23 PR. Mostly, it change the import of StringIO, copyreg, builtins and cPickle to use six and moved some six import to six.moves. Do you have any idea why change at that level could cause this problem?

**Pull request merged**
