### PR TITLE
Cudnn v7 grouped convolutions

### PR DESCRIPTION
**Pull request by affanv14**
Adds the grouped convolutions feature included in the recently released cudnn v7
tasks:

- [x] Implement cudnn v7 grouped 2d convolutions 
- [ ] Implement cudnn v7 grouped 3d convolutions

### CODE REVIEW

**Comment by notoraptor** [comment]
Hello ! Just to notice that your new code here won't work on cuDNN V6 (because `cudnnSetConvolutionGroupCount()` does not exist for versions prior to v7) !

Should we definitively drop support for all cuDNN versions prior to v7, @nouiz @abergeron ?

**Comment by affanv14** [comment]
> Hello ! Just to notice that your new code here won't work on cuDNN V6 

yes, How did I forget

**Comment by borisfom** [comment]
I think the group CUDNN7 feature can be implemented in much less invasive fashion. I don't think Theano will drop CUDNN6 right now. I will submit another PR.

**Comment by borisfom** [comment]
See https://github.com/Theano/Theano/pull/6302

**Comment by affanv14** [comment]
Well, it was discussed it would be best for the looped version of cudnn grouped convolutions be removed and use the GPUCorrMM version for cudnn < 6 . This was because by the time cudnn v8 comes out the looped would have to be taken out anyway. Also to be noted is the fact that cudnn versions have  short release cycles so the looped version would be removed very soon.

**Comment by nouiz** [comment]
@affanv14 you did what I wrote, I had forgotten that we where looping for group conv 2d already. So I di not think what I wrote would remove some feature that is currently in the master. Even if it isn't there for a long time, it is better to keep it. Especially if @borisfom did it.

As this affect the cache @borisfom is working on, I'll close this PR and let this continue in gh-6302.

@affanv14 can you make a PR to gh-6302 PR that will add the tests for group conv 3d?

**Comment by affanv14** [comment]
@nouiz Alright. Shall I make the optimizer changes for cudnn and also the tests in https://github.com/Theano/Theano/pull/6267  itself? so that once that it merged, @borisfom can then rebase.

**Comment by nouiz** [comment]
I think it will be better that you make a PR to this PR. (so mostly a PR to
boris Theano fork on the branch that this PR is based on).

Mixing them in different PR isn't great. I'll try to review/merge gh-6267
today.

**Pull request closed without merging**
