### PR TITLE
Fixes for detection of mkl for win32 with anaconda

### PR DESCRIPTION
**Pull request by lamblin**
I tested that without MKL, with MKL installed, with MKL installed and partially removed, both for a global installation and for an installation as a user, everything seemed to work.

### CODE REVIEW

**Comment by nouiz** [comment]
Except for my comment, it look good.

**Comment by lamblin** [comment]
Updated.

**Comment by nouiz** [comment]
travis fail.

**Comment by nouiz** [comment]
```
  File "/home/travis/miniconda/envs/pyenv/lib/python3.3/site-packages/theano/tensor/blas.py", line 568

    for ldflags_str.split():

                           ^

SyntaxError: invalid syntax
```

**Comment by lamblin** [comment]
Now it should work...

**Pull request merged**
