### PR TITLE
use floatX in gpuarray dnn tests

### PR DESCRIPTION
**Pull request by slefrancois**
~~Tests with float16 are successful.~~

### CODE REVIEW

**Comment by lamblin** [comment]
The failure may be due to non-determinism during the gradient computation, or just rounding error.
Since convolution is a linear operation, you can safely increase the step of the finite-difference estimate when calling `verify_grad`. I think we do it at other places for cuDNN convolution.

**Comment by slefrancois** [comment]
It passes in float32, which was hardcoded before. I wonder if we should have a precision-dependent step size, or  find one that works for all floatX?

**Comment by slefrancois** [comment]
The main conv3d tests fail in float16, apparently due to the reference C code not being implemented for float16.

**Comment by lamblin** [comment]
Maybe the solution could be to have the reference code running in float32 in that case.

**Comment by slefrancois** [comment]
With float32 refs and higher relative tolerances, the conv3d tests pass in float16. Other tests have deeper issues, such as CuDNN itself apparently not supporting float16 on those ops.

**Pull request merged**
