### PR TITLE
Disable average_exc_pad pooling for cudnn v3

### PR DESCRIPTION
**Pull request by lamblin**
See #3776

### CODE REVIEW

**Comment by f0k** [comment]
Looks good, but what about addding a sentence "NVIDIA's implementation in cuDNN v3 is broken"? Otherwise people may be wondering why it's disabled although it's in NVIDIA's API docs.

PS: Maybe nice to know: If you write "Closes #3776" instead of "See #3776" (either in the commit message or the PR description), github will automatically close the issue on merging: https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by nouiz** [comment]
This cause tests to fail with cudnn v3: 

```
======================================================================
ERROR: test_pool (theano.sandbox.gpuarray.tests.test_dnn.TestDnnInferShapes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/u/bastienf/repos/Theano/theano/sandbox/gpuarray/tests/test_dnn.py", line 517, in test_pool
    mode=params[2]
  File "/u/bastienf/repos/Theano/theano/sandbox/gpuarray/dnn.py", line 959, in __init__
    "CuDNN pooling mode 'average_exc_pad' requires at least v4")
RuntimeError: CuDNN pooling mode 'average_exc_pad' requires at least v4

======================================================================
ERROR: theano.sandbox.gpuarray.tests.test_dnn.test_pooling
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Tmp/lisa/os_v5/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/u/bastienf/repos/Theano/theano/sandbox/gpuarray/tests/test_dnn.py", line 197, in test_pooling
    f1 = theano.function([x], out1, mode=mode_with_gpu)
  File "/u/bastienf/repos/Theano/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/u/bastienf/repos/Theano/theano/compile/pfunc.py", line 526, in pfunc
    output_keys=output_keys)
  File "/u/bastienf/repos/Theano/theano/compile/function_module.py", line 1777, in orig_function
    output_keys=output_keys).create(
  File "/u/bastienf/repos/Theano/theano/compile/function_module.py", line 1457, in __init__
    optimizer_profile = optimizer(fgraph)
  File "/u/bastienf/repos/Theano/theano/gof/opt.py", line 101, in __call__
    return self.optimize(fgraph)
  File "/u/bastienf/repos/Theano/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/u/bastienf/repos/Theano/theano/gof/opt.py", line 240, in apply
    self.failure_callback(e, self, optimizer)
  File "/u/bastienf/repos/Theano/theano/gof/opt.py", line 197, in warn
    raise exc
RuntimeError: CuDNN pooling mode 'average_exc_pad' requires at least v4
-------------------- >> begin captured logging << --------------------
theano.gof.opt: ERROR: Optimization failure due to: local_pool_dnn_alternative
theano.gof.opt: ERROR: node: DownsampleFactorMax{ds=(4, 4), ignore_border=True, st=(2, 2), padding=(0, 0), mode='average_exc_pad'}(HostFromGpu(gpuarray).0)
theano.gof.opt: ERROR: TRACEBACK:
theano.gof.opt: ERROR: Traceback (most recent call last):
  File "/u/bastienf/repos/Theano/theano/gof/opt.py", line 1787, in process_node
    replacements = lopt.transform(node)
  File "/u/bastienf/repos/Theano/theano/sandbox/gpuarray/opt.py", line 141, in local_opt
    new_op = maker(node, context_name)
  File "/u/bastienf/repos/Theano/theano/sandbox/gpuarray/dnn.py", line 1401, in local_pool_dnn_alternative
    ds, stride=stride, pad=pad, mode=mode)
  File "/u/bastienf/repos/Theano/theano/sandbox/gpuarray/dnn.py", line 1163, in dnn_pool
    desc = GpuDnnPoolDesc(ws=ws, stride=stride, mode=mode, pad=pad)()
  File "/u/bastienf/repos/Theano/theano/sandbox/gpuarray/dnn.py", line 959, in __init__
    "CuDNN pooling mode 'average_exc_pad' requires at least v4")
RuntimeError: CuDNN pooling mode 'average_exc_pad' requires at least v4
```

**Comment by lamblin** [comment]
@nouiz I think that is the desired outcome: someone with cudnn v3 running the tests will know that this feature is going to be a problem.

**Comment by nouiz** [comment]
From memory, there was many tests failure. This polute the buildbot and hide other errors. If you want to keep one, we can discuss one. But I don't think there should be more then 1 such error.

Also, I would more put this as a warning, to not polute the error of tests.

**Comment by lamblin** [comment]
So, there is a total of 5 failures, 3 in the old back-end:
- `test_pool (theano.sandbox.cuda.tests.test_dnn.TestDnnInferShapes)`
- `theano.sandbox.cuda.tests.test_dnn.test_pooling`
- `theano.sandbox.cuda.tests.test_dnn.test_pooling3d`

 2 in the new back-end:
- `test_pool (theano.sandbox.gpuarray.tests.test_dnn.TestDnnInferShapes)`
- `theano.sandbox.gpuarray.tests.test_dnn.test_pooling`

Is that too much? I think we could skip the "InferShape" ones for v3 if that is important, but I would at least keep the errors for "test_pooling".

**Comment by f0k** [comment]
> So, there is a total of 5 failures

Why not skip the corresponding tests for cuDNN < v4? That would be the logical consequence. If the user doesn't have cuDNN, you skip the tests that require cuDNN, and if she/he doesn't have cuDNN v4, you skip the tests that require cuDNN v4. It should be enough to communicate the lack of features when somebody tries to actually use them, not when somebody runs the test suite.

On a side note, maybe the error should only be raised if `any(p > 0 for p in pad)` (or `max(pad) > 0`)? Without padding, `"average_exc_pad"` works fine.

> Also, I would more put this as a warning, to not polute the error of tests.

For end users, it should be an error, not just a warning, to make sure it's not used accidentally with cuDNN v3.

**Comment by lamblin** [comment]
Updated after @f0k's comments.

**Pull request merged**
