### PR TITLE
Fix allow_downcast on gpuarray

### PR DESCRIPTION
**Pull request by abergeron**
Also stop assuming that update_val will have a type in the error message.

### CODE REVIEW

**Comment by nouiz** [comment]
Also add the code as a test. I'm killing travis. (it have problems today...)

**Comment by abergeron** [comment]
Now with a test.

**Comment by nouiz** [comment]
test fail:
/home/travis/build/Theano/Theano/theano/sandbox/gpuarray/tests/test_type.py:42:1: E302 expected 2 blank lines, found 1

**Comment by abergeron** [comment]
Fixed

**Comment by abergeron** [comment]
Now passes travis.

**Pull request merged**
