### PR TITLE
Speed up scan test

### PR DESCRIPTION
**Pull request by sebastien-j**
@nouiz, @abergeron,

`test_grad_multiple_outs_some_disconnected` was taking multiple hours in DEBUG_MODE. As the test fails in that mode, I had not seen it in the logs.

### CODE REVIEW

**Comment by abergeron** [comment]
How exactly does it fail in that mode?

**Comment by nouiz** [comment]
I do not like this fix. Why it is now that slow? I do not recall such a
slow case there in the past. So maybe we should investigate which commit
changed that timming. @sebastien-j, can you use git bisect to try to find
when this test got much slower?

**Comment by sebastien-j** [comment]
@abergeron ,
```
Traceback (most recent call last):
  File "THEANO_PATH/theano/scan_module/tests/test_scan.py", line 1927, in test_grad_multiple_outs_some_disconnected
    assert cost < 0.02
AssertionError
```

@nouiz, ok, I will try to find when the test got slower.

**Comment by sebastien-j** [comment]
@abergeron ,@nouiz,

the test would have been slow from the initial working commit f208a0c613e76bc4fb89abdd6ff64e55a0afb9d3, but this was hidden by the DEBUG_MODE error fixed by pull request #2466. We can see this by cherry-picking 2777ecf5314c91b3e50615dada8310c888adc461.

**Comment by carriepl** [comment]
@sebastien-j  : Instead of forcing compile mode to be FAST_RUN, which essentially prevents us from running that test in DebugMode,  you can look into making the code run for less iterations or on less data. Right now it's training on 476 datapoints. If you reduce it, it will be faster to compute and most likely faster (in epochs) to get a low training error.

**Comment by sebastien-j** [comment]
@nouiz , @carriepl ,
The speed of the test is approximately linear in the number of data points. With 50 and 100 points, it took 2275 and 4555 seconds respectively.

Reducing the number of points doesn't seem to make the error get below 0.02 more quickly in terms of epochs. With 476, 100 and 50 points, it happened after approximately 75-85 iterations.

IN DEBUG_MODE, the error decreases very slowly. Even after 100 iterations, it is barely below its initial value.

**Comment by lamblin** [comment]
The error decreasing more slowly in DebugMode could be due to numerical optimizations not being applied, which can slow down gradient descent (for instance if units are almost saturated).

**Comment by nouiz** [comment]
I have in mind that DebugMode should return the same value as with
fast_run, but maybe with the python implementation. But I didn't double
checked that.

@sebastien-j, can you make a PR to merge the speed up? That is the most
urgent. We can continue to investigate the failure reason in parallel.

I would go with 50 datapoint. Can you disable the check_py_code at the same
time? This cuold give another speed up.

**Comment by sebastien-j** [comment]
@nouiz ,
I have already made the changes in this pull request.

**Comment by nouiz** [comment]
Ok. I merge for now.

**Pull request merged**
