### PR TITLE
Partial Revert 5ed8d9232d217ec73da28b2f9dbeb410bb9c208f

### PR DESCRIPTION
**Pull request by nouiz**
We need to test it more before merge.

### CODE REVIEW

**Comment by carriepl** [comment]
I tested this PR on the use case we discussed where the optimization PushOutScanOutput would not get applied properly which would increase memory usage *a lot*. This PR fixes the issue; the optimization is now applied correctly and memory usage is down.

**Comment by abergeron** [comment]
This passes all tests in scan_module with a GPU present

sandbox.cuda is still running.

**Comment by abergeron** [comment]
sandbox.scan_module is fine

I stopped the sandbox.cuda run and re-ran it with only for sandbox.cuda.test.test_opt, (since opt is the only file which has references to scan), and it passes.

**Comment by lamblin** [comment]
No new error in Pylearn2 either.

**Pull request merged**
