### PR TITLE
Use conda git on windows

### PR DESCRIPTION
**Pull request by slefrancois**

### CODE REVIEW

**Comment by slefrancois** [comment]
jenkins test windows

**Comment by lamblin** [comment]
Unfortunately there is a conflict since I merged #6242.

**Comment by slefrancois** [comment]
conflict resolved, I removed the parameterized commit.

**Comment by slefrancois** [comment]
jenkins test windows

**Comment by slefrancois** [comment]
jenkins test windows

**Comment by slefrancois** [comment]
git passed on windows PR

**Pull request merged**
