### PR TITLE
Allow MRG RNG shared variables to be recognised as such

### LINKED ISSUE #2668: Identify random states of MRG generators
For the moment, random states of MRG are regular matrices, either `TensorType(int32, matrix)` or `CudaNdarrayType(float32, matrix)`.
It would be useful to have a way of differenciating them from model parameters, for instance.
@bartvm proposed a tag like `.is_RNG`.
Something else that could be useful would be a weak reference to the `MRG_RandomStreams` instance that created them.

### PR DESCRIPTION
**Pull request by bartvm**
Fixes #2668.

### CODE REVIEW

**Comment by lamblin** [comment]
Thanks!
Could you add that to shared_randomstreams.RandomStreams as well, to keep the interfaces similar?

**Comment by bartvm** [comment]
@lamblin Sure, done.

**Comment by bartvm** [comment]
@lamblin 
Woops, not sure why Theano's buildbot didn't catch up on this, but I now get this error when pickling MRG RNGs:
```
TypeError: can't pickle weakref objects
```

**Comment by nouiz** [comment]
Probably there isn't any test for this. Can you add one? You can dump to a
string with cPickle.dumps().

**Pull request merged**
