### PR TITLE
Fix parameter types in ave_pool kernels, remove static_cast, add GLOBAL_MEM

### PR DESCRIPTION
**Pull request by xiaoqie**
This makes average pooling and conv3d work with OpenCL.

### CODE REVIEW

**Comment by nouiz** [comment]
jenkins test this

**Comment by abergeron** [comment]
This may conflict with https://github.com/Theano/Theano/pull/6012, so we might want to wait until that is merged.  Otherwise, good work.

**Comment by nouiz** [comment]
I just merged gh-6012. As @abergeron guessed, this caused conflict and this PR need a rebase. Can you do it?

thanks

**Comment by abergeron** [comment]
Please do a proper rebase and not a merge.

**Comment by nouiz** [comment]
I killed travis as it is overloaded and we will need it to run again after the rebase.

**Comment by xiaoqie** [comment]
I messed up this PR, I'll open a new PR.

**Pull request closed without merging**
