### PR TITLE
LogSoftmax

### PR DESCRIPTION
**Pull request by fvisin**
Work in progress to fix https://github.com/Theano/Theano/issues/3162

### CODE REVIEW

**Comment by nouiz** [comment]
I renamed the PR title, but didn't checked the code.

**Comment by fvisin** [comment]
A list of what has been done (and tested) so far:
* [X] Implementation of the first and second gradient of the Logsoftmax
    * [X] python code
    * [ ] C code
* [ ] Optimization
    * [X] fprop
    * [ ] bprop

**Comment by fvisin** [comment]
I am trying to understand how to write the C code, but it is more complicated than I expected and the documentation is not very clear (both Theano's and Numpy's I would say). I am referring to the c code of Softmax as a guideline. These are some of the lines I don't understand:
* https://github.com/fvisin/Theano/blob/b28c81c79ca44f0762f0ee5e6cbce2fefee81454/theano/tensor/nnet/nnet.py#L489-L501
    * what is sm?
    * what is this doing?
* https://github.com/fvisin/Theano/blob/b28c81c79ca44f0762f0ee5e6cbce2fefee81454/theano/tensor/nnet/nnet.py#L513-L514
    * If I am not wrong PyArray_BYTES should be the content of the ndarrray, but what is PyArray_STRIDES? I can only find tautological definitions "returns a pointer to the strides"...but I don't get what is a stride...

This would be a good start. I will keep reading and add new comments if there is something else that I don't get.

**Comment by fvisin** [comment]
I sent the comment too soon, I found this definition: 
`An array of integers providing for each dimension the number of bytes that must be skipped to get to the next element in that dimension.` 

It is still not completely clear though:
* is it right that when the ndarray does not contain structured items (e.g., is an array of ints, it does not contain lists or other ndarrays) every element (dimension) of stride corresponds to the size in bytes of the dtype of the ndarray (in my example, `stride==dtype(int)`)?
* in the case of `[[1, 2, 3], [4]]`, what is the value of stride? If you consider `[1, 2, 3]` stride should be `3 * sizeof(int)`, but if you consider `[4]` it should be `sizeof(int)`? I guess I am missing something trivial, but I am tired and this new unreadable font is driving me crazy. I'll try to reverse engineer the code, it is probably easier.

**Comment by abergeron** [comment]
The code looks ok, but we still have to debug why it doesn't work on Travis.  It works locally.

**Comment by nouiz** [comment]
I think travis tests fail due when mode=FAST_COMPILE and when floatX=float32.

Is the opt registered in FAST_COMPILE? I think you can make the test run by forcing 'FAST_COMPILE, to be sure the opt will be applied.

**Comment by abergeron** [comment]
Yes, the tests pass now!

**Comment by fvisin** [comment]
Great!!

**Pull request merged**
