### PR TITLE
Test files have been modified in order to respect the flake8 style.

### PR DESCRIPTION
**Pull request by ChihebTrabelsi**

### CODE REVIEW

**Comment by abergeron** [comment]
You should remove the fixed files from test_flake8.py (in the whitelist).

**Comment by abergeron** [comment]
The travis failure was due to the brief master breakage.  close/reopen to re-run travis.

**Comment by nouiz** [comment]
I killed travis

**Comment by nouiz** [comment]
travis is failing:

/home/travis/build/Theano/Theano/theano/tests/__init__.py:3:5: F401 'TheanoNoseTester' imported but unused

/home/travis/build/Theano/Theano/theano/tests/__init__.py:3:5: F401 'main' imported but unused

Don't remove the \__init__.py file from the whitelist. This should fix travis.

**Pull request merged**
