### PR TITLE
In the meta optimizer, try to fix broadcast pattern change.

### PR DESCRIPTION
**Pull request by nouiz**
see: [theano-users] Exception "Incompatible broadcastable dimensions" during meta-optimization of GpuConv

### CODE REVIEW

**Comment by lamblin** [comment]
I think the underlying optimizers should be fixed instead, so that the calls to `outputs = opt.transform(node)` in the loop succeed.

**Comment by nouiz** [comment]
I changed the each local opt as suggested. I also added some other fix that caused tests to crash when run with this PR. They are related to the cmodule key and CDataType.

They tests are continuing to run here.

**Comment by nouiz** [comment]
All tests passed here.

**Comment by abergeron** [comment]
Also even if the tests passed locally on your machine they still failed badly on travis.  There might be some key difference here.  I wouldn't merge in the current state.

**Comment by nouiz** [comment]
I fixed both problems.

**Pull request merged**
