### PR TITLE
Use randint() instead of random_integers() in the tests.

### PR DESCRIPTION
**Pull request by abergeron**
This should be a comprehensive for the warnings in numpy 1.11.

### CODE REVIEW

**Comment by nouiz** [comment]
travis fail.

**Comment by slefrancois** [comment]
jenkins test this

**Comment by slefrancois** [comment]
jenkins test this please

**Comment by slefrancois** [comment]
Jenkins test this please

**Comment by slefrancois** [comment]
Jenkins test this please

**Comment by slefrancois** [comment]
jenkins test this please

**Pull request merged**
