### PR TITLE
Update printing and plotting sections in tutorials

### PR DESCRIPTION
**Pull request by cangermueller**
Update printing and plotting sections in:
* tutorial/printing_drawing.txt
* tutorial/shape_info.txt
* crei2013/advanced_theano.txt
* cifarSC2011/advanced_theano.txt

Same as #2822, but covers all tutorials mentioned in #2711. I checked html files after running `scripts/docgen.py`.

### CODE REVIEW

**Comment by nouiz** [comment]
This PR need a rebase.

**Comment by nouiz** [comment]
I didn't check the generated doc, but I think it is good. @lamblin do you want to review it? If I don't get new 2 days after the rebase, I'll merge it.

**Comment by cangermueller** [comment]
To rebase to master, I had to create a new branch and submit a new PR (#2850). Sorry for the mess: the next time, I will not forget to rebase to master before applying any changes.

**Comment by nouiz** [comment]
After rebase, you do not need to make a new PR, can you :+1: 

git push -f origin your_branch

this will update the current PR. If the rebase is complicated and you want to be safe, you can make a new PR, but for simple stuff, this isn't needed.

I'll close this PR.

**Comment by cangermueller** [comment]
Thanks for the hint about the `-f` force flag!

**Pull request closed without merging**
