### PR TITLE
Speeding up local_gpua_careduce

### PR DESCRIPTION
**Pull request by Sentient07**
Made this [suggestion](https://groups.google.com/forum/#!topic/theano-dev/CyudghMklcE)

### CODE REVIEW

**Comment by nouiz** [comment]
Can you show the profile just before this PR and with this PR?

**Comment by Sentient07** [comment]
Current master - http://pastebin.com/bEbzQ8se
Over this branch - http://pastebin.com/C4sNtRkj

**Comment by nouiz** [comment]
closing/reopening to trigger travis.

**Comment by nouiz** [comment]
ok to merge when travis pass.

**Pull request merged**
