### PR TITLE
[Bug] Revert dot22->gemm optimization back to dot22->dot22scalar

### PR DESCRIPTION
**Pull request by carriepl**
The previously done change from dot22->dot22scalar to dot22->gemm had the effect, under some not-fully-understood circumstances,  of duplicating certain Scan nodes and preventing certain optimizations (such as ScanSaveMem) on the duplicates. The result was a drastic increase in memory usage.

The issue should be investigated further and tests added to try and ensure this doesn't occur again but, in the mean time, this fixes this issue which is preventing from people from using the latest version.

### CODE REVIEW

**Comment by nouiz** [comment]
gemm do not have an infer_shape. Could you try rapidly if adding it would solve the problem?

**Comment by nouiz** [comment]
I'm ok with that PR. Anyone can merge when travis pass.

**Comment by carriepl** [comment]
I currently testing with the infer_shape in gemm. So far it seems to work without any issue. I'll keep testing to make sure.

**Comment by carriepl** [comment]
@nouiz : in the optimization that does the replacement of dot22 with dot22scalar, the comment?

**Comment by nouiz** [comment]
for the comment, yes, in the opt.

**Comment by carriepl** [comment]
Nevermind what I said about infer_shape. The issue is still there.
I've added the comment @nouiz requested.

**Pull request merged**
