### PR TITLE
Fix test due to new error type.

### PR DESCRIPTION
**Pull request by nouiz**

### CODE REVIEW

**Comment by lamblin** [comment]
A CPU test expects an IndexError (test_join_matrixC_negative_axis at https://github.com/Theano/Theano/blob/master/theano/tensor/tests/test_basic.py#L3681), so it is failing now. I'm not sure which error is better, but we should be consistent in the tests.

**Comment by abergeron** [comment]
This changes IndexError to ValueError, so it can't fix the test you are talking about.

**Comment by abergeron** [comment]
In fact I'd say the first commit broke the test.

**Comment by nouiz** [comment]
I think the error should be ValueError. IndexError mean there is a problem during indexing. This is also what numpy does:

```
$python
Enthought Canopy Python 2.7.6 | 64-bit | (default, Apr 11 2014, 13:46:04) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-52)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
n>>> numpy.sum([1,2], axis=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Tmp/lisa/os_v3/canopy/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 1709, in sum
    out=out, keepdims=keepdims)
  File "/Tmp/lisa/os_v3/canopy/lib/python2.7/site-packages/numpy/core/_methods.py", line 25, in _sum
    out=out, keepdims=keepdims)
ValueError: 'axis' entry is out of bounds

```

I updated this PR to fix this tests.

**Comment by abergeron** [comment]
You might have to change that too: https://github.com/Theano/Theano/blob/master/theano/sandbox/gpuarray/basic_ops.py#L862

**Comment by nouiz** [comment]
done

**Comment by bouthilx** [comment]
Actually, I looked at Numpy to decide it was an IndexError

**Comment by nouiz** [comment]
done

**Comment by bouthilx** [comment]
Actually, I looked at Numpy to decide it was an IndexError
```python
np.concatenate([np.zeros((20,20)),np.zeros((20,20))], axis=3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: axis 3 out of bounds [0, 2)
```

**Comment by nouiz** [comment]
How you tested it?

**Comment by bouthilx** [comment]
@nouiz It seems numpy.concatenate doesn't give same error as numpy.sum

**Comment by nouiz** [comment]
That seem what happened. But Join call numpy.concatenate. I don't like that
error type, but anyway, it is better to stay as numpy. I'll change it again.

**Comment by nouiz** [comment]
I updated the PR again.

**Pull request merged**
