### PR TITLE
Updated numpy as np #4218

### PR DESCRIPTION
**Pull request by Amrithasuresh**
@nouiz 

I have updated the files https://github.com/Theano/Theano/issues/4218.

@Sentient07 It seems to me that I have updated the files you have mentioned in the issue. Can you please check and update it?

Thank you.

### CODE REVIEW

**Comment by nouiz** [comment]
Remove the merge commit. This ban be done by a rebase. If the Theano central repository is called central, it would give those command:


git remote update central/master
git rebase -i central/master

**Comment by Sentient07** [comment]
@Amrithasuresh Sorry, I am busy and didn't have time for review. I had a quick look and it seems good to me. Fred has given a comment, and with that I think this PR is fine. Great job! Thanks

**Comment by Amrithasuresh** [comment]
@nouiz I tried removing the merge commit and did it. But, I could not update with the above commands.  I can fix it by tomorrow.

**Comment by nouiz** [comment]
Now the merge commit is gone. I'll review it completly

**Comment by nouiz** [comment]
seem good, so merging. thanks.

**Pull request merged**
