### PR TITLE
Removing _op_use_c_code attribute

### PR DESCRIPTION
**Pull request by Faruk-Ahmed**
reference #4317 

This is one fix in one place. Others are pending, I'm looking for feedback right now if what I'm doing looks right.

### CODE REVIEW

**Comment by nouiz** [comment]
/home/travis/build/Theano/Theano/theano/gof/link.py:827:43: E128 continuation line under-indented for visual indent
/home/travis/build/Theano/Theano/theano/gof/link.py:828:43: E128 continuation line under-indented for visual indent
/home/travis/build/Theano/Theano/theano/gof/link.py:829:43: E128 continuation line under-indented for visual indent

- To fix the IfElse op inherit from Op instead of PureOp and rename make_thunk to make_py_thunk.
- For Scan, add a new make_py_thunk method that call Scan.make_thunk. Add in make_thunk a new parameter python_exec that default to False. In make_py_thunk, give the True value. In ScanOp.make_thunk, in the try...except, if python_exec if True, raise an theano.gof.cmodule.MissingGXX error.

**Comment by ballasn** [comment]
@Faruk-Ahmed, there are some flake8 issue you can fix, @nouiz the modifications seem to create some issues for a few tests (tensor.tests.test_blas.t_gemm, tests.test_mpi.test_mpi_schedule for instance) but I am not sure why?

**Comment by nouiz** [comment]
Some travis failure:

```
/home/travis/build/Theano/Theano/theano/tensor/opt.py:6330:36: E128 continuation line under-indented for visual indent
/home/travis/build/Theano/Theano/theano/tensor/opt.py:6331:36: E128 continuation line under-indented for visual indent
/home/travis/build/Theano/Theano/theano/tensor/opt.py:6332:36: E128 continuation line under-indented for visual indent
```

For the other errors, it was faster to do the fix then explain. I rebased this PR. Continue from this branch: https://github.com/nouiz/Theano/tree/Faruk-Ahmed-use_cxx_flag

**Comment by nouiz** [comment]
I continued this PR in this branch: https://github.com/Theano/Theano/pull/5073

**Pull request closed without merging**
