### PR TITLE
Fix tests in DebugMode with DNN convolutions

### PR DESCRIPTION
**Pull request by lamblin**

### CODE REVIEW

**Comment by nouiz** [comment]
ok to merge when travis pass.

**Comment by lamblin** [comment]
I'll add the fix & test for the pooling descriptor here as well.

**Comment by lamblin** [comment]
Apparently, we are not using the pooling descriptor at all any more in the new back-end, and trying to force the old interface results in errors in shape inference. So I'll fix it but not include a test for that, if it's OK.
I'll check the new back-end as well.

**Comment by nouiz** [comment]
Don't check the new interface. Harm is removing the descriptor.

**Comment by nouiz** [comment]
I merge this PR as this fix stuff for the release.

**Pull request merged**
