### PR TITLE
Simplify comparisons

### PR DESCRIPTION
**Pull request by sieben**

### CODE REVIEW

**Comment by nouiz** [comment]
we can merge when travis pass.

**Comment by nouiz** [comment]
One test about flake8 is failing:

```
/home/travis/miniconda2/envs/pyenv/lib/python2.6/site-packages/theano/tensor/basic.py:435:21: E127 continuation line over-indented for visual indent

/home/travis/miniconda2/envs/pyenv/lib/python2.6/site-packages/theano/tensor/basic.py:435:21: W503 line break before binary operator
```

**Comment by sieben** [comment]
@nouiz putting (-10) solved it.

**Comment by nouiz** [comment]
thanks

**Pull request merged**
