### PR TITLE
Fixed the docstring for the scan_opt.

### PR DESCRIPTION
**Pull request by caglar**
Fixes the docstring for the scan optimizations.

### CODE REVIEW

**Comment by nouiz** [comment]
It seem good for me. @carriepl is it ok with you?

**Comment by carriepl** [comment]
The first one is fine.
The second one should be something like : A global optimizer for pushing out the variables inside the scan that depend  only on constants and sequences.

**Comment by nouiz** [comment]
@caglar can you finish this and rebase it?

**Comment by nouiz** [comment]
Pop. This is small think to finish. Could you finish this? thanks.

**Comment by caglar** [comment]
@nouiz, OK fixed it.

**Comment by nouiz** [comment]
thanks

**Pull request merged**
