### PR TITLE
Decoding nvcc outputs in correct encoding.

### PR DESCRIPTION
**Pull request by cai-lw**
`nvcc` calls `cl` (Visula Studio C/C++ compiler), and `cl` outputs are in "current ANSI console codepage" (see [Visual Studio Documentation](https://msdn.microsoft.com/en-us/library/xwy0e8f2%28v=vs.120%29.aspx)). If the encoding is not UTF8 and the output contains non-ASCII characters (very likely to happen if the VS installation is in Asian languages), the default `decode()` will result in an exception.
There had been an issue #3551 that reported the problem, but remained untreated for long.
This pull request fixed the problem by adding a function that can decode in specified encoding and compatible with both Python 2 and 3, and detecting encodings of stdout and stderr.

### CODE REVIEW

**Comment by nouiz** [comment]
Thanks for the fix. I like the code, it is clean.

We try to make a release very close. So I'm not 100% sure we can merge this without too much chance to break other stuff. I'm ok to merge this, but I would like other Theano dev to agree to merge before the release. Otherwise, it should be in a few days.

**Comment by cai-lw** [comment]
@nouiz The first commit is not working because `p.stdout` and `p.stderr` do not derive from `io.TextIOBase` thus don't have the `encoding` attribute. I am using `locale.getpreferredencoding()` to detect encoding now. It should work in most cases, if not all.

**Comment by nouiz** [comment]
Travis have this error:

/home/travis/build/Theano/Theano/theano/compat/__init__.py:71:1: W293 blank line contains whitespace

I'm don't think we will merge this before the release. Just to be sure we don't break windows/mac. But otherwise, I think it is good. @lamblin @abergeron

**Comment by nouiz** [comment]
Seem good. Just for safety, we will merge after the release that is planned Monday.

**Comment by nouiz** [comment]
thanks

**Comment by lamblin** [comment]
Travis now passes, and the release is over, so I'm merging.
Thanks!

**Comment by maomao2991** [comment]
Thank you very much! ! It really halpful, solving the issue had troubled me for one night.

**Pull request merged**
