### PR TITLE
Change documentation theme to readthedocs and add source links (0.8.X backport)

### PR DESCRIPTION
**Pull request by fvisin**

### CODE REVIEW

**Comment by abergeron** [comment]
We usually don't handle backports with PRs, but rather with cherry-picking and pushing to the release branch.

I'll let @lamblin decide what to do here.

**Comment by lamblin** [comment]
A PR is fine, but we should click on "squash and merge" instead of just "merge" to limit the number of commits added to the old branch.

**Comment by slefrancois** [comment]
Travis seems to break with errors like "no module named six"

**Comment by abergeron** [comment]
Yes because we had to fix the travis script on the master but the 0.8 branch hasn't got the fix.  One more reason not to go with PRs.

**Comment by fvisin** [comment]
Ok, I will cherrypick, squash and push once the other PR gets merged.

**Comment by fvisin** [comment]
Reopening to run the tests.

**Pull request closed without merging**
