### PR TITLE
FunctionGraph crash

### PR DESCRIPTION
**Pull request by nouiz**
fix gh-2976, need a test before merging.

### CODE REVIEW

**Comment by nouiz** [comment]
I added a test. It should work with python3. The pickle load problem fix wasn't complicated.

**Comment by lamblin** [comment]
The new test fails both with Python 3.6 and 3, with:
```
AttributeError: 'module' object has no attribute 'OrderedDict'
```

**Comment by nouiz** [comment]
The problem is only with python 2.6 not with python 3. I skip it with python 2.6 and older.

**Comment by nouiz** [comment]
travis passed.

**Comment by nouiz** [comment]
Mereged wrong PR by mistake. But it already passed a review. @lamblin can you confirm in a comment you are good with this merge?

**Comment by lamblin** [comment]
Yes, it's fine for me.

**Pull request merged**
