### PR TITLE
Scan grad speedup bug

### PR DESCRIPTION
**Pull request by carriepl**

### CODE REVIEW

**Comment by abergeron** [comment]
This fixes the problem with David's code I suppose?

**Comment by carriepl** [comment]
Yes

**Comment by carriepl** [comment]
I can't guarantee the test case I've included is 100% identical but it has the same symptom (IndexError in scan.grad()) and is solved by the same fix.

**Comment by abergeron** [comment]
It looks ok to me.  I'm ok to merge even if it doesn't completely fix David's problem since it does fix a problem.

**Pull request merged**
