### PR TITLE
Fix the no_cycle test errors by applying manual surgery to shape_opt_cycle.pkl

### LINKED ISSUE #2456: new scan error in the daily buildbot
```
======================================================================
ERROR: test_no_cycle (theano.tensor.tests.test_opt.test_shapeoptimizer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/part/01/Tmp/nightly_build/Theano/theano/tensor/tests/test_opt.py", line 3280, in test_no_cycle
    theano.function(**fn_args)
  File "/part/01/Tmp/nightly_build/Theano/theano/compile/function.py", line 265, in function
    profile=profile)
  File "/part/01/Tmp/nightly_build/Theano/theano/compile/pfunc.py", line 511, in pfunc
    on_unused_input=on_unused_input)
  File "/part/01/Tmp/nightly_build/Theano/theano/compile/function_module.py", line 1545, in orig_function
    on_unused_input=on_unused_input).create(
  File "/part/01/Tmp/nightly_build/Theano/theano/compile/function_module.py", line 1250, in __init__
    optimizer_profile = optimizer(fgraph)
  File "/part/01/Tmp/nightly_build/Theano/theano/gof/opt.py", line 90, in __call__
    return self.optimize(fgraph)
  File "/part/01/Tmp/nightly_build/Theano/theano/gof/opt.py", line 81, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/part/01/Tmp/nightly_build/Theano/theano/gof/opt.py", line 205, in apply
    self.failure_callback(e, self, optimizer)
  File "/part/01/Tmp/nightly_build/Theano/theano/gof/opt.py", line 168, in warn
    raise exc
TypeError: ('The type of the replacement must be the same as the type of the original Variable.', do_while{cpu,scan_fn}.4, do_while{cpu,scan_fn}.4, TensorType(float32, matrix), CudaNdarrayType(float32, matrix), 'remove_constants_and_unused_inputs_scan')
-------------------- >> begin captured logging << --------------------
theano.gof.opt: ERROR: Optimization failure due to: remove_constants_and_unused_inputs_scan
theano.gof.opt: ERROR: TRACEBACK:
theano.gof.opt: ERROR: Traceback (most recent call last):
  File "/part/01/Tmp/nightly_build/Theano/theano/gof/opt.py", line 1525, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/part/01/Tmp/nightly_build/Theano/theano/gof/toolbox.py", line 258, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/part/01/Tmp/nightly_build/Theano/theano/gof/fg.py", line 467, in replace
    raise TypeError("The type of the replacement must be the same as the type of the original Variable.", r, new_r, r.type, new_r.type, str(reason))
TypeError: ('The type of the replacement must be the same as the type of the original Variable.', do_while{cpu,scan_fn}.4, do_while{cpu,scan_fn}.4, TensorType(float32, matrix), CudaNdarrayType(float32, matrix), 'remove_constants_and_unused_inputs_scan')

theano.gof.opt: ERROR: SeqOptimizer apply remove_constants_and_unused_inputs_scan
theano.gof.opt: ERROR: Traceback:
theano.gof.opt: ERROR: Traceback (most recent call last):
  File "/part/01/Tmp/nightly_build/Theano/theano/gof/opt.py", line 195, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/part/01/Tmp/nightly_build/Theano/theano/gof/opt.py", line 81, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/part/01/Tmp/nightly_build/Theano/theano/gof/opt.py", line 1594, in apply
    nb += self.process_node(fgraph, node)
  File "/part/01/Tmp/nightly_build/Theano/theano/gof/opt.py", line 1533, in process_node
    self.failure_callback(e, self, repl_pairs, lopt)
  File "/part/01/Tmp/nightly_build/Theano/theano/gof/opt.py", line 1394, in warn_inplace
    return NavigatorOptimizer.warn(exc, nav, repl_pairs, local_opt)
  File "/part/01/Tmp/nightly_build/Theano/theano/gof/opt.py", line 1384, in warn
    raise exc
TypeError: ('The type of the replacement must be the same as the type of the original Variable.', do_while{cpu,scan_fn}.4, do_while{cpu,scan_fn}.4, TensorType(float32, matrix), CudaNdarrayType(float32, matrix), 'remove_constants_and_unused_inputs_scan')

theano.gof.opt: ERROR: SeqOptimizer apply <theano.gof.opt.EquilibriumOptimizer object at 0xa1920f90>
theano.gof.opt: ERROR: Traceback:
theano.gof.opt: ERROR: Traceback (most recent call last):
  File "/part/01/Tmp/nightly_build/Theano/theano/gof/opt.py", line 195, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/part/01/Tmp/nightly_build/Theano/theano/gof/opt.py", line 81, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/part/01/Tmp/nightly_build/Theano/theano/gof/opt.py", line 1783, in apply
    gopt.apply(fgraph)
  File "/part/01/Tmp/nightly_build/Theano/theano/gof/opt.py", line 205, in apply
    self.failure_callback(e, self, optimizer)
  File "/part/01/Tmp/nightly_build/Theano/theano/gof/opt.py", line 168, in warn
    raise exc
TypeError: ('The type of the replacement must be the same as the type of the original Variable.', do_while{cpu,scan_fn}.4, do_while{cpu,scan_fn}.4, TensorType(float32, matrix), CudaNdarrayType(float32, matrix), 'remove_constants_and_unused_inputs_scan')

--------------------- >> end captured logging << ---------------------
```

### PR DESCRIPTION
**Pull request by abergeron**
Fixes #2456

### CODE REVIEW

**Comment by nouiz** [comment]
I think it is better to have done a manual surgery instead of removing the test. So I merge as it fix tests.

@lamblin can you confirm you are also ok with this? It was a strange case, so having more feedback is good.

**Comment by lamblin** [comment]
The main question is: would the patched pkl still be useful to detect the original issue. If it is not, then let's remove the test itself.
The way to check that would be to revert the fix in https://github.com/Theano/Theano/pull/1549 and see if the test fails, like it should.

**Comment by abergeron** [comment]
As far as I know it should still be useful.  The fix I did was to wrap one of the inner outputs of the scan in a HostFromGpu.  If I'm not mistaken the problem this tests was caused by shape inference somewhere.

**Comment by nouiz** [comment]
You are right, but I think making sure the change still trigger the bug is
good. It was a complicated case and small change was just making the error
disapear.

**Pull request merged**
