### PR TITLE
Cusolver using Cholesky decomposition for symmetric matrices

### PR DESCRIPTION
**Pull request by tfjgeorge**
@slefrancois 

I had to add a function similar to the one provided by scikit-cuda to wrap the call to cusolverDnSpotrs from libcusolver.

Maybe @abergeron should also take a look at this ?

For reference here are some timings for 2000 calls to solve with A with shape (150, 150) and b with shape (150, 5) (time in seconds)

    ('symmetric', 1.2224421501159668)
    ('general', 3.972813129425049)

### CODE REVIEW

**Comment by slefrancois** [comment]
jenkins test this

**Comment by slefrancois** [comment]
fixes #5397

**Comment by slefrancois** [comment]
Looks good at a glance, but I would like a review from @abergeron

**Comment by slefrancois** [comment]
jenkins test this

**Comment by slefrancois** [comment]
jenkins test this

**Comment by slefrancois** [comment]
@tfjgeorge, please check the jenkins errors on the custom cusolver objects.

**Comment by tfjgeorge** [comment]
I am using the github version of scikit cuda and jenkins is probably using
the last release. To fix this I could add the missing method directly in
linalg.py as I did for cusolverDnSpotrs

**Comment by slefrancois** [comment]
That's a good point, I actually encountered this problem, the current scikit-cuda release is missing references to cusolver in CUDA 8.0. I'll just install the dev version of scikit, we shouldn't change our code for a version incompatibility.

Maybe put a check where it warns if the old scikit is present is needed for the custom routine.

**Comment by slefrancois** [comment]
jenkins test this

**Comment by slefrancois** [comment]
The code looks good, but I recommend we add a version check for scikit-cuda which warns that CUDA 8 requires scikit-cuda >= 0.5.2.

**Comment by tfjgeorge** [comment]
@slefrancois I just added the required warning

**Comment by slefrancois** [comment]
looks good, jenkins test this

**Pull request merged**
