### PR TITLE
Device swap for compiled function.

### PR DESCRIPTION
**Pull request by abergeron**
This still needs testing, but I'm making a PR for feedback on the code and interface.

### CODE REVIEW

**Comment by nouiz** [comment]
pep8 error:

/home/travis/miniconda2/envs/pyenv/lib/python2.6/site-packages/theano/gof/graph.py:848:9: E731 do not assign a lambda expression, use a def

/home/travis/miniconda2/envs/pyenv/lib/python2.6/site-packages/theano/gof/graph.py:850:9: E731 do not assign a lambda expression, use a def

**Comment by abergeron** [comment]
I've fixed most of the things. For the other ones I replied to the comments.

**Comment by nouiz** [comment]
travis fail:

/home/travis/miniconda2/envs/pyenv/lib/python2.6/site-packages/theano/compile/function_module.py:652:1: E122 continuation line missing indentation or outdented

**Comment by nouiz** [comment]
I need to test this before merging. This also need doc somewhere on the web site. What about adding this to the multi-gpu doc? If you like that, I can merge after testing this.

**Comment by abergeron** [comment]
This doesn't currently work and will not be worked on for the forseeable future.

**Pull request closed without merging**
