### PR TITLE
[BUG, TEST] Fix Sng handling of nan and fix related test

### PR DESCRIPTION
**Pull request by nouiz**
this fix 2 tests in the buildbot in debugmode

theano-nose theano/tensor/tests/test_basic.py:test_comparison.test_{isclose,allclose}

### CODE REVIEW

**Comment by abergeron** [comment]
Does this work on GPU?  I know cuda has isnan() but I don't think it has the NAN define.

**Comment by nouiz** [comment]
I added a commit to test that. This shown weakness in the new back-end in comparison with nan. I fixed them at the same time.

**Comment by abergeron** [comment]
Ok with @lamblin 's comment.

**Comment by nouiz** [comment]
done

**Pull request merged**
