### PR TITLE
Update test_hessian_bug_grad_grad_two_scans to run faster

### PR DESCRIPTION
**Pull request by carriepl**
This PR modifies the test to rely on a simpler graph and avoid structures which slow down the optimization phase considerably. The new test fails in the same way as the original did before PR #1614 fixed the corresponding bug.

The original test was timed by @sebastien-j to take ~2 hours in DebugMode (don't know if it was timed with patience=3 or patience=default). It now takes ~2 minutes in DebugMode with patience=3.

### CODE REVIEW

**Comment by sebastien-j** [comment]
@carriepl,
this test previously took a bit more than 30 minutes in DebugMode with patience=3.

**Comment by carriepl** [comment]
Ok, good to know.

**Comment by carriepl** [comment]
@nouiz, would you mind having a look?

**Comment by nouiz** [comment]
Good I merge now.

**Pull request merged**
