### PR TITLE
change macro names

### PR DESCRIPTION
**Pull request by affanv14**
fix https://github.com/Theano/Theano/issues/5610

### CODE REVIEW

**Comment by nouiz** [comment]
jenkins test this

**Comment by abergeron** [comment]
Make sure to update the docs to match.

**Comment by nouiz** [comment]
There is two (probably related) error during gpu tests:

http://darjeeling.iro.umontreal.ca:8080/job/Theano_gpu/1018/testReport/theano.gpuarray.tests/test_pool/test_pool2d/

**Comment by affanv14** [comment]
I checked the docs and all of the occurrences are in the same format i.e DTYPE_{INPUT,OUTPUT}_N.
So I don't think there are any changes to make in the docs.

**Comment by nouiz** [comment]
jenkins test this

**Comment by nouiz** [comment]
we can ignore travis error. It was not related and is fixed upstream. When jenkins pass, we can merge.

**Pull request merged**
