### PR TITLE
Python 3.7 compatibility: Regenerate scan_perform.c with more recent cython.

### PR DESCRIPTION
**Pull request by twiecki**
Attempt to fix https://github.com/Theano/Theano/issues/6626.

I couldn't really test this as the unittests passed fine even on Python 3.7.

### CODE REVIEW

**Comment by ColCarroll** [comment]
The PyMC3 test suite appears to fail on Python 3.7 (I haven't confirmed this). Perhaps test there?

**Comment by twiecki** [comment]
Turns out I ran the test suite wrong and now confirmed that theano tests do not pass in python 3.7 without this, but do pass with this fix.

**Comment by abergeron** [comment]
This looks good.

I'm curious, did you have to apply the numpy api patch or did cython finally fixed their binding?

**Comment by nouiz** [comment]
When you ran the tests, was it only on CPU or it would have also tested GPU?

**Comment by twiecki** [comment]
Only on CPU.

**Comment by nouiz** [comment]
Ok. So not enough to support it officially.

Le ven. 14 sept. 2018 03:48, Thomas Wiecki <notifications@github.com> a
écrit :

**Comment by abergeron** [comment]
From my limited tests before, that was the only thing missing.  But we could also add it to the buildbots to see if it works.

**Comment by twiecki** [comment]
@abergeron That'd be great.

**Comment by springcoil** [comment]
@twiecki How did you figure out all of this C stuff?

**Comment by twiecki** [comment]
This is just a cython recompilation of the .pyx file.

**Comment by springcoil** [comment]
Ahh - I thought you did it manually :)

**Pull request merged**
