### PR TITLE
Numpy imports

### PR DESCRIPTION
**Pull request by kvmanohar22**
Changed imports of numpy to one common form of `import numpy as np` in `Theano/theano/tensor/*` files

### CODE REVIEW

**Comment by nouiz** [comment]
travis have at least those errors that come from that PR.

To make sure you fix all of them run nosetest theano/tests/test_flake8.py before updating this PR.

thanks

```
/home/travis/build/Theano/Theano/theano/tensor/basic.py:1260:33: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/basic.py:1503:33: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/basic.py:1506:62: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/basic.py:3088:46: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/basic.py:5065:27: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/blas.py:136:5: F401 'numpy' imported but unused

/home/travis/build/Theano/Theano/theano/tensor/elemwise.py:512:43: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/elemwise.py:513:43: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/elemwise.py:787:38: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/elemwise.py:788:38: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/elemwise.py:1456:48: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/elemwise.py:1487:37: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/subtensor.py:1393:33: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/Conv3D.py:623:17: E128 continuation line under-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/ConvTransp3D.py:389:17: E128 continuation line under-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/abstract_conv.py:1240:35: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/abstract_conv.py:1242:35: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/abstract_conv.py:1455:35: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/abstract_conv.py:1457:35: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/blocksparse.py:212:62: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/conv.py:760:32: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/conv.py:781:31: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/conv.py:812:39: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/conv.py:813:39: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/nnet.py:625:32: E128 continuation line under-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_blocksparse.py:46:36: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_blocksparse.py:71:29: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_blocksparse.py:73:29: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_blocksparse.py:121:62: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_conv.py:112:39: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_conv.py:113:39: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_conv3d2d.py:78:39: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_corr.py:84:40: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_corr.py:85:40: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_corr.py:113:36: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_corr.py:114:36: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_corr3d.py:86:40: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_corr3d.py:87:40: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_corr3d.py:115:36: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_corr3d.py:116:36: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_corr3d.py:117:36: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_neighbours.py:332:35: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_neighbours.py:346:38: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_neighbours.py:358:38: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_nnet.py:134:36: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_nnet.py:136:35: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_nnet.py:200:31: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_nnet.py:1623:25: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_nnet.py:1664:31: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/nnet/tests/test_nnet.py:1673:36: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_elemwise.py:170:30: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_elemwise.py:174:30: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_elemwise.py:593:31: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_elemwise.py:608:31: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_elemwise.py:660:31: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_elemwise.py:665:31: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_elemwise.py:701:30: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_elemwise.py:703:30: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_elemwise.py:928:45: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:2514:30: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:2873:27: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:2878:44: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:2883:27: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:2888:44: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:2893:27: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:2898:44: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:2903:27: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:2912:27: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:2921:27: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:2926:44: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:2930:27: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:2939:27: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:2948:27: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:2953:44: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:2957:27: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:2969:27: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:2981:27: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:2989:44: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:2993:27: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:3002:29: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:3005:29: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:3020:39: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:4676:37: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:4785:29: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:4808:29: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:4837:29: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:4876:29: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:4901:29: E127 continuation line over-indented for visual indent

/home/travis/build/Theano/Theano/theano/tensor/tests/test_opt.py:5455:31: E127 continuation line over-indented for visual indent
```

**Comment by kvmanohar22** [comment]
I ran the command  `$nosetests theano/tests/test_flake8.py` and the output was as follows: 
```
S
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK (SKIP=1)

```

and there were no changes which I could notice, how do I proceed further ?

**Comment by nouiz** [comment]
You probably don't have all optional Theano dependency installed. This is
why the test is skipped.

In particular, do you have installed flake8?

**Comment by nouiz** [comment]
Just a note that this PR is in conflict.

**Comment by nouiz** [comment]
No news for a long time and many conflict, so I'll close. If you continue it, you can reopen it.

**Pull request closed without merging**
