### PR TITLE
Support .theanorc files in the current working directory

### PR DESCRIPTION
**Pull request by tillahoffmann**
Load `.theanorc` configuration file in the current working directory similar to [matplotlib](http://matplotlib.org/users/customizing.html#the-matplotlibrc-file).

### CODE REVIEW

**Comment by nouiz** [comment]
@abergeron @lamblin what do you think?

If we accept that, it should be documented in the file doc/library/config.txt

**Comment by lamblin** [comment]
I'm not sure it is a good idea to have it on by default.
We could explicitly document that, if it is the desired behaviour, it is possible to set `THEANORC=~/.theanorc:.theanorc`

**Comment by nouiz** [comment]
I like that solution. @tillahoffmann do you want to update the PR for this?

thanks for bringing this to our attention.

**Comment by tillahoffmann** [comment]
Added some text to the documentation describing how to load local configuration files.

**Comment by nouiz** [comment]
thanks

**Pull request merged**
