### PR TITLE
Fix slips from PR #4244

### PR DESCRIPTION
**Pull request by bouthilx**

### CODE REVIEW

**Comment by nouiz** [comment]
Seem good to me. We can merge when the travis part for doc passed.

**Comment by bouthilx** [comment]
Wait, there is a last bug that I didn't fixed yet. I'm trying to understand it.

**Comment by nouiz** [comment]
ok, killing travis.

**Comment by bouthilx** [comment]
OK False alarm.

**Comment by nouiz** [comment]
The doc part of travis passed, so I merge as trvis don't test this change.

**Pull request merged**
