### PR TITLE
Better same_shape implementation

### PR DESCRIPTION
**Pull request by nouiz**
fix gh-2585 ?

not ready to merge. Not tested

### CODE REVIEW

**Comment by sisp** [comment]
Tests are failing because there is an unnecessary `Assert` op in the graph due to unnecessary `Elemwise{eq}` ops. The graph looks like this:
theano
I'm not sure, if this fixes the root cause, but an optimization that removes unnecessary `Elemwise{eq}` ops makes the tests pass.
```
diff --git a/theano/tensor/opt.py b/theano/tensor/opt.py
index 96c1f97..1cfb4c2 100644
--- a/theano/tensor/opt.py
+++ b/theano/tensor/opt.py
@@ -2643,6 +2643,44 @@ def local_adv_sub1_adv_inc_sub1(node):
     return [T.cast(y, node.outputs[0].dtype)]
 
 
+###########################
+# Logical comparison opts #
+###########################
+
+@register_canonicalize
+@register_specialize
+@register_stabilize
+@gof.local_optimizer([T.Elemwise])
+def local_useless_eq(node):
+    """
+    Remove EQ op if it's not needed.
+    """
+    if (isinstance(node.op, T.Elemwise) and
+        isinstance(node.op.scalar_op, scalar.EQ)):
+        x, y = node.inputs
+        true = T.as_tensor_variable(1)
+
+        if x is y:
+            return [true]
+
+        if x == y:
+            return [true]
+
+        if (x.owner is not None and
+            y.owner is not None and
+            x.owner.op == y.owner.op and
+            len(x.owner.inputs) == len(y.owner.inputs) and
+            all((xi is yi) or (xi == yi)
+                for xi, yi in zip(x.owner.inputs, y.owner.inputs))):
+            return [true]
+
+        from theano.scan_module.scan_utils import equal_computations
+        if equal_computations([x], [y]):
+            return [true]
+
+    return False
+
+
 ####################
 # Rebroadcast opts #
 ####################
```
What do you think?

**Comment by nouiz** [comment]
@lamblin I added tests to this PR. Can you review it?

**Comment by lamblin** [comment]
@nouiz It looks reasonable, but now one test is failing, probably because there is no Op removing "eq(x, x)".
Should we disable the test until this is fixed in a different PR?

**Comment by nouiz** [comment]
I updated this PR. The remove of the useless eq op is done in the local_useless_elemwise and it run during specialize like the local_elemwise_alloc opt. The problem is that local_useless_elemwise check if both input are exactly the same object. But they aren't as the merge optimizer do not run during specialize, but just after.

My fix is to not introduce the assert as we can detect this. Introducing the merge optimizer during specialize would also have fixed this. But I'm not sure we should do this.

@lamblin do you remember why it isn't in specialize? Historycal reason (slowness) only? Is there current reason to not do this now as it is faster? If we do this, it should be in another PR.

**Comment by lamblin** [comment]
Regarding the merge thing, I don't remember exactly, but now there should be a feature tracking the equivalent variables, even before they are substituted, so we could either use the feature, or force the merge more often (which could be slower).

**Comment by nouiz** [comment]
I updated the PR with your suggestion.

**Pull request merged**
