### PR TITLE
Follow the change in call protocol in libgpuarray.

### PR DESCRIPTION
**Pull request by abergeron**
I'm talking about https://github.com/Theano/libgpuarray/pull/46.

### CODE REVIEW

**Comment by nouiz** [comment]
I think it is ok, but I wait until libgpuarray PR get merged and I'll then run the tests.

**Comment by abergeron** [comment]
Done.

**Comment by nouiz** [comment]
This need a rebase.

**Comment by abergeron** [comment]
Rebased

**Pull request merged**
