### PR TITLE
Implement GpuAdvancedSubtensor1 for gpuarray

### PR DESCRIPTION
**Pull request by abergeron**
This also fixes a number of problems with GpuAdvancedIncSubtensor1_dev20 and makes it raise IndexError appropriately.

This depends on https://github.com/Theano/libgpuarray/pull/63

### CODE REVIEW

**Comment by nouiz** [comment]
I get many errors like this on oolong:

```
======================================================================
ERROR: test_advanced1_inc_and_set (theano.sandbox.gpuarray.tests.test_subtensor.G_subtensor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/u/bastienf/repos/Theano/theano/tensor/tests/test_subtensor.py", line 1042, in test_advanced1_inc_and_set
    f_outs = f(*all_inputs_num)
  File "/u/bastienf/repos/Theano/theano/compile/function_module.py", line 618, in __call__
    storage_map=self.fn.storage_map)
  File "/u/bastienf/repos/Theano/theano/gof/link.py", line 297, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/u/bastienf/repos/Theano/theano/compile/function_module.py", line 607, in __call__
    outputs = self.fn()
  File "/u/bastienf/repos/Theano/theano/gof/op.py", line 761, in rval
    r = p(n, [x[0] for x in i], o)
  File "/u/bastienf/repos/Theano/theano/sandbox/gpuarray/subtensor.py", line 527, in perform
    k(x[i], reshaped_y, broadcast=True)
  File "/u/bastienf/.local/lib64/python2.7/site-packages/pygpu-0.2.1-py2.7-linux-x86_64.egg/pygpu/elemwise.py", line 489, in __call__
    k(*args, n=n)
  File "pygpu/gpuarray.pyx", line 1898, in pygpu.gpuarray.GpuKernel.__call__ (pygpu/gpuarray.c:22057)
  File "pygpu/gpuarray.pyx", line 1962, in pygpu.gpuarray.GpuKernel.do_call (pygpu/gpuarray.c:22666)
  File "pygpu/gpuarray.pyx", line 1998, in pygpu.gpuarray.GpuKernel._setarg (pygpu/gpuarray.c:23066)
ValueError: Bad typecode in _setarg (please report this, it is a bug)
Apply node that caused the error: GpuAdvancedIncSubtensor1{inplace,inc}(GpuFromHost(gpuarray).0, GpuFromHost(gpuarray).0, <TensorType(int64, vector)>)
Toposort index: 213
Inputs types: [<theano.sandbox.gpuarray.type.GpuArrayType object at 0x7f8b5a5e3350>, <theano.sandbox.gpuarray.type.GpuArrayType object at 0x7f8b5a647290>, TensorType(int64, vector)]
Inputs shapes: [(4, 5), (1,), (2,)]
Inputs strides: [(20, 4), (4,), (8,)]
Inputs values: ['not shown', <pygpu.gpuarray.GpuArray object at 0x7f8b691c5f30>, array([3, 1])]
Outputs clients: [[HostFromGpu(gpuarray)(GpuAdvancedIncSubtensor1{inplace,inc}.0)]]
```

I run this with a recompiled libgpuarray from today and a clean Theano cache.

**Comment by abergeron** [comment]
I removed the assert and https://github.com/Theano/libgpuarray/pull/76 should fix the other problem.

**Comment by abergeron** [comment]
What is happening with this?

**Comment by nouiz** [comment]
this need a rebase

**Comment by nouiz** [comment]
this need a rebase

**Comment by abergeron** [comment]
Rebase done.

**Comment by nouiz** [comment]
I have this error:
```
======================================================================
ERROR: test_adv_sub1_broadcast (theano.sandbox.gpuarray.tests.test_subtensor.G_subtensor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/u/bastienf/repos/Theano/theano/tensor/tests/test_subtensor.py", line 541, in test_adv_sub1_broadcast
    g = self.function([idx], gn, op=self.adv_incsub1)
  File "/u/bastienf/repos/Theano/theano/tensor/tests/test_subtensor.py", line 91, in function
    accept_inplace=accept_inplace)
  File "/u/bastienf/repos/Theano/theano/compile/function.py", line 309, in function
    output_keys=output_keys)
  File "/u/bastienf/repos/Theano/theano/compile/pfunc.py", line 511, in pfunc
    output_keys=output_keys)
  File "/u/bastienf/repos/Theano/theano/compile/function_module.py", line 1761, in orig_function
    defaults)
  File "/u/bastienf/repos/Theano/theano/compile/function_module.py", line 1625, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/u/bastienf/repos/Theano/theano/gof/link.py", line 683, in make_thunk
    storage_map=storage_map)[:3]
  File "/u/bastienf/repos/Theano/theano/gof/vm.py", line 1037, in make_all
    no_recycling))
  File "/u/bastienf/repos/Theano/theano/gof/op.py", line 918, in make_thunk
    no_recycling)
  File "/u/bastienf/repos/Theano/theano/gof/op.py", line 836, in make_c_thunk
    output_storage=node_output_storage)
  File "/u/bastienf/repos/Theano/theano/gof/cc.py", line 1175, in make_thunk
    keep_lock=keep_lock)
  File "/u/bastienf/repos/Theano/theano/gof/cc.py", line 1113, in __compile__
    keep_lock=keep_lock)
  File "/u/bastienf/repos/Theano/theano/gof/cc.py", line 1549, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/u/bastienf/repos/Theano/theano/gof/cmodule.py", line 1130, in module_from_key
    src_code = lnk.get_src_code()
  File "/u/bastienf/repos/Theano/theano/gof/cc.py", line 1419, in get_src_code
    mod = self.get_dynamic_module()
  File "/u/bastienf/repos/Theano/theano/gof/cc.py", line 1477, in get_dynamic_module
    self.code_gen()
  File "/u/bastienf/repos/Theano/theano/gof/cc.py", line 773, in code_gen
    name))
  File "/u/bastienf/repos/Theano/theano/sandbox/gpuarray/subtensor.py", line 783, in c_support_code_apply
    return super(GpuAdvancedIncSubtensor1_dev20, self).c_support_code_apply(node, nodename) + """
  File "/u/bastienf/repos/Theano/theano/sandbox/gpuarray/basic_ops.py", line 158, in c_support_code_apply
    bins = '\n'.join(self._generate_kernel_bin(k) for k in kernels)
  File "/u/bastienf/repos/Theano/theano/sandbox/gpuarray/basic_ops.py", line 158, in <genexpr>
    bins = '\n'.join(self._generate_kernel_bin(k) for k in kernels)
  File "/u/bastienf/repos/Theano/theano/sandbox/gpuarray/basic_ops.py", line 132, in _generate_kernel_bin
    gk = gpuarray.GpuKernel(k.code, k.name, k.params, **k.flags)
  File "pygpu/gpuarray.pyx", line 1890, in pygpu.gpuarray.GpuKernel.__cinit__ (pygpu/gpuarray.c:21843)
  File "pygpu/gpuarray.pyx", line 452, in pygpu.gpuarray.kernel_init (pygpu/gpuarray.c:6389)
GpuArrayException: ('The following error happened while compiling the node', GpuAdvancedIncSubtensor1_dev20{inplace,inc}(GpuAlloc.0, GpuArrayConstant{[[ 1.]]}, GpuFromHost(gpuarray).0), '\n', u'CUDA kernel build failure ::\n0001\t#define local_barrier() __syncthreads()\n0002\t#define WITHIN_KERNEL extern "C" __device__\n0003\t#define KERNEL extern "C" __global__\n0004\t#define GLOBAL_MEM /* empty */\n0005\t#define LOCAL_MEM __shared__\n0006\t#define LOCAL_MEM_ARG /* empty */\n0007\t#define REQD_WG_SIZE(X,Y,Z) __launch_bounds__(X*Y, Z)\n0008\t#ifdef NAN\n0009\t#undef NAN\n0010\t#endif\n0011\t#define NAN __int_as_float(0x7fffffff)\n0012\t#define LID_0 threadIdx.x\n0013\t#define LID_1 threadIdx.y\n0014\t#define LID_2 threadIdx.z\n0015\t#define LDIM_0 blockDim.x\n0016\t#define LDIM_1 blockDim.y\n0017\t#define LDIM_2 blockDim.z\n0018\t#define GID_0 blockIdx.x\n0019\t#define GID_1 blockIdx.y\n0020\t#define GID_2 blockIdx.z\n0021\t#define GDIM_0 gridDim.x\n0022\t#define GDIM_1 gridDim.y\n0023\t#define GDIM_2 gridDim.z\n0024\t#define ga_bool unsigned char\n0025\t#define ga_byte signed char\n0026\t#define ga_ubyte unsigned char\n0027\t#define ga_short short\n0028\t#define ga_ushort unsigned short\n0029\t#define ga_int int\n0030\t#define ga_uint unsigned int\n0031\t#define ga_long long long\n0032\t#define ga_ulong unsigned long long\n0033\t#define ga_float float\n0034\t#define ga_double double\n0035\t#define ga_half ga_ushort\n0036\t#define ga_size size_t\n0037\t#define ga_ssize ptrdiff_t\n0038\t\n0039\t/*\n0040\t * This is an atomicAdd that works for doubles since that is not provided\n0041\t * natively by cuda.\n0042\t */\n0043\t__device__ double atomicAdd(ga_double* address, ga_double val) {\n0044\t    unsigned long long int* address_as_ull =\n0045\t                                          (unsigned long long int*)address;\n0046\t    unsigned long long int old = *address_as_ull, assumed;\n0047\t    do {\n0048\t        assumed = old;\n0049\t        old = atomicCAS(address_as_ull, assumed,\n0050\t                        __double_as_longlong(val +\n0051\t                        __longlong_as_double(assumed)));\n0052\t    } while (assumed != old);\n0053\t    return __longlong_as_double(old);\n0054\t}\n0055\t\n0056\t/*\n0057\t * This is a version of atomicAdd that works for half-floats.  It may\n0058\t * read and write 2 bytes more than the size of the array if the array\n0059\t * has an uneven number of elements.  The actual value at that spot\n0060\t * will not be modified.\n0061\t */\n0062\t\n0063\t__device__ ga_half atomicAdd(ga_half *addr, ga_half val) {\n0064\t  ga_uint *base = (ga_uint *)((ga_size)addr & ~2);\n0065\t  ga_uint old, assumed, sum, new_;\n0066\t  old = *base;\n0067\t  do {\n0068\t    assumed = old;\n0069\t    sum = __float2half_rn(\n0070\t      __half2float(val) +\n0071\t      __half2float((ga_half)__byte_perm(old, 0,\n0072\t                     ((ga_size)addr & 2) ? 0x4432 : 0x4410)));\n0073\t    new_ = __byte_perm(old, sum, ((ga_size)addr & 2) ? 0x5410 : 0x3254);\n0074\t    old = atomicCAS(base, assumed, new_);\n0075\t  } while (assumed != old);\n0076\t  return (ga_half)__byte_perm(old, 0,\n0077\t                                  ((ga_size)addr & 2) ? 0x4432 : 0x4410);\n0078\t}\n0079\t\n0080\t        KERNEL void k_vector_add_fast(const ga_size numRowsX,\n0081\t                                      const ga_size numColsX,\n0082\t                                      const ga_ssize stridesX0,\n0083\t                                      const ga_ssize stridesX1,\n0084\t                                      ga_float *X,\n0085\t                                      const ga_size offset_X,\n0086\t                                      const ga_size numRowsY,\n0087\t                                      const ga_size numColsY,\n0088\t                                      const ga_ssize stridesY0,\n0089\t                                      const ga_ssize stridesY1,\n0090\t                                      ga_float *Y,\n0091\t                                      const ga_size offset_Y,\n0092\t                                      const ga_size numIndices,\n0093\t                                      const ga_ssize stridesIndices,\n0094\t                                      ga_long *indices_arr,\n0095\t                                      const ga_size offset_indices_arr,\n0096\t                                      ga_int *err)\n0097\t        {\n0098\t             X = (ga_float *)(((char *)X)+offset_X);\n0099\t             Y = (ga_float *)(((char *)Y)+offset_Y);\n0100\t             indices_arr = (ga_long *)(((char *)indices_arr)+offset_indices_arr);\n0101\t             for (int i = (blockIdx.x); i < numIndices; i += gridDim.x)\n0102\t             {\n0103\t                  for(int j = (threadIdx.x); j < numColsX;j += blockDim.x)\n0104\t                  {\n0105\t                      ssize_t x_row = indices_arr[i * stridesIndices];\n0106\t                      if (x_row < 0)\n0107\t                          x_row += numRowsX;\n0108\t                      ssize_t y_row = i;\n0109\t                      if (x_row < numRowsX && x_row >= 0) {\n0110\t                        atomicAdd(&X[(x_row * stridesX0) + (j * stridesX1)], Y[(y_row * stridesY0) + (j * stridesY1)]);\n0111\t                      } else {\n0112\t                        *err = 1;\n0113\t                      }\n0114\t                  }\n0115\t             }\n0116\t             return;\n0117\t        }\n0118\t        ')

----------------------------------------------------------------------

```

**Comment by abergeron** [comment]
I tried with cuda 7.0 and 7.5, with my 750 and 610 and I don't have any problem with those combinations.

I'll need more info to reproduce/fix the issue.

**Comment by nouiz** [comment]
Try on oolong.

**Comment by abergeron** [comment]
There shouldn't be anymore compilation problems.

**Comment by nouiz** [comment]
Tests pass here, when travis pass, we can merge.

**Pull request merged**
