### PR TITLE
Fix crash on Mac with curand op. We where using g++ extention that MSVC ...

### PR DESCRIPTION
**Pull request by nouiz**
...also supported

### CODE REVIEW

**Comment by abergeron** [comment]
What is the crash exactly?

**Comment by abergeron** [comment]
Never mind I get it.  We where using pointer manipulation on void*, which is forbidden by the standard.

**Comment by nouiz** [comment]
See the report of the error: https://groups.google.com/forum/#!topic/theano-users/yCa4CrPW_5w

**Comment by abergeron** [comment]
But I would use `PyArray_GETPTR1(%(size)s, i)[0]` instead to make this cleaner

**Comment by lamblin** [comment]
Should you update the version as well?

**Comment by nouiz** [comment]
I used the more clear code. I didn't change the version as the code is equivalent and it just fix crash with clang. No need to recompile if it compiled correctly before.

**Comment by abergeron** [comment]
You still need the cast to npy_int32

**Comment by nouiz** [comment]
I amended the last commit. I ran the test locally for that file and they passed.

**Pull request merged**
