### PR TITLE
Canopy win

### PR DESCRIPTION
**Pull request by nouiz**
This is a test fix for gh-1791

wait for confirmation by user that this fix the problem.

### CODE REVIEW

**Comment by abergeron** [comment]
I worry about how maintainable that approach is.  Could it be possible to interrogate the canopy database to make sure the relevant packages are present?

**Comment by nouiz** [comment]
As I cache the call, now the message will be printed only once per process.
So it will be much more tolerable.

I think it do not change too frequently. I do not know how to query that
db...

**Comment by nouiz** [comment]
@abergeron can you review this PR? I think we can merge it if we do not introduce new problem with old config (I mean, we do raise warning when we didn't) and that maybe we remove the warning with newer canopy version?

This PR will remove duplicate warning and this is good, so maybe we shouldn't way and merge it today?

**Comment by abergeron** [comment]
I still worry about the approach, but it's an improvement, so let's merge this and see later for maybe a better solution overall

**Pull request merged**
