### PR TITLE
Change default value of reoptimize_unpickled_function

### PR DESCRIPTION
**Pull request by nouiz**

### CODE REVIEW

**Comment by nouiz** [comment]
Wait after NIPS to merge.

**Comment by carriepl** [comment]
After IRL discussion with @nouiz; he says he should revisit this PR before merging so, even if this is after NIPS, this PR shouldn't be merged as it is.

**Comment by nouiz** [comment]
I updated this PR. I'm not sure how to warn user about the interface change. What do you think? I think we can just email again on the mailing list. If you disagree, tell it.

**Comment by nouiz** [comment]
@lamblin @abergeron what do you think of this PR?

**Comment by lamblin** [comment]
OK for me.

**Pull request merged**
