### PR TITLE
make gpuarray/test_fft compatible with numpy<1.10

### PR DESCRIPTION
**Pull request by slefrancois**

### CODE REVIEW

**Comment by lamblin** [comment]
OK for me if Travis passes.

**Comment by slefrancois** [comment]
jenkins test this please

**Comment by slefrancois** [comment]
jenkins test this please

**Comment by slefrancois** [comment]
jenkins test this please

**Comment by slefrancois** [comment]
jenkins test this please

**Comment by slefrancois** [comment]
jenkins test this please

**Comment by slefrancois** [comment]
jenkins test this please

**Comment by slefrancois** [comment]
jenkins test this please

**Comment by slefrancois** [comment]
jenkins test this please

**Comment by slefrancois** [comment]
jenkins test this please

**Comment by slefrancois** [comment]
jenkins test this please

**Pull request closed without merging**
